### ISSUE TITLE
报NullPointerException异常 

### ISSUE THREAD

**Issue by birdroidcn** [medcl/elasticsearch-analysis-ik#100]
ES版本:1.5.1

analysis-ik:1.3.0 自己编译打包 pom文件ES版本号已经修改成了1.5.1

按照readme上的样例，成功加了mapping

但是添加文档时报错：
```
{"error":"NullPointerException[null]","status":500}
```
can anyone help me?

**Comment by birdroidcn** [comment]
是没有配置config
close

**Comment by xxllp** [comment]
这个config 是要放到哪里哈

**Comment by chentaikuang** [comment]
配置什么config，怎么配置
