### ISSUE TITLE
8.3.1b版本使用8.3.3版本，重新编译安装成功后，使用报错

### ISSUE THREAD

**Issue by tyzhong** [medcl/elasticsearch-analysis-ik#1006]
我是用的es版本是8.3.1，下载8.3.3源码，修改其中的版本依赖：
<groupId>org.ansj</groupId><artifactId>elasticsearch-analysis-ansj</artifactId>
<version>8.3.1.0</version>
<description>elasticsearch analysis by ansj</description>
<name>elasticsearch-analysis-ansj</name>
<urT>http://maven.nlpcn.org</url>
<properties>
<project.build.sourceEncoding>UTF-8</project.build.sourceEncodinq>
<runSuite>**/MainTestSuite.class</runSuite>
<elasticsearch.plugin.name>elasticsearch-analysis-ansj</elasticsearch.plugin.name><elasticsearch.plugin.java.version>17</elasticsearch.plugin.java.version>
<elasticsearch.version>8.3.1</elasticsearch.version>
<elasticsearch.plugin.classname>org.ansj.elasticsearch.plugin.AnalysisAnsjPlugin</elasticsearch.plugin.classname
</properties>
重新打包安装正常
使用api调用的方式可以正常使用：
localhost:9200/ cat/ansi?text=中国&tvpe=indey oni
但是kibana中使用调用
POST _analyze
{
  "text": ["美国阿拉斯加州发生8.0级地震"],
  "analyzer": "index_ansj"
}
测报错：
{
  "error": {
    "root_cause": [
      {
        "type": "null_pointer_exception",
        "reason": """Cannot invoke "String.length()" because "s" is null"""
      }
    ],
    "type": "null_pointer_exception",
    "reason": """Cannot invoke "String.length()" because "s" is null"""
  },
  "status": 500
}

**Comment by ilaotan** [comment]
elasticsearch-analysis-ansj 这个仓库的？
