### ISSUE TITLE
8.9.0

### ISSUE THREAD

**Issue by niu-dali** [medcl/elasticsearch-analysis-ik#1012]
8.9.0
[elasticsearch-analysis-ik-8.9.0.zip](https://github.com/medcl/elasticsearch-analysis-ik/files/12237226/elasticsearch-analysis-ik-8.9.0.zip)

**Comment by niu-dali** [comment]
[elasticsearch-analysis-ik-8.9.0.zip](https://github.com/medcl/elasticsearch-analysis-ik/files/12237226/elasticsearch-analysis-ik-8.9.0.zip)

**Comment by duhbbx** [comment]
孩子饿了，奶来了

**Comment by FreedomRights** [comment]
顶
