### ISSUE TITLE
你好，请帮忙支持下7.17.12。 

### ISSUE THREAD

**Issue by Changego** [medcl/elasticsearch-analysis-ik#1017]
你好，请帮忙支持下7.17.12。 
下载7.17.6 修改 plugin-descriptor.properties内版本即可？

**Comment by JohnieCheng** [comment]
这个需要自己下载源码编译。下载master分支，
修改elasticsearch.version为7.17.12：
![image](https://github.com/medcl/elasticsearch-analysis-ik/assets/70625981/ddc829a2-1abf-4d19-9914-0e013cc95634)
修改源码错误：
![image](https://github.com/medcl/elasticsearch-analysis-ik/assets/70625981/bdd1fb26-0b74-40fc-9f8d-1bd7c7269c28)

然后在项目根目录依次执行：
mvn clean
mvn compile
mvn package

在target\releases文件夹下获得elasticsearch-analysis-ik-7.17.12.zip文件。

我自己操作过，es能正常启动

**Comment by puppylpg** [comment]
> 这个需要自己下载源码编译。下载master分支， 修改elasticsearch.version为7.17.12： ![image](https://user-images.githubusercontent.com/70625981/266279822-ddc829a2-1abf-4d19-9914-0e013cc95634.png) 修改源码错误： ![image](https://user-images.githubusercontent.com/70625981/266280265-bdd1fb26-0b74-40fc-9f8d-1bd7c7269c28.png)
> 
> 然后在项目根目录依次执行： mvn clean mvn compile mvn package
> 
> 在target\releases文件夹下获得elasticsearch-analysis-ik-7.17.12.zip文件。
> 
> 我自己操作过，es能正常启动

nb！7.17.13也可以这么搞

**Comment by shandy-0** [comment]
编译不通过，org.elasticsearch.core.PathUtils包找不到怎么办？
