### ISSUE TITLE
8.7.1 版本的分词器没有

### ISSUE THREAD

**Issue by huyang19881115** [medcl/elasticsearch-analysis-ik#1019]
es 版本 8.7.1 ，但是使用8.7.0 的ik 分词插件，会报错

**Comment by lizongbo** [comment]
构建了一个包放上去了，代码没变化，只是改配置里的版本号。
https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v8.7.1

**Comment by lizongbo** [comment]
来源参考 https://github.com/medcl/elasticsearch-analysis-ik/issues/1028
