### ISSUE TITLE
构建了 8.10.2 ，8.10.3，8.10.4，7.17.14供使用

### ISSUE THREAD

**Issue by lizongbo** [medcl/elasticsearch-analysis-ik#1028]
elasticsearch-analysis-ik 新包构建说明

elasticsearch-analysis-ik作者创业之后应该是没时间维护这个插件了，
没有构建支持8.10.2版本的包，于是自己fork了代码，拉到本地修改修改pom.xml中的版本号，比如：
<elasticsearch.version>8.10.2</elasticsearch.version>
修改之后运行构建命令 mvn clean compile package，打包成功，得到elasticsearch-analysis-ik-8.10.2.zip
插件安装命令示例：
./elasticsearch-plugin -v install file:///var/services/homes/lizongbo/esplugins/elasticsearch-analysis-ik-8.10.2.zip

为方便大家使用，我构建了以下版本的包供使用：

8.10.2,8.10.3,8.10.4,7.17.14

https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v8.10.2
https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v8.10.3
https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v8.10.4
https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v7.17.14
https://github.com/lizongbo/elasticsearch-analysis-ik/releases/tag/v8.7.1

有其它版本包需求的也可以在此提出来，我可以构建上传。

**Comment by winnershili** [comment]
不错哦

**Comment by calacaly** [comment]
A good person lives a peaceful life
