### ISSUE TITLE
谁有兴趣一起维护插件后续版本的，一起探讨交流

### ISSUE THREAD

**Issue by lizongbo** [medcl/elasticsearch-analysis-ik#1029]
先前一直是使用各种开源组件，比较少参与代码建设。
最近参加了阿里开源的数据库连接池druid组件的特性开发，地址是 https://github.com/alibaba/druid 
基本熟悉了github提交代码的流程。

目前看ik插件作者创业当老板之后，估计是没啥时间持续维护插件特性了。
因此这几天fork了[elasticsearch-analysis-ik](https://github.com/medcl/elasticsearch-analysis-ik) 等插件代码，

构建了ES对应版本所需的插件，然后在现有代码上，做了以下优化：
1.Character对象实力全部使用缓存机制。
2.增加国标GB18030-2022的生僻字分词。
3.引入maven checkstyle插件，格式化代码，确保后续代码格式风格一致。

看了现在处于open的一些Issue，后续打算实现以下特性：
1.支持单个字符的繁体转简体
2.支持按索引配置对应的远程扩展词库。
以及其它实用的特性。

有兴趣的欢迎一起交流。
我fork的代码地址在：
https://github.com/lizongbo/elasticsearch-analysis-ik
拼音插件也准备后续维护更新，增加更多的拼音内容。
https://github.com/lizongbo/elasticsearch-analysis-pinyin

**Comment by medcl** [comment]
欢迎贡献本项目！

**Comment by lizongbo** [comment]
> 欢迎贡献本项目！

提交了pr，你看下没问题的化就合并进去吧。
代码支持mvn validate 检查checkstyle格式。
