### ISSUE TITLE
es版本7.17.13 ik版本 8.5.0 不兼容  java.lang.NoSuchMethodError: 'void org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider

### ISSUE THREAD

**Issue by ZiiYuann** [medcl/elasticsearch-analysis-ik#1031]
在es 版本8.2.3升级到8.3.0的过程中，AbstractIndexAnalyzerProvider的构造函数由public AbstractIndexAnalyzerProvider(IndexSettings indexSettings, String name, Settings settings) 改为了public AbstractIndexAnalyzerProvider(String name, Settings settings) ，同样的IK的版本在8.3.0也进行了升级。这说明8.2.3版本以前（包括8.2.3）与IK 8.3.0（包括8.3.0）之后的版本是不兼容的，会抛出java.lang.NoSuchMethodError: 'void org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider.<init>(java.lang.String, org.elasticsearch.common.settings.Settings)' 异常。
所以使用elasticsearch 8.2.3 前的伙伴们要注意 ik的版本至少不要超过 8.2.3（其他版本暂未测试），留个言方便碰到同样问题的小伙伴参考一下

**Comment by medcl** [comment]
不同版本不保证一定兼容的，ES 和插件版本要一一对应。
