### ISSUE TITLE
是否可以出个V7.17.15的版本？

### ISSUE THREAD

**Issue by AlbertYou** [medcl/elasticsearch-analysis-ik#1036]
Elasticsearch 7的版本已经更新到7.17.15，请问elasticsearch-analysis-ik 能否提供一个适配7.17.15的版本，谢谢啦！

**Comment by AcaciusShun** [comment]
need the elasticsearch-analysis-ik-1.17.15 alse

**Comment by bocaiJs** [comment]
老哥你现在用的什么版本的呀。

**Comment by AlbertYou** [comment]
> 老哥你现在用的什么版本的呀。

 v7.17.7

**Comment by fishbigbig** [comment]
同求7.17.15版本的，谢谢！

**Comment by Pane1234** [comment]
7.17.15现有的有能用的分词器吗

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v7.17.15
