### ISSUE TITLE
求8.12版本的ik

### ISSUE THREAD

**Issue by yanchaoguo** [medcl/elasticsearch-analysis-ik#1041]
号称最快的版本8.12， 
作者的还没更新，我编译好了一个 需要的拿去

**Comment by yanchaoguo** [comment]
[Uploading elasticsearch-analysis-ik-8.12.0.zip…]()

**Comment by Jzhnakui** [comment]
感谢！！！

**Comment by medcl** [comment]
早就已经有了
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v8.12.0

Issue 里面请不要再灌水和版本相关的内容。
