### ISSUE TITLE
ES8.9.2，没有对应的release版本

### ISSUE THREAD

**Issue by shengjianzhou** [medcl/elasticsearch-analysis-ik#1045]
ES8.9.2，没有对应的release版本，最好有编译好的jar包，可以直接使用

**Comment by shengjianzhou** [comment]
在这个issue里找到下载地址了，但是最好在release里发布，方便大家查找，谢谢！
https://github.com/medcl/elasticsearch-analysis-ik/issues/1015

**Comment by medcl** [comment]
已发布，release 相关的帖子请不要在这里，如果版本发布不及时，麻烦前往 Discord ( https://discord.gg/NtZgghfW)，谢谢合作。
