### ISSUE TITLE
无法加载plugin的相关class Unknown Analyzer type 

### ISSUE THREAD

**Issue by fimoon** [medcl/elasticsearch-analysis-ik#107]
ES: 2.0, ik-analyzer:1.5.0, JDK:1.7

```
 curl -XPUT http://10.0.0.20:9200/index?pretty
```

```
{
  "error" : {
    "root_cause" : [ {
      "type" : "index_creation_exception",
      "reason" : "failed to create index"
    } ],
    "type" : "illegal_argument_exception",
    "reason" : "Unknown Analyzer type [org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin] for [ik]"
  },
  "status" : 400
}
```

elasticsearch.yml 配置如下：
```
index :
    analysis :
        analyzer :
            ik :
                type : "org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin"
            ik_smart:
                type : ik
                use_smart : true
```

plugin-descriptor.properties 配置如下：

```
description=IK Analyzer for ElasticSearch
version=1.5.0
name=ik
site=${elasticsearch.plugin.site}
jvm=true
classname=org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
java.version=${maven.compiler.target}
elasticsearch.version=2.0.0

```

**Comment by medcl** [comment]
1.5里面直接能用,不需要单配,
Analyzer: ik_smart , ik_max_word , Tokenizer: ik_smart , ik_max_word

**Comment by fimoon** [comment]
以前的配置都是写成了ik，我想在少改变以前配置的情况下升级，想在这里加一个别名，我写type: ik_max_word， 还是出现Unknown Analyzer type，这里是不需要单配，还是不能单配？

**Comment by fimoon** [comment]
```
index :
    analysis :
        analyzer :
            ik :
                type: custom
                tokenizer: ik_max_word
```
现在我这样搞，好像work了，2.0好像不支持直接加载一个类了，可能是出于安全的考虑？
https://github.com/elastic/elasticsearch/blame/2.0/core/src/main/java/org/elasticsearch/index/analysis/AnalysisModule.java#L321

**Comment by codykong** [comment]
我用你的配置后发现这个错误，我的es用的2.1.1，这是什么问题？

{
  "error": {
    "root_cause": [
      {
        "type": "index_creation_exception",
        "reason": "failed to create index"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Custom Analyzer [ik] failed to find tokenizer under name [ik_max_word]"
  },
  "status": 400
}

**Comment by medcl** [comment]
@codykong 2.1.1可以看看rtf里面是如何配的 https://github.com/medcl/elasticsearch-rtf
