### ISSUE TITLE
match搜索时，如何将搜索的词汇进行分词

### ISSUE THREAD

**Issue by syx114** [medcl/elasticsearch-analysis-ik#110]
我搜索衬衫，可以出来很多，搜索针织衬衫，就什么都出不来了，尽管有一模一样叫针织衬衫的

**Comment by medcl** [comment]
match是term匹配，你换个querystring或者textquery就好了

send via my Phone.

**Comment by medcl** [comment]
说错了，不是 term 匹配，也会使用 analyzer 对 query 分词，你的问题还要看看具体是怎么设置的 mapping，这个问题太久了，欢迎重开
