### ISSUE TITLE
怎样实现粗粒度分词?

### ISSUE THREAD

**Issue by nsspw** [medcl/elasticsearch-analysis-ik#112]
即怎样配置把匹配度高的文本搜索出来?
举个例子,通过ES的API搜索"女衬衫",它默认会把含有"女"或"衬衫"都搜出来,但部分含有"女"字的文本都跟衬衫没关系的，这样用户体验就不好了。
请问要怎么配置,谢谢!
ES版本:1.7.1
IK版本:1.4.0

**Comment by vnnw** [comment]
添加“女衬衫”新词？

**Comment by nsspw** [comment]
那添加的词就多了，有没有更“轻量级”的解决办法?

**Comment by medcl** [comment]
不用这么复杂的,你设置查询的operator=AND,这样就只会返回同时匹配"女"和"衬衫"的结果
