### ISSUE TITLE
Unfulfilled properties in plugin-descriptor.properties

### ISSUE THREAD

**Issue by 3str** [medcl/elasticsearch-analysis-ik#119]
Hi,

I compiled the latest code (version 1.5.1) with maven on amazon-linux with javajdk-1.7. The plugin-descriptor.properties contained in target/releases/elasticsearch-analysis-ik-1.5.1.zip is stopping elasticsearch from starting, because the following properties are not defined in the file.

name=${elasticsearch.plugin.name}
site=${elasticsearch.plugin.site}
java.version=${maven.compiler.target}
isolated=${elasticsearch.plugin.isolated}

I tried to fill in those settings, making site=false, isolated=true. Elasticsearch would be able to start, but the cluster health would be **red**! What should I do?

**Comment by medcl** [comment]
33fb6ad67ee52a3d58b749de27bee06cf219daef fixed in master

**Comment by jocundmo** [comment]
Hey, I'm getting this unfulfilled issue, I downloaded the zip, unzip and executed 'mvn package', all seems to success, after that, I get a 'elasticsearch-analysis-ik-1.7.0.jar' file, inside there is 'plugin-descriptor.properties' which is totally unset, what steps I missed?

**Comment by medcl** [comment]
Hi,@jocundmo please use the package in release

**Comment by kmsheng** [comment]
@medcl Do you know how to build plugin-descriptor.properties properly ? I have the same problem as @jocundmo  I am using maven 3.3.9 on mac.

**Comment by medcl** [comment]
@kmsheng  give the error msg or what's the detail issue about plugin-descriptor.properties, this file is included in relase/ik-***.zip

**Comment by kmsheng** [comment]
@medcl Hey! Thanks for replying. I've upgraded my java to 1.8 and this issue's gone.
