### ISSUE TITLE
ik分词器配置错误

### ISSUE THREAD

**Issue by yqguodataman** [medcl/elasticsearch-analysis-ik#120]
我按照提供的教程进程配置分词器，当我不配置elasticsearch.yml里面的ik内容时，es是不报错的可以使用，当我配置上以后es就一直不停的报错，难道这个版本把里面的配置给去掉了？环境是es2.0.0  ik1.5.0

**Comment by medcl** [comment]
去掉了

**Comment by yqguodataman** [comment]
@medcl 好的谢谢
