### ISSUE TITLE
不可以使用index/_analyze测试?

### ISSUE THREAD

**Issue by childe** [medcl/elasticsearch-analysis-ik#124]
用_search搜索的时候没问题, 但是不能用_analyze测试:

调用 GET index/_analyze?analyzer=ik_max_word&text=中华人民共和国国歌

返回

```
{
   "tokens": [
      {
         "token": "20013",
         "start_offset": 2,
         "end_offset": 7,
         "type": "ARABIC",
         "position": 0
      },
      {
         "token": "21326",
         "start_offset": 10,
         "end_offset": 15,
         "type": "ARABIC",
         "position": 1
      },
      {
         "token": "20154",
         "start_offset": 18,
         "end_offset": 23,
         "type": "ARABIC",
         "position": 2
      },
      {
         "token": "27665",
         "start_offset": 26,
         "end_offset": 31,
         "type": "ARABIC",
         "position": 3
      },
      {
         "token": "20849",
         "start_offset": 34,
         "end_offset": 39,
         "type": "ARABIC",
         "position": 4
      },
      {
         "token": "21644",
         "start_offset": 42,
         "end_offset": 47,
         "type": "ARABIC",
         "position": 5
      },
      {
         "token": "22269",
         "start_offset": 50,
         "end_offset": 55,
         "type": "ARABIC",
         "position": 6
      },
      {
         "token": "22269",
         "start_offset": 58,
         "end_offset": 63,
         "type": "ARABIC",
         "position": 7
      },
      {
         "token": "27468",
         "start_offset": 66,
         "end_offset": 71,
         "type": "ARABIC",
         "position": 8
      }
   ]
}
```

**Comment by medcl** [comment]
es什么版本？
2.1 analyze接口有问题，参见：https://github.com/elastic/elasticsearch/issues/15148

**Comment by childe** [comment]
抱歉回复太晚了!

版本是2.0.0
es的应用log里面没有报错, 只是调用_analyze出来的结果不对.

实际使用(索引和搜索)没有问题, 只是想用_analyze测试一下分词结果的时候, 发现_analyze的结果不正确, 好像是没有使用ik_max_word分词器, 而是用的default分词器.

**Comment by hu985815621** [comment]
我的是es2.1  你们是怎么把分词加到索引里的，我加不进去啊。我照着这个curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'
{
    "fulltext": {
             "_all": {
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "content": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}'
然后  看索引的信息是这样"mappings": {
"fulltext": {
"properties": {
"fulltext": {
"properties": {
"_all": {
"properties": {
"searchAnalyzer": {
"type": "string"
},
"indexAnalyzer": {
"type": "string"
},
"term_vector": {
"type": "string"
},
"store": {
"type": "string"
}
}
},
"properties": {
"properties": {
"content": {
"properties": {
"include_in_all": {
"type": "string"
},
"searchAnalyzer": {
"type": "string"
},
"indexAnalyzer": {
"type": "string"
},
"term_vector": {
"type": "string"
},
"boost": {
"type": "long"
},
"store": {
"type": "string"
},
"type": {
"type": "string"
}
}
}
}
}
}
}
}
}
},
"aliases": [ ]
}

**Comment by hu985815621** [comment]
index/_analyze?analyzer=ik_max_word&text=中华人民共和国国歌。
我这样是可以成功的

**Comment by medcl** [comment]
@hu985815621 你看你的mapping是没有analyzer信息的，说明mapping修改没成功，应该是mapping已经存在且已经有数据了，建议删除重新创建mapping

**Comment by medcl** [comment]
@childe 能复现吗？

**Comment by hu985815621** [comment]
@medcl  Windows下和linux下的命令不一样。弄好了。

**Comment by selfchanger** [comment]
@childe 请问windows下是什么命令呢，我创建mapping时也报错了：
D:\elasticsearch-2.1.0\bin>curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'{"fulltext":{"_all":{"analyzer":"ik_max_word","search_analyzer
":"ik_max_word","term_vector":"no","store":"false"},"properties":{"content":{"type":"string","store":"no","term_vector":"with_positions_offsets","anal
yzer":"ik_max_word","search_analyzer":"ik_max_word","include_in_all":"true","boost":8}}}}'


{"error":{"root_cause":[{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcont
ent bytes"}],"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"},
"status":500}

**Comment by childe** [comment]
@medcl  可以, 随时可以复现. 试了es2.0+ik1.5,  以及es2.1+ik1.6, 都有这个问题.

**Comment by medcl** [comment]
方便贴一下完整curl请求和返回么，我试试

send via my Phone.

**Comment by childe** [comment]
@medcl  就是一楼贴的, 2.0, 2.1都是这样.
按我的理解, 调用GET index/_analyze?analyzer=ik_max_word&text=中华人民共和国国歌, 返回应该是“中华人民共和国,中华人民,中华,华人,人民共和国,人民,人,民,共和国,共和,和,国国,国歌”这样的token, 但是返回了7个单字.

**Comment by medcl** [comment]
@childe 中文使用url方式需要进行urlencode编码，直接是不行的，或者你用POST的analyze，在body里面传值

**Comment by medcl** [comment]
@childe 
curl -XGET http://localhost:9200/_analyze\?analyzer\=ik_max_word\&text\=%e4%b8%ad%e5%8d%8e%e4%ba%ba%e6%b0%91%e5%85%b1%e5%92%8c%e5%9b%bd%e5%9b%bd%e6%ad%8c
{"tokens":[{"token":"中华人民共和国","start_offset":0,"end_offset":7,"type":"CN_WORD","position":0},{"token":"中华人民","start_offset":0,"end_offset":4,"type":"CN_WORD","position":1},{"token":"中华","start_offset":0,"end_offset":2,"type":"CN_WORD","position":2},{"token":"华人","start_offset":1,"end_offset":3,"type":"CN_WORD","position":3},{"token":"人民共和国","start_offset":2,"end_offset":7,"type":"CN_WORD","position":4},{"token":"人民","start_offset":2,"end_offset":4,"type":"CN_WORD","position":5},{"token":"共和国","start_offset":4,"end_offset":7,"type":"CN_WORD","position":6},{"token":"共和","start_offset":4,"end_offset":6,"type":"CN_WORD","position":7},{"token":"国","start_offset":6,"end_offset":7,"type":"CN_CHAR","position":8},{"token":"国歌","start_offset":7,"end_offset":9,"type":"CN_WORD","position":9}]}%

**Comment by childe** [comment]
@medcl  非常非常感谢.
