### ISSUE TITLE
请问如何将ik_max_word设置为default的analyzer？

### ISSUE THREAD

**Issue by oliverhuang** [medcl/elasticsearch-analysis-ik#129]
elasticsearch.yml 里：

`
index :
  analysis :
    analyzer :
      default :
        tokenizer : ik_max_word
`

或者
`
index.analysis.analyzer.default.type: ik_max_word
`

都提示错误：

`
IllegalArgumentException[Unknown Analyzer type [ik_max_word] for [default]]
`

（我用的elasticsearch是2.1.1的，所以我把pom.xml里的elasticsearch版本号改成这个了，应该没影响吧？）

谢谢！

**Comment by iranw** [comment]
add index.analysis.default.type: ik_max_word in your elasticsearch.yml
