### ISSUE TITLE
How to transfer parameter "index name " from ES to IK

### ISSUE THREAD

**Issue by focusme** [medcl/elasticsearch-analysis-ik#130]
Hi, medcl, William Wong said you can help me to resolve my requirement.thank you very much. It is:
  I need post a parameter's data,such as index name or applications' name(set application=app1 in ES' index) to ik plugin for distinction other's application analysis' dictionary.
 
   best regards

**Comment by focusme** [comment]
I hope not modify ES' code.

**Comment by medcl** [comment]
i guess you need a customized dict config based on your index,it is doable feature,
take a look at this line: https://github.com/medcl/elasticsearch-analysis-ik/blob/master/src/main/java/org/elasticsearch/index/analysis/IkAnalyzerProvider.java#L18
as you can see,there is a parameter `index`,you can use this name to load custom dict files,and it is dynamic,no need to modify es's code

hope that help!

**Comment by focusme** [comment]
I can load custom dict files but do not need index name. I need analyzer word segment by index's dict file.
"IKAnalyzerProvider" does not provide index's name to singleton(in https://github.com/medcl/elasticsearch-analysis-ik/blob/master/src/main/java/org/wltea/analyzer/dic/Dictionary.java)

**Comment by focusme** [comment]
I need transfer index's name in line 230,"TransportAnalyzeAction" file (https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java) to ik's plugin.If ik's plugin does not get index'name in this way, the word segment can not analyzer by my customer's dictionary file.

**Comment by focusme** [comment]
in line 238,"TransportAnalyzeAction" file (https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/action/admin/indices/analyze/TransportAnalyzeAction.java):
while (stream.incrementToken()) {
if this sentence like :
while (stream.incrementToken( request.index())) {
this requirement can resolved it.

**Comment by medcl** [comment]
Hey @focusme,we can't pass parameter into Lucene's analysis phrase,you know,in Lucene,there is no concept of index or type,so you can't achieve you goal by doing this,but if you could accept another solution,it is simply that you specify different ik instance with different dict path or with different tokenization algorithm,that's doable.
BTW you can reply in Chinese if you prefer.

**Comment by focusme** [comment]
这确实是很棒的想法。可是我们的业务已经基于ES1.3.6。如果改动，是否要重新设置ES的mapping了呢？
一个方法是修改lucene的底层 。一个方法是重新mapping,如果修改底层，是否引起性能降低。你能帮我选择一种优劣么？谢谢你。
另外，我在你的群里，你曾经给我提供过其他帮助。非常感谢。

**Comment by medcl** [comment]
不用修改修改mapping的，不过需要修改IK的插件，就是我最开始指出的地方，analyzer名字是一样的，但是不同的index都会进入到那个方法里面，你可以在里面处理多个analyzer实例和多词典的处理。
这一行：https://github.com/medcl/elasticsearch-analysis-ik/blob/master/src/main/java/org/elasticsearch/index/analysis/IkAnalyzerProvider.java#L23
比如修改成        analyzer=new IKAnalyzer(useSmart,index.getIndexName());
，然后就可以根据不同的index来构造不同的analyzer了。

**Comment by focusme** [comment]
恩，初步测试是可以的。非常感谢。后面如果再有问题，再请教。非常感谢
