### ISSUE TITLE
创建mapping报错，求解

### ISSUE THREAD

**Issue by selfchanger** [medcl/elasticsearch-analysis-ik#131]
D:\elasticsearch-2.1.0\bin>curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'{"fulltext":{"_all":{"analyzer":"ik_max_word","search_analyzer
":"ik_max_word","term_vector":"no","store":"false"},"properties":{"content":{"type":"string","store":"no","term_vector":"with_positions_offsets","anal
yzer":"ik_max_word","search_analyzer":"ik_max_word","include_in_all":"true","boost":8}}}}'

{"error":{"root_cause":[{"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcont
ent bytes"}],"type":"not_x_content_exception","reason":"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"},
"status":500}

**Comment by medcl** [comment]
windows下把双引号和单引号互换下，或者使用fiddler之类的工具来调试

**Comment by selfchanger** [comment]
@medcl好的，多谢
