### ISSUE TITLE
升级到1.7，已有的mapping怎么处理？

### ISSUE THREAD

**Issue by chinajuanbob** [medcl/elasticsearch-analysis-ik#133]
以前的定义是
curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'
				{
					"fulltext": {
						"_all": {
							"indexAnalyzer": "ik",
							"searchAnalyzer": "ik",
							"term_vector": "no",
							"store": "false"
						},
						"properties": {
							"content": {
								"type": "string",
								"store": "no",
								"term_vector": "with_positions_offsets",
								"indexAnalyzer": "ik",
								"searchAnalyzer": "ik",
								"include_in_all": "true",
								"boost": 8
							}
						}
					}
				}
升级elasticsearch到2.1，ik到1.7后，报错
[2016-01-13 17:20:07,297][WARN ][indices.cluster          ] [Franz Kafka] [[.kibana][0]] marking and sending shard failed due to [failed to create index]
[.kibana] IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [ik]];

配置文件是
index.analysis.analyzer.ik.type: "ik"

应该如何正确升级系统？多谢！

**Comment by medcl** [comment]
去掉配置文件里面的ik的定义就行了

**Comment by chinajuanbob** [comment]
已有mapping需要改动么？

**Comment by medcl** [comment]
你的analyzer名字是什么？如果是自定义的需要修改，type是ik，记住，不要使用以前的class完整路径的方式
