### ISSUE TITLE
对于es集群，是否每个节点都需要安装这个插件？

### ISSUE THREAD

**Issue by leo108** [medcl/elasticsearch-analysis-ik#135]
RT，假如是的话，那如果不同的节点ik的配置不一样（例如用不同的词库）那会发生什么事情？

**Comment by leo108** [comment]
看了下其他相关issue，知道了。

**Comment by goywzl** [comment]
你好，请问现在es集群身份那么多，如：master、node、ingest、client等身份，是只需要在node上和client上安装ik分词，还是每个身份节点都要安装？我没有找到其他相关issue，请问是哪个issue有说明？

**Comment by hustshawn** [comment]
@goywzl 都装

**Comment by goywzl** [comment]
@hustshawn 谢谢
