### ISSUE TITLE
无法将ik设置为默认analyzer

### ISSUE THREAD

**Issue by denghongcai** [medcl/elasticsearch-analysis-ik#139]
```
IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik_smart] for [default]]
```

`ik_smart`改成`ik`也不行
版本是Elasticsearch 2.1.1，以前用1.7.1的时候没碰到过这样的问题，是有什么改动我没注意到吗？
`elasticsearch.yml`里只有一条
```
index.analysis.analyzer.default.type: ik_smart
```

```
root@xxx:/opt/elasticsearch-jdbc-2.1.1.2/bin# /usr/share/elasticsearch/bin/plugin list
Installed plugins in /usr/share/elasticsearch/plugins:
    - elasticsearch-analysis-mmseg-1.7.0
    - elasticsearch-analysis-pinyin-1.5.2
    - elasticsearch-analysis-stconvert-1.6.1
    - elasticsearch-analysis-ik-1.7.0
```

**Comment by medcl** [comment]
这个是es版本的一个bug，你可以通过setting接口来动态设置analyzer

**Comment by denghongcai** [comment]
ok，感谢
看起来是ES初始化时还未加载plugin的问题

**Comment by denghongcai** [comment]
https://github.com/elastic/elasticsearch/issues/16282

并不知道是谁的bug……

**Comment by medcl** [comment]
https://github.com/elastic/elasticsearch/issues/16219 analyze接口的问题

**Comment by denghongcai** [comment]
是elasticsearch服务重启时的问题，新建index的时候报的错

**Comment by botaruibo** [comment]
@denghongcai  我也遇到这个问题，2.1.1 。你解决了吗

**Comment by denghongcai** [comment]
@botaruibo 没有，生产上还是用的1.7.1，等ES那边修好吧

**Comment by botaruibo** [comment]
@denghongcai 我刚改为ik 是可以创建索引了，es bug是_analyze 接口的default 没有设置成功

**Comment by denghongcai** [comment]
@botaruibo 你是用接口改成ik还是在elasticsearch.yml里？

**Comment by botaruibo** [comment]
@denghongcai  用 elasticsearch.yml。 加了引号 “ik”。 不加引号还没试。接口的我不确定现在的还work不。我看2.2的change里讲 好些level的analyzer 参数都 remove了https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_mapping_changes.html#_analyzer_mappings

**Comment by tad2021** [comment]
@botaruibo 你是master自行编译的还是2.2.0？

**Comment by tad2021** [comment]
@medcl _analyze时指定ik是可以用的，使用_setting（先_close，再_setting，后_open）重建索引时还是报IndexCreationException，新建索引指定分词器为ik时，还是报Unknown Analyzer type [ik]。

**Comment by tad2021** [comment]
"mappings": {
    "x":{
      "properties": {
        "y":{
          "type": "string",
          "analyzer": "ik"
        }
      }
    }
  }
使用mapping就不会报IndexCreationException。

**Comment by botaruibo** [comment]
@tad2021 我是用的2.1的binary jar

**Comment by xmudall** [comment]
2.2.0 新建index时设置default analyzer报同样的错误，有什么办法设置default analyzer 吗？

另外，不觉得是es的bug，用其他分词器并没有这个问题，比如smartcn

**Comment by medcl** [comment]
@xmudall 你确定用smartcn是好的？

**Comment by medcl** [comment]
@xmudall 我查一下先

**Comment by medcl** [comment]
已经fix，b344f2e
好吧，我承认我之前删掉了一个方法

**Comment by xmudall** [comment]
赞赞～～

**Comment by xmudall** [comment]
@medcl 
我试了一下，似乎还有问题。
现在添加template的时候不会报错了，但是在添加复合template的index的时候还是报错，过程如下：

添加template
POST /_template/test
{
    "order": 1,
    "template": "test-*",
    "settings": {
      "index": {
        "analysis": {
          "analyzer": {
            "default": {
              "type": "ik_smart"
            }
          }
        }
      }
    }
}

添加名为test-1的index
PUT /test-1

错误信息：
{
  "error": {
    "root_cause": [
      {
        "type": "remote_transport_exception",
        "reason": "[node-2][192.168.2.128:9300][indices:admin/create]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Unknown Analyzer type [ik_smart] for [default]"
  },
  "status": 400
}

**Comment by medcl** [comment]
@xmudall 默认配置只支持类型 `ik`

**Comment by xmudall** [comment]
@medcl 确实，用ik就好了，非常感谢

**Comment by Morriaty-The-Murderer** [comment]
@xmudall 
你现在yml中的配置是这样吗
```
index.analysis.analyzer.default.type : ik
```
同样是es 2.2.0，设置成`smartcn`就没问题，设置成`ik`和`ik_max_word`就都不行
```
IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]];
```

**Comment by xmudall** [comment]
现在没问题，已经fix了，见前面Medcl的回复

另外我是在template里配的，不过应该是一样的

On Fri, Apr 8, 2016 at 7:03 PM, Morriaty-The-Murderer <
notifications@github.com> wrote:

> @xmudall <https://github.com/xmudall>
> 你现在yml中的配置是这样吗
>
> index.analysis.analyzer.default.type : ik
>
> 同样是es 2.2.0，设置成smartcn就没问题，设置成ik和ik_max_word就都不行
>
> IndexCreationException[failed to create index]; nested: IllegalArgumentException[Unknown Analyzer type [ik] for [default]];
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/medcl/elasticsearch-analysis-ik/issues/139#issuecomment-207378407>
>



-- 

    祝
好

胡游乐
清华大学软件学院
xmudall@gmail.com

**Comment by Morriaty-The-Murderer** [comment]
@xmudall 我上面的配置  不行啊............

**Comment by Morriaty-The-Murderer** [comment]
@xmudall 改成你上面的template也不行
@medcl 请问是我的ik安装错误吗
```
[es@sjBI143 bin]$ ll ../plugins/ik/
total 1444
-rw-rw-r-- 1 es es 263965 Apr  8 17:42 commons-codec-1.9.jar
-rw-rw-r-- 1 es es  61829 Apr  8 17:42 commons-logging-1.2.jar
drwxrwxr-x 3 es es   4096 Feb 21 01:20 config
-rw-rw-r-- 1 es es  68655 Apr  8 18:22 elasticsearch-analysis-ik-1.8.0.jar
-rw-rw-r-- 1 es es 720931 Apr  8 17:42 httpclient-4.4.1.jar
-rw-rw-r-- 1 es es 322234 Apr  8 17:42 httpcore-4.4.1.jar
-rw-rw-r-- 1 es es   2680 Apr  8 18:22 plugin-descriptor.properties
[es@sjBI143 bin]$ 
```

**Comment by medcl** [comment]
@Morriaty-The-Murderer 请提供具体操作过程和错误信息

**Comment by Morriaty-The-Murderer** [comment]
@medcl template的问题解决，是以前的老的template没有删除
但是yml里default设置成ik还是不行，设置成smartcn就没有这个问题，/_analyze接口也没问题

**Comment by xmudall** [comment]
你用的分支的问题吧，1.8.0的tag还没有修复上面那个问题，你要自己把@medcl的修改merge过去

On Mon, Apr 11, 2016 at 11:58 AM, Morriaty-The-Murderer <
notifications@github.com> wrote:

> @medcl <https://github.com/medcl> template的问题解决，是以前的老的template没有删除
> 但是yml里default设置成ik还是不行，设置成smartcn就没有这个问题，/_analyze接口也没问题
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/medcl/elasticsearch-analysis-ik/issues/139#issuecomment-208151751>
>



-- 

    祝
好

胡游乐
清华大学软件学院
xmudall@gmail.com

**Comment by lbitee** [comment]
@medcl 你好，我还是遇到了类似问题。es2.3.3+elasticsearch-analysis-ik-1.9.4。
我看到您在上边说：默认配置只支持类型 ik，请问想使用ik-smart，应在es中作何设置？

**Comment by medcl** [comment]
`
index.analysis.analyzer.default.use_smart: true
index.analysis.analyzer.default.type: ik
`
es 后面的版本已经不支持设置节点层面的默认分词了，还是尽量在索引层面动态设置吧
