### ISSUE TITLE
ik分词器为什么不能把猫，狗这样的单个词分出来呢

### ISSUE THREAD

**Issue by chengyuanheng** [medcl/elasticsearch-analysis-ik#142]
比如我现在分词：我家猫叫小明
ik分词器会分成：我家。家猫。家。猫叫。小明。
而我想让它把 猫 这个词分出来 
还有类似 狗狗 这样的词
怎么把狗 这个词分出来呢
求大神啊

**Comment by hanwujibaby** [comment]
你要把狗单独作为一个字典吧。

2016-01-25 20:22 GMT+08:00 cc <notifications@github.com>:

> 比如我现在分词：我家猫叫小明
> ik分词器会分成：我家。家猫。家。猫叫。小明。
> 而我想让它把 猫 这个词分出来
> 还有类似 狗狗 这样的词
> 怎么把狗 这个词分出来呢
> 求大神啊
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medcl/elasticsearch-analysis-ik/issues/142>.
>



-- 
from wei4liverpool's gmail

**Comment by chengyuanheng** [comment]
对呀， 因为现在别人搜 狗 就搜不出来东西啊

**Comment by medcl** [comment]
在词典把你需要的单字加上吧

**Comment by chengyuanheng** [comment]
字典里面加上是没有问题的，但是考虑如果以后遇到这样的词都要加的话，工作量会很大呀，就没有其他的办法了吗？

**Comment by medcl** [comment]
看你的需要了，不分成一个个的词是为了减少索引大小，你如果要全部分成单字，那直接用standard分词就行

**Comment by medcl** [comment]
同 #117
