### ISSUE TITLE
ik为什么不支持es1.3.x版本了

### ISSUE THREAD

**Issue by zcgewu** [medcl/elasticsearch-analysis-ik#143]
最近学习es时，想到spring data，不想版本支持的比低，当时也没多想。（不知道1.3.x版本是不是不好）
Spring data elaticsearch until 1.0.0.RELEASE version is on elasticsearch 1.1.x library, which uses java 1.6 or later version.From spring data elastic search 1.1.0.RELEASE (current) on, the version of elasticsearch 1.3.x is supporting java 1.7 or later.

**Comment by medcl** [comment]
如果刚开始学习，我建议你直接使用最新版本的es，也就是2.0之后的版本
