### ISSUE TITLE
ES用的2.2.0,ik应该用哪个版本？

### ISSUE THREAD

**Issue by zhongying90** [medcl/elasticsearch-analysis-ik#153]
启动的时候出现这个错误
`Plugin [elasticsearch-analysis-ik] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]`

**Comment by wx7614140** [comment]
用最新的就好啊，我记得支持2.2.0了

**Comment by zhongying90** [comment]
我下的最新的1.7.0,不支持ES2.2.0 @wx7614140

**Comment by SakuraZhang** [comment]
不支持2.1.1 + 的

**Comment by medcl** [comment]
fixed 099b1f2
