### ISSUE TITLE
无法直接通过plugin install安装

### ISSUE THREAD

**Issue by ideazxy** [medcl/elasticsearch-analysis-ik#155]
我在elasticsearch官方的2.1.1的docker镜像中测试：

root@7b184685d6b1:/# elasticsearch -version
Version: 2.1.1, Build: 40e2c53/2015-12-15T13:05:55Z, JVM: 1.8.0_66-internal
root@7b184685d6b1:/# plugin install medcl/elasticsearch-analysis-ik/v1.7.0
-> Installing medcl/elasticsearch-analysis-ik/v1.7.0...
Trying https://download.elastic.co/medcl/elasticsearch-analysis-ik/elasticsearch-analysis-ik-v1.7.0.zip ...
Trying https://search.maven.org/remotecontent?filepath=medcl/elasticsearch-analysis-ik/v1.7.0/elasticsearch-analysis-ik-v1.7.0.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/medcl/elasticsearch-analysis-ik/v1.7.0/elasticsearch-analysis-ik-v1.7.0.zip ...
Trying https://github.com/medcl/elasticsearch-analysis-ik/archive/v1.7.0.zip ...
Downloading .........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://github.com/medcl/elasticsearch-analysis-ik/archive/v1.7.0.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by medcl** [comment]
不支持plugin install方式来安装。

**Comment by li0803** [comment]
没有这个plugin-descriptor.properties都没法通过plugin命令来安装
