### ISSUE TITLE
es1.4版本用的ik1.2.9从哪里下载？

### ISSUE THREAD

**Issue by wuxiaoyi** [medcl/elasticsearch-analysis-ik#156]
公司使用的es1.4，但是在github上找不到ik1.2.9了？
@medcl 请问ik1.2.9版本可以从哪下载？或者可否使用其他某个版本？

**Comment by medcl** [comment]
可以使用https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.3.0 然后修改pom.xml里面的es版本号，打包就可以了
