### ISSUE TITLE
编辑了最新1.8版本

### ISSUE THREAD

**Issue by sixinyiyu** [medcl/elasticsearch-analysis-ik#159]
成功编辑了1.8版本，在es2.2.0版本上安装成功启动无异常，但是创建索引时Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]

**Comment by jaohaohsuan** [comment]
我也遇到相同的问题

**Comment by medcl** [comment]
可以把问题复现过程发一下么？是不是使用了旧的elasticsearch.yml文件，请参照README的安装说明

**Comment by jaohaohsuan** [comment]
谢谢 @medcl 的提示，我把`config/elasticsearch.yml`里面的
> ~~index.analysis.analyzer.ik.type : "ik"~~

去掉就好了
