### ISSUE TITLE
Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]???

### ISSUE THREAD

**Issue by wyp315360007** [medcl/elasticsearch-analysis-ik#161]
/etc/elasticsearch/elasticsearch.yml
-------
index:
    analysis:
        analyzer:
            ik:
                alias: [ik_analyzer]
                type: org.elasticsearch.index.analysis.IkAnalyzerProvider  
            ik_max_word:
                type: ik
                use_smart: false
            ik_smart:
                type: ik
                use_smart: true
----------
PUT /shoespie_website
{
    "settings" : {
        "analysis" : {
            "analyzer" : {
                "stem" : {
                    "tokenizer" : "standard",
                    "filter" : ["standard", "lowercase", "stop", "porter_stem"]
                }
            }
        }
    },
   "mappings" : {
        "MongoDBSpuItemModel" : {
            "dynamic" : true,
            "properties" : {
                "intro" : {
                    "type" : "string",
                    "indexAnalyzer" : "ik",
                    "searchAnalyzer":"ik"
                }
            }
        }
    }
}
----------------
{
   "error": {
      "root_cause": [
         {
            "type": "index_creation_exception",
            "reason": "failed to create index"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]"
   },
   "status": 400
}

**Comment by medcl** [comment]
type: org.elasticsearch.index.analysis.IkAnalyzerProvider
这种配置方式已不支持
