### ISSUE TITLE
How custom IK Analysis Configuration ？(elasticsearch.yml)

### ISSUE THREAD

**Issue by wyp315360007** [medcl/elasticsearch-analysis-ik#162]
Mmseg‘s example：
index:
  analysis: 
    analyzer:
      mmseg_maxword:
        type: custom
        filter:
        - lowercase
        tokenizer: mmseg_maxword
      mmseg_maxword_with_cut_letter_digi:
        type: custom
        filter:
        - lowercase
        - cut_letter_digit
        tokenizer: mmseg_maxword  
how ik config with elasticsearch.yml,please?

**Comment by medcl** [comment]
Analyzer: ik_smart , ik_max_word , Tokenizer: ik_smart , ik_max_word

**Comment by medcl** [comment]
are you already fixed this issue?
