### ISSUE TITLE
elasticsearch-analysis-ik 1.7.0的config拷贝到哪里？

### ISSUE THREAD

**Issue by sshling** [medcl/elasticsearch-analysis-ik#167]
文档中说明：
`
2.config files:
download the dict files,unzip these dict file into your elasticsearch's config folder,such as: your-es-root/config/ik
`
部署时，plugin目录单独指定的，不是使用默认的，ik插件包中的config是一定要拷贝到ES服务器下的config目录吗？测试貌似config放在ik下也可以。

**Comment by medcl** [comment]
1.7 config目录已经移动到插件相对目录了，所以跟着插件走就行了。
