### ISSUE TITLE
elasticsearch.yml这里面怎么配置啊

### ISSUE THREAD

**Issue by zwkmdj** [medcl/elasticsearch-analysis-ik#170]
elasticsearch.yml这里面怎么配置啊
以前我下面的配置，这个版本的不行
index:
  analysis:
    analyzer:
      ik:
          alias: [news_analyzer_ik,ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
          
index.analysis.analyzer.default.type : "ik"

**Comment by medcl** [comment]
不用配置了，
两个Analyzer: ik_smart , ik_max_word , 
和两个：Tokenizer: ik_smart , ik_max_word
默认配置es目前不支持
