### ISSUE TITLE
path.conf setting ignored

### ISSUE THREAD

**Issue by simonseed** [medcl/elasticsearch-analysis-ik#172]
https://www.elastic.co/guide/en/elasticsearch/reference/2.2/breaking_20_setting_changes.html#_custom_config_file

The es plugin install script will follow the path.conf setting and install config in to a customised location. 

But the analysis-ik plugin ignores this setting and assumes the config is installed in a directory inside plugin source location. 

So when using a custom config location the plugin fails. The work around is to symlink the config. But I think the plugin should read the config file location from properties.

Thanks

**Comment by medcl** [comment]
already in master
