### ISSUE TITLE
Cannot get special version

### ISSUE THREAD

**Issue by zhupengGitHub** [medcl/elasticsearch-analysis-ik#175]
git clone https://github.com/medcl/elasticsearch-analysis-ik
cd elasticsearch-analysis-ik
mvn clean
mvn compile
mvn package

I use the step to get zip,but it get elasticsearch-analysis-ik-1.9.0.zip,how can I get elasticsearch-analysis-ik-1.8.1.zip?

**Comment by JohnTian** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases
