### ISSUE TITLE
Garbled words

### ISSUE THREAD

**Issue by szhupeng** [medcl/elasticsearch-analysis-ik#176]
curl -XPOST 'http://localhost:9200/profile/_analyze?analyzer=standard&pretty=true&text=我爱我家'
{
  "tokens" : [ {
    "token" : "ﾈﾑ",
    "start_offset" : 1,
    "end_offset" : 3,
    "type" : "<KATAKANA>",
    "position" : 0
  }, {
    "token" : "ﾈ",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "<KATAKANA>",
    "position" : 1
  }, {
    "token" : "ﾱ",
    "start_offset" : 5,
    "end_offset" : 6,
    "type" : "<HANGUL>",
    "position" : 2
  }, {
    "token" : "ﾈﾑ",
    "start_offset" : 7,
    "end_offset" : 9,
    "type" : "<KATAKANA>",
    "position" : 3
  }, {
    "token" : "ﾮﾶ",
    "start_offset" : 10,
    "end_offset" : 12,
    "type" : "<HANGUL>",
    "position" : 4
  } ]
}

**Comment by medcl** [comment]
我爱我家 需要 urlencode 先
