### ISSUE TITLE
中英文不分词的情况怎么处理？

### ISSUE THREAD

**Issue by SIvaCoHan** [medcl/elasticsearch-analysis-ik#178]
如 “HR总监” 这是一个标准职位名称。我们不希望这个被分词。

**Comment by JohnTian** [comment]
构建Type的时候，"name": {"index": "not_analyzed", "type": "string"}

**Comment by SIvaCoHan** [comment]
谢谢

**Comment by wallyhung** [comment]
不分词的中英文怎么用query_string 查询呢
