### ISSUE TITLE
创建mapping，发生【mapper_parsing_exception】

### ISSUE THREAD

**Issue by henryfeng811** [medcl/elasticsearch-analysis-ik#180]
我现在使用elasticsearch-2.3.0，增加了 elasticsearch-analysis-ik 1.9。
在创建mapping的时候（详细如下），发生了【mapper_parsing_exception】异常。怎么解决？

curl -XPOST http://localhost:9200/index/fulltext/_mapping -d'
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "analyzer on field [content] must be set when search_analyzer is set"
}
],
"type": "mapper_parsing_exception",
"reason": "analyzer on field [content] must be set when search_analyzer is set"
},
"status": 400
}
返回：
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "analyzer on field [content] must be set when search_analyzer is set"
}
],
"type": "mapper_parsing_exception",
"reason": "analyzer on field [content] must be set when search_analyzer is set"
},
"status": 400
}

**Comment by medcl** [comment]
mapping贴错了吧，另外看提示就知道，你需要设置`analyzer`这个参数

**Comment by henryfeng811** [comment]
菜鸟一枚，对里面的提交的内容不太清楚。问题已解决，谢谢！

**Comment by luozehua** [comment]
请问楼主是怎么解决的？我下载IK1.5，按照readme.md中步骤安装，创建mapping的时候也报这个错?
{
    "fulltext": {
             "_all": {
            "indexAnalyzer": "ik_max_word",
            "searchAnalyzer": "ik_max_word",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "content": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "indexAnalyzer": "ik_max_word",
                "searchAnalyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}
