### ISSUE TITLE
新版本不支持在config.yaml里添加全局默认analyzer了么?

### ISSUE THREAD

**Issue by jinleileiking** [medcl/elasticsearch-analysis-ik#181]

**Comment by jinleileiking** [comment]
#index.analysis.analyzer.ik.type : "ik"
#index.analysis.analyzer.default.type : "ik"

**Comment by medcl** [comment]
支持

**Comment by jinleileiking** [comment]
@medcl 求给个说明,多谢

**Comment by medcl** [comment]
`index.analysis.analyzer.default.type: ik`

**Comment by jinleileiking** [comment]
这个在最新的好像不好使.
```
elasticsearch:2.2.0
ik:1.8.0
```

我的配置是这样的:
```
index.analysis.analyzer.default.tokenizer : "ik_max_word"
```

**Comment by jinleileiking** [comment]
`index.analysis.analyzer.default.type: ik` 报错

**Comment by jinleileiking** [comment]
说找不到ik

**Comment by medcl** [comment]
请使用最新的1.9.1，之前的版本不行

**Comment by jinleileiking** [comment]
我是按照version表来的 -_-# :(
我试试

**Comment by jinleileiking** [comment]
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-ik] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.3.1]

**Comment by jinleileiking** [comment]
用这个功能必须231 ? 又要升级了....

**Comment by hyh012356789** [comment]
windows下报下面错误怎么解决：
[2016-05-29 22:02:44,739][ERROR][bootstrap                ] Guice Exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "E:\ES%20study\elasticsearch-2.3.3\plugins\ik\config\IKAnalyzer.cfg.xml" "read")

**Comment by jinleileiking** [comment]
@hyh012356789 ... 目录别有空格啊...

**Comment by medcl** [comment]
5.0以后不支持node级别的默认分词设置了
`The index.analysis.analyzer.default_index analyzer is not supported anymore. If you wish to change the analyzer to use for indexing, change the index.analysis.analyzer.default analyzer instead.`

https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_settings_changes.html#_index_level_settings
