### ISSUE TITLE
同义词在查询中不起作用

### ISSUE THREAD

**Issue by mdifferent** [medcl/elasticsearch-analysis-ik#182]
请大神帮忙看一下这个问题：我在查询时候无法返回同义词查询的结果，ES版本是2.2.1
1. yml里这样定义analyzer:
   `index:
   analysis:
     analyzer:
       ik_syno:
           type: custom
           tokenizer: ik_max_word
           filter: [my_synonym_filter]
       ik_syno_smart:
           type: custom
           tokenizer: ik_smart
           filter: [my_synonym_filter]
     filter:
       my_synonym_filter:
           type: synonym
           synonyms_path: analysis/synonym.txt`
2. 同义词是这么定义的，文件是UTF-8编码：
   番茄,西红柿
   白薯,地瓜,红薯
3. 然后建立index:
   `PUT items2
   {
   "itemNames":{
     "_all": {
       "enabled": "false"
     },
     "properties": {
         "name": { 
           "type": "string",
           "index": "analyzed",
           "analyzer": "ik_syno_smart",
           "search_analyzer": "ik_syno_smart",
           "index_analyzer":"ik_syno_smart"
         }
       }
   }
   }`
4. 测试同义词可以通过：
   `POST items2/_analyze?analyzer=ik_syno_smart
   {
   "text": "番茄"
   }`

`{
  "tokens": [
    {
      "token": "番茄",
      "start_offset": 0,
      "end_offset": 2,
      "type": "CN_WORD",
      "position": 0
    },
    {
      "token": "西红柿",
      "start_offset": 0,
      "end_offset": 2,
      "type": "SYNONYM",
      "position": 0
    }
  ]
}`

但是无论用query_string还是match都无法查询到结果：
`POST items2/itemName/_search
{
  "query": {
    "query_string": {
      "default_field": "name",
      "query": "番茄",
      "analyzer": "ik_syno_smart"
    }
  }
}`

`POST items2/itemName/_search
{
  "query": {
    "match": {
      "name": {
        "query": "番茄",
        "analyzer": "ik_syno_smart"
      }
    }
  }
}`

`{
  "took": 5,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 0,
    "max_score": null,
    "hits": []
  }
}`

这问题困扰我好几天了，请帮忙看一下，多谢~

**Comment by JohnTian** [comment]
ES 2.3.1 

## 同义词配置

### step 1

`elasticserach.yml` 最后一行添加：
`index.analysis.analyzer.default.type: ik`

### step 2

在`elasticsearch-2.3.1/config`目录下面，存放`synonyms.txt`

其中，synonyms.txt 编码格式为'utf-8'，内容为：

    #Example:
    ipod, i-pod, i pod
    foozball , foosball
    universe , cosmos
    西红柿, 番茄
    马铃薯, 土豆
    aa, bb

### step 3

新建立索引类型设置
```
curl -XPUT localhost:9200/test/_mapping?pretty -d '
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "jt_cn": {
            "type": "custom",
            "use_smart": "true",
            "tokenizer": "ik_smart",
            "filter": ["jt_tfr","jt_sfr"],
            "char_filter": ["jt_cfr"]
          },
          "ik_smart": {
            "type": "ik",
            "use_smart": "true"
          },
          "ik_max_word": {
            "type": "ik",
            "use_smart": "false"
          }
        },
        "filter": {
          "jt_tfr": {
            "type": "stop",
            "stopwords": [" "]
          },
          "jt_sfr": {
            "type": "synoym",
            "synonyms_path": "synonyms.txt"
          }
        },
        "char_filter": {
            "jt_cfr": {
                "type": "mapping",
                "mappings": [
                    "| => \\|"
                ]
            }
        }
      }
    }
  },
  "mappings": {
    "solution": {
      "properties": {
        "title": {
          "include_in_all": true,
          "analyzer": "jt_cn",
          "term_vector": "with_positions_offsets",
          "boost": 8,
          "store": true,
          "type": "string"
        }
      }
    }
  }
}
'
```


### step 4

    curl -XPUT localhost:9200/test/solution/1 -d '
    {
        "title": "番茄"
    }
    '
    curl -XPUT localhost:9200/test/solution/2 -d '
    {
        "title": "西红柿"
    }
    '


### step 5

    curl -XPOST 'localhost:9200/test/solution/_search?pretty' -d '
    {
      "query": {
        "query_string": {
          "title": {
            "query": "西红柿",
            "analyzer": "jt_cn"
          }
        }
      },
      "highlight": {
        "pre_tags": [
          "<tag1>",
          "<tag2>"
        ],
        "post_tags": [
          "</tag1>",
          "</tag2>"
        ],
        "fields": {
          "title": {}
        }
      }
    }
    '

结果：

    {
      "took": 3,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 2,
        "max_score": 0.4500804,
        "hits": [
          {
            "_index": "test",
            "_type": "solution",
            "_id": "1",
            "_score": 0.4500804,
            "_source": {
              "title": "西红柿"
            }
          },
          {
            "_index": "test",
            "_type": "solution",
            "_id": "2",
            "_score": 0.36006433,
            "_source": {
              "title": "番茄"
            }
          }
        ]
      }
    }

**Comment by nathan-zhu** [comment]
问个自定义分词和同类词的问题。
文字和数字的自定一次如何设置，我在 mydict.dic 里添加了如下
```
玛莎拉蒂
宝马5系530Li
宝马5系
宝马X6
```

宝马5系530Li和宝马X1这种带数字和汉字的都被拆分开了
```
{
  "analyzer": "ik",
  "text": "宝马5系530LI和宝马X6"
}
```
分词结果如下
```
"tokens": [
    {
    "token": "宝马5系",
    "start_offset": 0,
    "end_offset": 4,
    "type": "CN_WORD",
    "position": 0
    },
    {
    "token": "宝马",
    "start_offset": 0,
    "end_offset": 2,
    "type": "CN_WORD",
    "position": 1
    },
    {
    "token": "5",
    "start_offset": 2,
    "end_offset": 3,
    "type": "ARABIC",
    "position": 2
    },
    {
    "token": "系",
    "start_offset": 3,
    "end_offset": 4,
    "type": "CN_CHAR",
    "position": 3
    },
    {
    "token": "530li",
    "start_offset": 4,
    "end_offset": 9,
    "type": "LETTER",
    "position": 4
    },
    {
    "token": "530",
    "start_offset": 4,
    "end_offset": 7,
    "type": "ARABIC",
    "position": 5
    },
    {
    "token": "li",
    "start_offset": 7,
    "end_offset": 9,
    "type": "ENGLISH",
    "position": 6
    },
    {
    "token": "和",
    "start_offset": 9,
    "end_offset": 10,
    "type": "CN_CHAR",
    "position": 7
    },
    {
    "token": "宝马",
    "start_offset": 10,
    "end_offset": 12,
    "type": "CN_WORD",
    "position": 8
    },
    {
    "token": "x6",
    "start_offset": 12,
    "end_offset": 14,
    "type": "LETTER",
    "position": 9
    },
    {
    "token": "x",
    "start_offset": 12,
    "end_offset": 13,
    "type": "ENGLISH",
    "position": 10
    },
    {
    "token": "6",
    "start_offset": 13,
    "end_offset": 14,
    "type": "ARABIC",
    "position": 11
    }
]
```
请问这种的应该如何处理这种自定义带数字的分词？多谢

**Comment by nathan-zhu** [comment]
@JohnTian 我也想测试同义词，按照你的方法在step 3时报错了

```
{
"error": {
"root_cause": [
{
"type": "mapper_parsing_exception",
"reason": "Root mapping definition has unsupported parameters: [settings : {index={analysis={analyzer={jt_cn={type=custom, use_smart=true, tokenizer=ik_smart, filter=[jt_tfr, jt_sfr], char_filter=[jt_cfr]}, ik_smart={type=ik, use_smart=true}, ik_max_word={type=ik, use_smart=false}}, filter={jt_tfr={type=stop, stopwords=[ ]}, jt_sfr={type=synonym, synonyms_path=synonyms.txt}}, char_filter={jt_cfr={type=mapping, mappings=[| => \|]}}}}}] [mappings : {solution={properties={title={include_in_all=true, analyzer=jt_cn, term_vector=with_positions_offsets, boost=8, store=true, type=string}}}}]"
}
],
"type": "mapper_parsing_exception",
"reason": "Root mapping definition has unsupported parameters: [settings : {index={analysis={analyzer={jt_cn={type=custom, use_smart=true, tokenizer=ik_smart, filter=[jt_tfr, jt_sfr], char_filter=[jt_cfr]}, ik_smart={type=ik, use_smart=true}, ik_max_word={type=ik, use_smart=false}}, filter={jt_tfr={type=stop, stopwords=[ ]}, jt_sfr={type=synonym, synonyms_path=synonyms.txt}}, char_filter={jt_cfr={type=mapping, mappings=[| => \|]}}}}}] [mappings : {solution={properties={title={include_in_all=true, analyzer=jt_cn, term_vector=with_positions_offsets, boost=8, store=true, type=string}}}}]"
},
"status": 400
}
```
没找到那里出错，请指教。多谢。

**Comment by xiafei571** [comment]
你配置文件配置了自定义的tokenizer，需要定义一下tokenizer， 如：
ik_syno:
          type: custom
          filter: [my_synonym_filter]
          tokenizer: my_max_word
      ik_syno_smart:
          type: custom
          filter: [my_synonym_filter]
          tokenizer: my_smart
    filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: analysis/synonym.txt
    tokenizer:
      my_max_word:
          type: ik
          use_smart: false
      my_smart:
          type: ik
          use_smart: true

**Comment by JohnTian** [comment]
@nathan-zhu 您好，我当时只测试了2.3.1版本的，没有测试其他版本是否合适。不过，从错误提示“"mapper_parsing_exception”来看，应该是您自己map的时候出现了一些问题。

**Comment by nathan-zhu** [comment]
@JohnTian @xiafei571 感谢大家的答复，这是我的配置，我用的默认Tokenizer: ik_smart , ik_max_word来定义的

```
index.analysis.analyzer.ik.type: ik
index:
  analysis:
    analyzer:
        ik_syno:
            type: custom
            tokenizer: ik_max_word
            filter: [my_synonym_filter]
        ik_syno_smart:
            type: custom
            tokenizer: ik_smart
            filter: [my_synonym_filter]
        filter:
          my_synonym_filter:
              type: synonym
              synonyms_path: synonyms.txt
```
1. 有个问题我之前建立索引没有加以上配置，现在添加了这种配置以后重启服务，会影响到老的索引分片吗？昨天测试后老的索引文档都失效了呢。请问这应该如何处理？
2. 文字加数字的固定分词如何定义？ 比如"宝马5系530Li"如何让它不被拆分，能作为一个特殊词搜索到？

十分感谢。

**Comment by xiafei571** [comment]
感谢您的回复，已经解决，
1.4.2版本
index:
  analysis:
    analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_syno:
          type: custom
          filter: [my_synonym_filter]
          tokenizer: my_max_word
      ik_syno_smart:
          type: custom
          filter: [my_synonym_filter]
          tokenizer: my_smart
    filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: analysis/synonym.txt
    tokenizer:
      my_max_word:
          type: ik
          use_smart: false
      my_smart:
          type: ik
          use_smart: true

**Comment by JohnTian** [comment]
@nathan-zhu 
1. 这个好像只能重新索引数据。当然，你可以试试动态map模板。
2. 可以在自定义分析器内部添加char_filter，具体操作看官网的配置。如果，还是不行的话，只好修改源码中的停止词设置。Good Luck~!

**Comment by nathan-zhu** [comment]
@JohnTian 好的多谢，我研究看下。

**Comment by nathan-zhu** [comment]
@JohnTian 再问个问题，在elasticsearch.yml配置文件里不能写自定义analyzer？
```
index:
  analysis:
    analyzer:
      ik_syno:
          type: custom
          tokenizer: ik_max_word
          filter: [my_synonym_filter]
      ik_syno_smart:
          type: custom
          tokenizer: ik_smart
          filter: [my_synonym_filter]
    filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: synonyms.txt
```
然后启动测试自定义的 ik_syno 提示找不到
```
"type": "illegal_argument_exception",
"reason": "failed to find analyzer [ik_syno]"
```
2.0 版本后不支持了在配置里写吗？只能写在 mapping 的 settings里才生效？

**Comment by medcl** [comment]
@nathan-zhu 配置支持配置文件的，你查看下yaml语法，tab与空格之类的问题
