### ISSUE TITLE
ElasticSearch 2.3.2 版本不兼容

### ISSUE THREAD

**Issue by holmescn** [medcl/elasticsearch-analysis-ik#186]
今天尝试装ik的时候，发现ElasticSearch的版本还是2.2.1，然后upgrade了一下，就变成 2.3.2了，我直接pull了master分支，结果都不兼容。ES的插件如何兼容呢？是不是可以有一组测试，来验证是不是兼容或者在FAQ里加入如何修改以实现兼容？我想小版本的更新，应该API的变动不会太大。

**Comment by medcl** [comment]
fixed  cd9dfdf
