### ISSUE TITLE
为什么ik不能通过./plugin install medcl/elasticsearch-analysis-ik 这样的方式安装？

### ISSUE THREAD

**Issue by Folyd** [medcl/elasticsearch-analysis-ik#189]
![qq20160504-0](https://cloud.githubusercontent.com/assets/3369694/15009049/d21acd9e-1216-11e6-9902-1a1e44756411.png)

原来是ik里面并没有配备`plugin-descriptor.properties` 这个文件，难道必须要手动`git clone` `mvn clean compile package `? 并不是新机子都会装git 和 maven的，希望能支持官方推荐的那种方式安装，给开发者带来便利。

万分感谢啊

**Comment by medcl** [comment]
下载地址：https://github.com/medcl/elasticsearch-analysis-ik/releases

**Comment by Folyd** [comment]
好吧，谢谢，最后还是希望能够采纳 😃

**Comment by medcl** [comment]
@Folyd 目前社区的插件还不能直接以这种方式安装，回头支持了一定加上的

**Comment by Folyd** [comment]
为什么 head插件能够通过这种方式安装呢？https://github.com/mobz/elasticsearch-head

**Comment by ZoozyCN** [comment]
+1

**Comment by a121984376** [comment]
这个properties 可坑苦了我..作为一个非java的开发者,教程都是 1.X.X的~自己下了个新的2.3.3 plugin都是有properties 这个玩应~~~

**Comment by medcl** [comment]
release里面的压缩包都是有这个配置文件的拉

**Comment by medcl** [comment]
从es2.3.5开始支持plugin安装：
`./bin/plugin install org.elasticsearch/elasticsearch-analysis-ik/1.9.5`

**Comment by xiangyu123** [comment]
您好，请问下2.3.4 是否支持 ./bin/plugin install org.elasticsearch/elasticsearch-analysis-ik/1.9.4，另外2.3.4是否兼容最新版？ 这种安装方式？另外，我所有的机器的环境都一样，如果我在其中一台机器上安装git mvn 编译好，我是否可以直接把最终编译后的包拷贝到其他的机器上直接使用(其他机器不安装git  mvn)， 我这一个集群有82台机器，要一台台编译太痛苦了。我是非java开发，谢谢 ！！
