### ISSUE TITLE
关于中文全文检索的问题

### ISSUE THREAD

**Issue by levylll** [medcl/elasticsearch-analysis-ik#195]
你好，我这边输入的是一个词语“索菲特”
我的es库里的是有字段包含索菲特的
但是检索的时候，match的type如果指定为phrase就检索不到
              {
                "value": 0,
                "description": "no match on required clause ((area_name:\"索 菲 特\"^5.0 | pinyin:\"suofeite suo feite fei te\" | product_short_name:\"索菲特 索 菲特 菲 特\"^2.0 | key_words:\"索菲特 索 菲特 菲 特\"^4.0 | product_name:\"索菲特 索 菲特 菲 特\"^3.0))",
                "details": [
                  {
                    "value": 0,
                    "description": "No matching clause",
                    "details": []
                  }
                ]
              }
如果不特别指定match的type就可以搜到了
{
                "value": 1.4249796,
                "description": "product of:",
                "details": [
                  {
                    "value": 1.7812245,
                    "description": "sum of:",
                    "details": [
                      {
                        "value": 0.54060966,
                        "description": "weight(product_short_name:索菲特 in 2937) [PerFieldSimilarity], result of:",
                        "details": [
                          {
                            "value": 0.54060966,
                            "description": "score(doc=2937,freq=1.0), product of:",
                            "details": [
                              {
                                "value": 0.34448737,
                                "description": "queryWeight, product of:",
                                "details": [
                                  {
                                    "value": 7.1740174,
                                    "description": "idf(docFreq=17, maxDocs=8642)",
                                    "details": []
                                  },
                                  {
                                    "value": 0.048018754,
                                    "description": "queryNorm",
                                    "details": []
                                  }
                                ]
                              },
                              {
                                "value": 1.5693163,
                                "description": "fieldWeight in 2937, product of:",
                                "details": [
                                  {
                                    "value": 1,
                                    "description": "tf(freq=1.0), with freq of:",
                                    "details": [
                                      {
                                        "value": 1,
                                        "description": "termFreq=1.0",
                                        "details": []
                                      }
                                    ]
                                  },
                                  {
                                    "value": 7.1740174,
                                    "description": "idf(docFreq=17, maxDocs=8642)",
                                    "details": []
                                  },
                                  {
                                    "value": 0.21875,
                                    "description": "fieldNorm(doc=2937)",
                                    "details": []
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }

请问这个是什么原因呢？

**Comment by JohnTian** [comment]
你还是直接上你的搜索语句吧，例如在es服务器命令行输入下列语句：
```
curl -XPOST localhost:9200/yourIndex/yourType/_search?pretty -d '
{
    "query":
    {
        "match": {  "yourField":  "索菲特" }
    }
}
'
```
前提是你定义了yourIndex 和 yourType

`curl -XPUT localhost:9200/yourIndex?pretty -d @yourIndex.json`

在yourIndex.json中包含 **类似** 以下内容：

```
    {
    "mappings":
        {
        "yourType": {
                "_all": {
                    "analyzer": "ik_smart",
                    "search_analyzer": "ik_smart",
                    "term_vector": "no",
                    "store": "false"
                },
                "properties": {
                    "yourField": {
                        "type": "string",
                        "store": "yes",
                        "term_vector": "with_positions_offsets",
                        "analyzer": "ik_smart",
                        "search_analyzer": "ik_smart",
                        "include_in_all": "true",
                        "boost": 8
                    }
                }
            }
        }
    }
```

**Comment by medcl** [comment]
查询贴一下看看

**Comment by levylll** [comment]
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "status": 1
                    }
                },
                {
                    "term": {
                        "is_country": 0
                    }
                }
            ],
            "must": [
                {
                    "multi_match": {
                        "query": "索菲特",
                        "type": "phrase",
                        "fields": [
                            "product_name^3",
                            "product_short_name^2",
                            "pinyin",
                            "area_name^5",
                            "key_words^4"
                        ]
                    }
                }
            ]
        }
    }
}
这样就搜索不到
如果是下面的样子，就能搜到
{
    "query": {
        "bool": {
            "filter": [
                {
                    "term": {
                        "status": 1
                    }
                },
                {
                    "term": {
                        "is_country": 0
                    }
                }
            ],
            "must": [
                {
                    "multi_match": {
                        "query": "索菲特",
                        "fields": [
                            "product_name^3",
                            "product_short_name^2",
                            "pinyin"
                        ]
                    }
                }
            ]
        }
    }
}
两者的区别就是type，但是从我的分词是可以看到的，索菲特是有被视为是整词的，但是用phrase没有匹配到，目前我这边的es库里，出现了很多的这种情况。

**Comment by levylll** [comment]
@medcl 麻烦帮忙看一下，多谢了~~

**Comment by medcl** [comment]
@levylll 你用的es版本多少，我这里测了一下是没问题的，方便给几条测试数据和你的mapping么？

**Comment by levylll** [comment]
@medcl 我目前的版本是2.1.1，因为是在线上，所以不是很方便更新es版本，那我QQ上发你我的测试数据和mapping吧，多谢了~

**Comment by medcl** [comment]
`
PUT myindex
{
  "index": {
    "analysis": {
      "analyzer": {
        "product_name_analyzer": {
          "type": "custom",
          "tokenizer": "ik"
        },
        "product_pinyin_analyzer": {
          "type": "custom",
          "tokenizer": "my_pinyin",
          "filter": "word_delimiter"
        }
      },
      "tokenizer": {
        "my_pinyin": {
          "type": "pinyin",
          "first_letter": "none",
          "padding_char": " "
        }
      }
    }
  }
}

PUT myindex/enjoy_product/_mapping
{
  "properties": {
    "key_words": {
      "type": "string",
      "analyzer": "product_name_analyzer"
    },
    "pinyin": {
      "type": "string",
      "analyzer": "product_pinyin_analyzer"
    },
    "product_name": {
      "type": "string",
      "analyzer": "product_name_analyzer"
    },
    "product_short_name": {
      "type": "string",
      "analyzer": "product_name_analyzer"
    }
  }
}


PUT myindex/enjoy_product/1
{
"product_short_name": "新元素餐厅单人餐",
"key_words": "",
"product_name": "在全透明落地窗旁享受悠闲单人时光 新元素餐厅单人餐",
"status": 1,
"pinyin": "在全透明落地窗旁享受悠闲单人时光 新元素餐厅单人餐",
"area_name": "大悦城",
"is_country": 0
}


PUT myindex/enjoy_product/2
{
"product_short_name": "新元素餐厅双人餐",
"key_words": "",
"product_name": "享“瘦”8种新鲜食材打造的营养美味 新元素餐厅双人餐",
"status": 1,
"pinyin": "享“瘦”8种新鲜食材打造的营养美味 新元素餐厅双人餐",
"area_name": "大悦城",
"is_country": 0
}


POST myindex/_search
{
    "query": {
        "bool": {
            "must": [
                {
                    "multi_match": {
                        "query": "新元素",
                        "type": "phrase",
                        "fields": [
                            "product_name^3",
                            "product_short_name^2",
                            "pinyin",
                            "area_name^5",
                            "key_words^4"
                        ]
                    }
                }
            ]
        }
    }
}

POST myindex/_search
{
    "query": {
        "bool": {
            "must": [
                {
                    "multi_match": {
                        "query": "新元素",
                        "fields": [
                            "product_name^3",
                            "product_short_name^2",
                            "pinyin",
                            "area_name^5",
                            "key_words^4"
                        ]
                    }
                }
            ]
        }
    }
}
`
我这查询ok的，你bool里面的filter写法不对
