### ISSUE TITLE
感觉版本支持好乱啊

### ISSUE THREAD

**Issue by alonebicycle** [medcl/elasticsearch-analysis-ik#198]

**Comment by medcl** [comment]
你的是什么版本？

**Comment by alonebicycle** [comment]
es 2.2.0

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.8.0  ，用这个版本就行，不过这个版本需要自己打包，后续的版本有打好的包

**Comment by alonebicycle** [comment]
非常感谢，我试试

**Comment by xibeilin** [comment]
请问 es 2.3.1 要用那个版本？

**Comment by medcl** [comment]
@xibeilin https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.9.1

**Comment by xibeilin** [comment]
@medcl 谢谢 可以了

**Comment by 0xcb49** [comment]
@medcl 请问ik支持es1.7.1吗？

**Comment by alonebicycle** [comment]
支持了啊

**Comment by 0xcb49** [comment]
应该选择哪个版本呢？
2016年5月31日 17:50，"alonebicycle" <notifications@github.com>写道：

**Comment by alonebicycle** [comment]
奥，抱歉，我刚才看错了成jdk1.7了，这个问题还是应该@medcl回答了。

**Comment by medcl** [comment]
@0xcb49  试试v1.4.1版本，版本间变化不大的，之前的版本都是兼容的

**Comment by 0xcb49** [comment]
ok，我是在v1.4.1编译的，目前测试正常，十分感谢！
2016年5月31日 18:18，"Medcl" <notifications@github.com>写道：

**Comment by linjianzhong** [comment]
请问 es 2.3.2 要用那个版本？

**Comment by medcl** [comment]
@linjianzhong 1.9.2

**Comment by CodeLieutenant** [comment]
之前的版本都兼容？也就是说，假如我现在是es1.6，安装ik1.9.3也可以？

**Comment by medcl** [comment]
5.0以后会和es版本保持一致
