### ISSUE TITLE
curl -XPOST "http://localhost:9200/_analyze?analyzer=ik&text=歌手&pretty"

### ISSUE THREAD

**Issue by xiejie** [medcl/elasticsearch-analysis-ik#199]
{
  "tokens" : [ {
    "token" : "￦",
    "start_offset" : 0,
    "end_offset" : 1,
    "type" : "OTHER_CJK",
    "position" : 0
  }, {
    "token" : "ﾭ",
    "start_offset" : 1,
    "end_offset" : 2,
    "type" : "OTHER_CJK",
    "position" : 1
  }, {
    "token" : "ﾌ",
    "start_offset" : 2,
    "end_offset" : 3,
    "type" : "OTHER_CJK",
    "position" : 2
  }, {
    "token" : "￦",
    "start_offset" : 3,
    "end_offset" : 4,
    "type" : "OTHER_CJK",
    "position" : 3
  }, {
    "token" : "ﾉ",
    "start_offset" : 4,
    "end_offset" : 5,
    "type" : "OTHER_CJK",
    "position" : 4
  }, {
    "token" : "ﾋ",
    "start_offset" : 5,
    "end_offset" : 6,
    "type" : "OTHER_CJK",
    "position" : 5
  } ]
}

// elasticsearch Version: 2.3.1
// elasticsearch-analysis-ik-1.9.1

**Comment by medcl** [comment]
需要urlencode(中文)

**Comment by xiejie** [comment]
谢谢
