### ISSUE TITLE
Mongodb同步数据到Elasticsearch2.3.3 ik 创建mapping出错

### ISSUE THREAD

**Issue by MemoriesLina** [medcl/elasticsearch-analysis-ik#201]
Mongodb同步数据到Elasticsearch2.3.3后，ik已经配置好了，用ik的例子是能创建mapping,但是用mongo-connector同步数据到Elasticsearch后，在用mongdb同步创建的index的时候，index下的type创建mapping都是失败。code:
curl -XPOST http://localhost:9200/index/articletest/_mapping -d'
{
    "articletest": {
             "_all": {
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "content": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            },   "articleid": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}'
错误：
{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Mapper for [_all] conflicts with existing mapping in other types:\n[mapper [_all] has different [analyzer], mapper [_all] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [_all] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]"}],"type":"illegal_argument_exception","reason":"Mapper for [_all] conflicts with existing mapping in other types:\n[mapper [_all] has different [analyzer], mapper [_all] is used by multiple types. Set update_all_types to true to update [search_analyzer] across all types., mapper [_all] is used by multiple types. Set update_all_types to true to update [search_quote_analyzer] across all types.]"},"status":400}

**Comment by MemoriesLina** [comment]
@medcl

**Comment by JohnTian** [comment]
May you should change 
`curl -XPOST http://localhost:9200/index/articletest/_mapping`
to 
`curl -XPOST http://localhost:9200/index/_mapping`

**Comment by MemoriesLina** [comment]
@JohnTian no. error: mapping type is missing

**Comment by JohnTian** [comment]
[mapping](https://www.elastic.co/guide/en/elasticsearch/reference/2.3/mapping.html#mapping-type)

**Comment by medcl** [comment]
你要不把mapping里面的`_all`字段的analyzer配置去掉，要么保证该index下面所有的不同类型的all配置都一样。

**Comment by medcl** [comment]
Closing， fell free to reopen。

**Comment by wanming** [comment]
遇到了一样的问题
```javascript
{  
   "error":{  
      "root_cause":[  
         {  
            "type":"illegal_argument_exception",
            "reason":"Mapper for [title] conflicts with existing mapping in other types:\n[mapper [title] has different [store_term_vector] values, mapper [title] has different [store_term_vector_offsets] values, mapper [title] has different [store_term_vector_positions] values, mapper [title] has different [analyzer]]"
         }
      ],
      "type":"illegal_argument_exception",
      "reason":"Mapper for [title] conflicts with existing mapping in other types:\n[mapper [title] has different [store_term_vector] values, mapper [title] has different [store_term_vector_offsets] values, mapper [title] has different [store_term_vector_positions] values, mapper [title] has different [analyzer]]"
   },
   "status":400
}
```

某个 doc 的数据如下：
```javascript
{  
   id:50,
   deletedAt:null,
   guid:"2be95fd51e4f4525bf945554cd66aba7",
   height:100,
   path:"55d9ce128208e1297f02abd4bc6a87ac.gif",
   size:989965,
   status:0,
   title:"fasdfasdf",
   width:976,
   updatedAt:"2016-09-03T14:56:49.000Z",
   createdAt:"2016-09-03T14:40:19.000Z",
   tags:[  
      "222",
      "TestTag",
      "gif"
   ]
}
```

发送的数据（我根据楼上的，去掉了 _all，带上了也有 _all 的相关错误）
```
 curl -XPOST http://localhost:9200/nut/files/_mapping -d'
{
    "files": {
        "properties": {
            "title": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}'

```
该咋办呢。。

**Comment by abanger** [comment]
在5.1.1 下，只要把type由string改为text就可以

{
"articletest": {
    "_all": {
        "analyzer": "ik_max_word",
        "search_analyzer": "ik_max_word",
        "term_vector": "no",
        "store": "false"
    },
    "properties": {
        "content": {
            "type": "text",
            "store": "no",
            "term_vector": "with_positions_offsets",
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "include_in_all": "true",
            "boost": 8
        }, 
        "articleid": {
            "type": "text",
            "store": "no",
            "term_vector": "with_positions_offsets",
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "include_in_all": "true",
            "boost": 8
        }
    }
}
}
