### ISSUE TITLE
支持Elasticsearch 5.0.0-alpha3吗?

### ISSUE THREAD

**Issue by zwl1619** [medcl/elasticsearch-analysis-ik#206]
支持Elasticsearch 5.0.0-alpha3吗?

**Comment by medcl** [comment]
5.0还没正式release，不建议用于生产环境，暂时不支持

**Comment by pancz** [comment]
是不是可以出一个  SNAPSHOT 便于我们线下环境试用ES5.0 @medcl

**Comment by medcl** [comment]
@pancz 没有问题

**Comment by nathan-zhu** [comment]
@medcl 同求测试5.0的分词，多谢。

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.0.0-alpha5

**Comment by pancz** [comment]
3Q @medcl
