### ISSUE TITLE
是不是新版本不用再elasticsearch.yml中配置一些信息了？

### ISSUE THREAD

**Issue by ronyuzhang** [medcl/elasticsearch-analysis-ik#207]
我安装的1.9.3 在elasticsearch.yml中配置了
index:
  analysis:
    analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true

但是却报错了Caused by: java.lang.IllegalArgumentException: Unknown Analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]
@medcl

**Comment by JohnTian** [comment]
I think you should just add `index.analysis.analyzer.default.type: ik` at the bottom of **elasticsearch.yml**.

**Comment by medcl** [comment]
`type: org.elasticsearch.index.analysis.IkAnalyzerProvider`
不支持了
`type: ik`
支持
