### ISSUE TITLE
请问同义词可以热更新吗

### ISSUE THREAD

**Issue by boolBit** [medcl/elasticsearch-analysis-ik#222]
重建索引的时候能够应用就可以，现在好像更新了同义词，需要重启elasticsearch服务

**Comment by medcl** [comment]
同义词不支持热更新

**Comment by ln94223** [comment]
es 1.7 版本对应的ik分词器 更新了自定义词库后只有重启es服务 才能应用吗？

**Comment by medcl** [comment]
同义词不支持动态加载更新
