### ISSUE TITLE
能否提供一个2.3.3打包好的ik啊???非java者很愁啊啊

### ISSUE THREAD

**Issue by a121984376** [medcl/elasticsearch-analysis-ik#225]
在下面的回复找到已经打包好的2.3.1~~结果在ES2.3.3里不能用啊啊~~

小版本都不让用啊啊 ~~

**Comment by a121984376** [comment]
通过修改properties 中指定的es版本~~可以运行起来了...但是还不知道会有什么问题~~

**Comment by nathan-zhu** [comment]
打包还好吧，不是很复杂啊 mvn package 就行

**Comment by medcl** [comment]
这里不有么？
https://github.com/medcl/elasticsearch-analysis-ik/releases

**Comment by loswing** [comment]
我把集群1.6升级到2.3.3  但是分词都不起作用了。数据大概60亿从新进数据，非常麻烦。以前定义的mapping是

"txsj": {
    "dynamic_templates": [
      {
        "en": {
          "mapping": {
            "search_analyzer": "ik_smart",
            "analyzer": "ik_smart",
            "type": "string"
          },
          "match_mapping_type": "string",
          "match": "*"
        }
      }
    ],
    "_timestamp": {

    },
    "properties": {
      "_LDCREATETIME": {
        "type": "long"
      },
      "RYBH": {
        "analyzer": "ik_smart",
        "type": "string"
      },
     "XB": {
        "analyzer": "ik_smart",      
         "type": "string"
      }
    }
  }

1、如何修改才可以让ik起作用
现在
POST /user/txsj/_search
{
    "query" : { "" : { "XB" : "刘" }},
    "highlight" : {
        "pre_tags" : ["<tag1>", "<tag2>"],
        "post_tags" : ["</tag1>", "</tag2>"],
        "fields" : {
            "content" : {}
        }
    }
}
什么都查不到
2、如何在查询的_all的时候不让es启动分词查询

3、如何在2.3中设置ik为默认分词

 
发件人： Medcl
发送时间： 2016-06-29 10:39
收件人： medcl/elasticsearch-analysis-ik
主题： Re: [medcl/elasticsearch-analysis-ik] 能否提供一个2.3.3打包好的ik啊???非java者很愁啊啊 (#225)
Closed #225.

**Comment by medcl** [comment]
@loswing 配置文件有没有问题，新版本不用配置就行了，详细错误贴一下
