### ISSUE TITLE
如何默认支持ik_smart

### ISSUE THREAD

**Issue by tottishi05** [medcl/elasticsearch-analysis-ik#226]
想创建**索引**的时候，不显示指定，而是默认使用**ik_smart** **analyzer**
如何配置，需要在**elasticsearch.yml**里如何配置？？

**Comment by wuziliang18** [comment]
你好，你这个问题解决了吗，我也想问这个问题

**Comment by tottishi05** [comment]
@wuziliang18 没有啊，没有人回复我

**Comment by medcl** [comment]
`
index.analysis.analyzer.default.use_smart: true
index.analysis.analyzer.default.type: ik
`

**Comment by tottishi05** [comment]
@medcl 
感谢，回头我试一下
