### ISSUE TITLE
elasticsearch5.0.0版本对应的更新有计划吗？

### ISSUE THREAD

**Issue by hongfuli** [medcl/elasticsearch-analysis-ik#234]
你好，请问elasticsearch5.0版本对应的ik插件有更新吗？因为elasticsearch5.0[插件机制变化](https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking_50_plugins.html#_analysisplugin)了。

  > AnalysisPluginedit
  >Plugins that register custom analysis components should implement AnalysisPlugin and remove their   onModule(AnalysisModule) implementation.

**Comment by medcl** [comment]
会更新的，不过现在5.0还没正式发布

**Comment by hongfuli** [comment]
不是很懂细节，修改了一下不兼容的代码并编译了一个用于5.X的版本，链接：http://pan.baidu.com/s/1miRfjS0

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.0.0-alpha5
