### ISSUE TITLE
安装分词器插件按着您给的说明来的，设置默认的分词器后，启动后老是报错后台，[no default analyzer configured]

### ISSUE THREAD

**Issue by baiyq152** [medcl/elasticsearch-analysis-ik#238]
我在ｃｏｎｆｉｇ下的配置文件里配置了
　index.analysis.analyzer.default.use_max_word: true
　 index.analysis.analyzer.default.type: ik

**Comment by baiyq152** [comment]
我想设置默认分词器，数据进ｅｓ后就默认用ｉｋ分词器，老是不成功，ｅｓ版本２。０，　ｉｋ插件是１。５，都是安装对应版本来的

**Comment by medcl** [comment]
index.analysis.analyzer.default.use_max_word  这个配置根本就没有

**Comment by medcl** [comment]
```
index.analysis.analyzer.default.use_smart: true
index.analysis.analyzer.default.type: ik

```
或（默认use_smart是false）
```
index.analysis.analyzer.default.use_smart: false

index.analysis.analyzer.default.type: ik

```
