### ISSUE TITLE
为什么我安装IK之后，创建索引，总是报400错误，提示我_id不能配置

### ISSUE THREAD

**Issue by groopyang** [medcl/elasticsearch-analysis-ik#239]
elasticsearch 2.3.3 
ik 1.9.3
mapping的内容：
{
  "order": 0,
  "template": "mydb*",
  "settings": {
      "number_of_shards": "2",
      "number_of_replicas": "1"
  },
  "mappings": {
    "_default_": {
      "_source": {
        "enabled": false
      }
    },
    "mydoc": {
      "properties": {
        "id": {
          "type": "string",
          "index": "not_analyzed"
        },
        "name": {
          "index": "analyzed",
          "analyzer": "ik",
          "type": "string"
        }
      },
      "_id": {
        "path": "id"
      },
      "_source": {
        "enabled": true
      },
      "_all": {
        "enabled": true
      }
    }
  },
  "aliases": {"docidx":{}}
}
报错的内容：
{

```
"error": {
    "root_cause": [
        {
            "type": "mapper_parsing_exception",
            "reason": "_id is not configurable"
        }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [house]: _id is not configurable",
    "caused_by": {
        "type": "mapper_parsing_exception",
        "reason": "_id is not configurable"
    }
},
"status": 400
```

}

**Comment by medcl** [comment]
现在已经不支持这种配置了

**Comment by niyuelin1990** [comment]
现在应该如何设置

**Comment by medcl** [comment]
_id不能进行配置
