### ISSUE TITLE
是不是可以不用加lowercase?或者提供可以关闭的设置?或者提供一个不做任何预处理的tokenizer?

### ISSUE THREAD

**Issue by imevis** [medcl/elasticsearch-analysis-ik#241]
某些场景下可能需要做驼峰分词，ik预处理直接全部lowercase了，官方提供的word_delimiter起不了作用，但实际lowercase可以通过filter转换。

**Comment by medcl** [comment]
没问题，我加个配置吧

**Comment by medcl** [comment]
`
index:
  analysis:
    tokenizer:
      my_ik:
        type: ik
        enable_lowercase: false
      my_ik_lowercase:
        type: ik
        enable_lowercase: true
    analyzer:
      my_ik_analyzer:
        type: ik
        enable_lowercase: false
        use_smart: true
`

**Comment by imevis** [comment]
方便多了！谢谢！
