### ISSUE TITLE
请问ES 2.1.2 对应IK哪个版本

### ISSUE THREAD

**Issue by blueseaport** [medcl/elasticsearch-analysis-ik#242]
请问ES 2.1.2 对应 IK 哪个版本。我使用 IK 1.7, IK 1.8，在启动ES时都报IK版本不匹配。谢谢

**Comment by medcl** [comment]
抱歉，es2.1.2没有打对应的包，不过你下载最新的源码，修改pom.xml里面es的版本号为2.1.2打包就行了，或者下载release里面的包，修改property文件里面es版本号
