### ISSUE TITLE
添加索引报400错误  Root mapping definition has unsupported parameters

### ISSUE THREAD

**Issue by wangchen223** [medcl/elasticsearch-analysis-ik#245]
添加索引
curl -XPOST http://192.168.179.131:9200/log/error/_mapping -d'
{
    "fulltext": {
             "_all": {
            "analyzer": "ik_max_word",
            "search_analyzer": "ik_max_word",
            "term_vector": "no",
            "store": "false"
        },
        "properties": {
            "Error": {
                "type": "string",
                "store": "no",
                "term_vector": "with_positions_offsets",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_max_word",
                "include_in_all": "true",
                "boost": 8
            }
        }
    }
}'
后报400错误，谁遇到过呀？

{

    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "Root mapping definition has unsupported parameters: [fulltext : {_all={analyzer=ik_max_word, search_analyzer=ik_max_word, term_vector=no, store=false}, properties={error={type=string, store=no, term_vector=with_positions_offsets, analyzer=ik_max_word, search_analyzer=ik_max_word, include_in_all=true, boost=8}}}]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "Root mapping definition has unsupported parameters: [fulltext : {_all={analyzer=ik_max_word, search_analyzer=ik_max_word, term_vector=no, store=false}, properties={error={type=string, store=no, term_vector=with_positions_offsets, analyzer=ik_max_word, search_analyzer=ik_max_word, include_in_all=true, boost=8}}}]"
    },
    "status": 400

}

**Comment by medcl** [comment]
你需要把`fulltext ` 换成实际的type名称：`error`
