### ISSUE TITLE
maven打包出错

### ISSUE THREAD

**Issue by Samuel-liuse** [medcl/elasticsearch-analysis-ik#246]
打包报错，尝试了两台电脑都这样，用的是maven最新版
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-ik: Compilation failure
[ERROR] /Users/Samuel/Desktop/elasticsearch-analysis-ik-master/src/main/java/org/wltea/analyzer/query/SWMCQueryBuilder.java:[78,65] 错误: 不兼容的类型: boolean无法转换为Configuration
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
➜  elasticsearch-analysis-ik-master mvn -v
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /Library/Java/apache-maven-3.3.9
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.5", arch: "x86_64", family: "mac"
➜  elasticsearch-analysis-ik-master java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

**Comment by medcl** [comment]
fixed with 7e86d7390acc072eed5e20a08a72a08f7400dc98

**Comment by Aibric** [comment]
我打包也报这个错，换成fixed with 7e86d73，也不行。。。

**Comment by medcl** [comment]
错误贴一下

**Comment by Aibric** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-analysis-ik 1.9.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ elasticsearch-analysis-ik ---
[INFO] Deleting D:\elasticsearch\elasticsearch-analysis-ik-master\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-analysis-ik ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch-analysis-ik ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ elasticsearch-analysis-ik ---
[INFO] Compiling 28 source files to D:\elasticsearch\elasticsearch-analysis-ik-master\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \elasticsearch\elasticsearch-analysis-ik-master\src\main\java\org\wltea\analyzer\query\SWMCQueryBuilder.java:[78,65] 错误: 不兼容的类型: boolean无法转换为Configuration
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.859 s
[INFO] Finished at: 2016-07-26T10:02:27+08:00
[INFO] Final Memory: 22M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-ik: Compilation failure
[ERROR] \elasticsearch\elasticsearch-analysis-ik-master\src\main\java\org\wltea\analyzer\query\SWMCQueryBuilder.java:[78,65] 错误: 不兼容的类型: boolean无法转换为Configuration
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by Aibric** [comment]
[INFO] ------------------------------------------------------------------------
[INFO] Building elasticsearch-analysis-ik 1.9.4
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ elasticsearch-analysis-ik ---
[INFO] Deleting D:\elasticsearch\elasticsearch-analysis-ik-master\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ elasticsearch-analysis-ik ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch-analysis-ik ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ elasticsearch-analysis-ik ---
[INFO] Compiling 28 source files to D:\elasticsearch\elasticsearch-analysis-ik-master\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] \elasticsearch\elasticsearch-analysis-ik-master\src\main\java\org\wltea\analyzer\query\SWMCQueryBuilder.java:[78,65] 错误: 不兼容的类型: boolean无法转换为Configuration
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.859 s
[INFO] Finished at: 2016-07-26T10:02:27+08:00
[INFO] Final Memory: 22M/212M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project elasticsearch-analysis-ik: Compilation failure
[ERROR] \elasticsearch\elasticsearch-analysis-ik-master\src\main\java\org\wltea\analyzer\query\SWMCQueryBuilder.java:[78,65] 错误: 不兼容的类型: boolean无法转换为Configuration
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by medcl** [comment]
请 pull一下，这个文件已经删除了

**Comment by Aibric** [comment]
重新下载，打包，好了，谢谢@medcl.
