### ISSUE TITLE
Ik分词问题

### ISSUE THREAD

**Issue by wbj0110** [medcl/elasticsearch-analysis-ik#249]
![image](https://cloud.githubusercontent.com/assets/5533297/17135716/bafddf14-5363-11e6-94f8-af41624bacbe.png)
我按Readme.md 配置的，新增文档的时候报了这个错
请问怎么解决

**Comment by iwwenbo** [comment]
@wbj0110  我也是按照readme.md安装的，步骤记录在这里了，你可以参考一下：http://www.iwwenbo.com/elasticsearch-ik-install/ ，如果有不清楚的可以讨论一下

**Comment by medcl** [comment]
错误提示很明显，json格式不合法
