### ISSUE TITLE
如何配置不匹配单个汉字呢

### ISSUE THREAD

**Issue by giantray** [medcl/elasticsearch-analysis-ik#250]
例如搜索关键字“金融圈”，ik_smart模式，会将分词分为“金融”，“圈”，但是“圈”这个字是没意义的（至少在我们的业务场景里面），因此，希望分词（或者搜索时）时不去匹配单个汉字。请问要怎么配置呢？

目前使用的es版本是1.7

**Comment by medcl** [comment]
两个方案：
1.新增词库『金融圈』
2.查询确保同时匹配『金融』和『圈』，设置 default_operator=AND

**Comment by javasgl** [comment]
将 圈 加入到stopwords中不是就不会分词了？
金融圈 analyze的结果就只有 金融了
