### ISSUE TITLE
我按照步骤 安装了 es 和 ik 

### ISSUE THREAD

**Issue by Ballwang** [medcl/elasticsearch-analysis-ik#252]
我按照步骤 安装了 es 和 ik ，
当es中没有 ik的时候 ，es运行正常，但是 通过 插件方式按照 ik的时候 ，插入 数据显示失败，找不到ik索引，
我的运行环境是  centos 6.5 64位
elasticsearch 2.3.4
ik 最新的
jdk 1.8（我发现 ik中写的是1.7  是不是这里会有问题）

**Comment by medcl** [comment]
插件方式安装？怎么安装的？
现在还不支持插件安装

**Comment by Ballwang** [comment]
通过以下方式安装的
./plugin -install analysis-ik -u file:///root/elasticsearch-analysis-ik-master/target/releases/elasticsearch-analysis-ik-1.9.4.zip
