### ISSUE TITLE
IK是怎么支持IP地址分词的

### ISSUE THREAD

**Issue by kunkun2858** [medcl/elasticsearch-analysis-ik#255]
我用的是1.9.0版本的IK，比如192.168.1.1分词结果只有一个，那这样我用192.168 或者1.1去检索是没有结果的，能分成这种粒度嘛

**Comment by medcl** [comment]
这个字段里面只有ip么？

**Comment by kunkun2858** [comment]
哦  我的这个字段里只有IP

**Comment by medcl** [comment]
如果是IP字段，那直接使用es的ip数据类型吧，提供更丰富的功能
