### ISSUE TITLE
ES 2.3.4和IK 分词中文出现OTHER_CJK的type类型

### ISSUE THREAD

**Issue by minibear0523** [medcl/elasticsearch-analysis-ik#256]
OS: ubuntu server 16.04 LTS
ES: 2.3.4
IK: 1.9.4
locale: 
![image](https://cloud.githubusercontent.com/assets/1175287/17463199/8feba574-5cf3-11e6-8456-44f01666579b.png)

问题:
![image](https://cloud.githubusercontent.com/assets/1175287/17463208/b4d33438-5cf3-11e6-91d4-ca2e0ed72f17.png)

如果在浏览器中输入, 会出现正确的结果:
![image](https://cloud.githubusercontent.com/assets/1175287/17463229/3a422d36-5cf4-11e6-92f8-dd3c40122340.png)

但是在sense工具里输入的话, 就没有任何结果:
![image](https://cloud.githubusercontent.com/assets/1175287/17463240/55f13964-5cf4-11e6-922f-71ad2ea5d1f3.png)

**Comment by medcl** [comment]
终端下请urlencode转义一下
