### ISSUE TITLE
在es外部使用ik分词问题

### ISSUE THREAD

**Issue by jacklone** [medcl/elasticsearch-analysis-ik#257]
请教，想在es外部和es内部保证分词效果一致，问题和
https://discuss.elastic.co/t/using-elasticsearch-analyzers-outside-of-elasticsearch/8600 差不多，想知道elasticsearch-analysis-ik中的ik是哪个版本的~

**Comment by medcl** [comment]
基于作者最新的 IK Analyzer 2012
