### ISSUE TITLE
姓氏是否可以开放为千家姓？

### ISSUE THREAD

**Issue by michealyq** [medcl/elasticsearch-analysis-ik#265]
http://wenku.baidu.com/view/d5dd60ce52ea551811a68786.html?from=search
比如这个列表

**Comment by michealyq** [comment]
http://www.jiapu.best198.com/e/  姓氏谱

**Comment by medcl** [comment]
可以的

**Comment by aeroplane** [comment]
感谢楼主提供，`surname.dic`自己可以改

**Comment by michealyq** [comment]
thanks medcl
