### ISSUE TITLE
结合ik使用suggester，没有结果返回

### ISSUE THREAD

**Issue by Vincent717** [medcl/elasticsearch-analysis-ik#266]
Hi medcl,

最近我在用尝试试用term (phrase) suggester进行中文纠错，但是却一直没有得到返回理想的结果 甚至没有结果。使用ik进行的中文分词。

比如进行如下搜索：
`  "suggest": {
    "revise_suggestion": {
      "text": "运动写"
        ,"phrase": {
          "field": "goods_name"
          ,"size": 3
          ,"real_word_error_likelihood" : 0.95
          ,"max_errors" : 0.5
          ,"gram_size" : 2
          ,"direct_generator" : [ {
              "field" : "goods_name",
              "suggest_mode" : "always",
              "min_word_length" : 1
          } ]
        }
    }
}`

结果是空的：
`  "suggest" : {
    "revise_suggestion" : [ {
      "text" : "运动写",
      "offset" : 0,
      "length" : 3,
      "options" : [ ]
    } ],
`

term suggester也是返回空的结果 (按道理应该返回“运动鞋”)。同样的语句我试过英语是可以纠错的，中文不行我猜是分词的原因。mapping是这样的：
`            ,"goods_name": {
            	 "type": "string"
            	,"store": "yes"
            	,"term_vector": "with_positions_offsets"
                ,"analyzer": "ik_max_word"
                ,"search_analyzer": "ik_max_word"
                ,"include_in_all": "true"
            }`

我猜想的是ik将“运动写” 分词成了 “运动” 和 “写”， 所以单独进行了suggest，不过因为这两个都是词，所以并没有返回suggest的结果。当我尝试搜索“运懂”的时候，它又将“运”和“懂”分成了两个词。强制将搜索的关键词看作一个词(不进行分词)并不是一个好的解决办法，因为有可能有关键词确实是输入两个词这样的情况。 

所以不知道各位是否有好的建议？

谢谢！

Vincent

**Comment by medcl** [comment]
可以把完整的测试脚本发一下么，sense格式的最好，另外es什么版本？

**Comment by Vincent717** [comment]
es用的1.7.5, 对应用了ik的1.4.1. 版本有点老

具体的脚本如下：
curl -XPOST /_search?pretty -d'
{
  "size": 0,
  "suggest": {
    "revise_suggestion": {
      "text": "平底写"
        ,"phrase": {
          "field": "goods_name"
          ,"size": 3
          ,"real_word_error_likelihood" : 0.95
          ,"max_errors" : 0.5
          ,"gram_size" : 2
          ,"direct_generator" : [ {
              "field" : "goods_name",
              "suggest_mode" : "always",
              "min_word_length" : 1
          } ]
          ,"collate": {
              "query": {
                  "match": {
                      "{{field_name}}" : "{{suggestion}}"
                  }
              }
              ,"params": {"field_name": "goods_name"}
              ,"prune": "true"
          }          
        }
    }
  }
}'

结果如下：

{
  "took" : 88,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 2313153,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "suggest" : {
    "revise_suggestion" : [ {
      "text" : "平底写",
      "offset" : 0,
      "length" : 3,
      "options" : [ {
        "text" : "平衡 写",
        "score" : 1.8635456E-4,
        "collate_match" : true
      }, {
        "text" : "平板 写",
        "score" : 1.5372003E-4,
        "collate_match" : true
      }, {
        "text" : "平滑 写",
        "score" : 1.0378615E-4,
        "collate_match" : true
      } ]
    } ]
  }
}


我的期望是得到如“平底鞋”这样的答案，不过它似乎将“平底”和“写”分成了两个词，然后分别进行了suggest？所以“平底”返回了一些如“平衡”这样的建议。英文是可以的，这样看起来问题还是在于分词？他会将写错的中文分成两个词，因而不会推荐。用你的另一个pinyin插件会不会能解决中文纠错的问题

**Comment by medcl** [comment]
如果是这样，你suggest的时候可以使用keyword分词，不对查询进行分词是不是就可以

**Comment by Vincent717** [comment]
不对关键词分词也不行，因为还是有可能会输入两个关键词的，比如“运动鞋 耐克”

**Comment by Vincent717** [comment]
根据你的提示，想到一个还算满意的折中的办法，就是用whitespace的analyzer来分词，就能简单的将进行分词，又进行中文纠错了

谢谢！

**Comment by Shooting1007** [comment]
我在elasticsearch5.x遇到这个问题，差别是，什么推荐词都没。详细信息如下：
对文档title字段查询推荐词，文档信息：新闻联播，心翁连波，星闻连播，请问有什么解决办法吗？在线急等~！ 
查询：
{
  "suggest": {
    "text" : "辛文连播",
    "simple_phrase" : {
      "phrase" : {
        "field" :  "title",
        "size" :   1,
        "direct_generator" : [ {
          "field" :            "title",
          "suggest_mode" :     "always",
          "min_word_length" :  1
        } ]
      }
    }
  }
}
'
查询结果：
{
  "took" : 5,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : 0.0,
    "hits" : [ ]
  },
  "suggest" : {
    "simple_phrase" : [
      {
        "text" : "辛文连播",
        "offset" : 0,
        "length" : 4,
        "options" : [ ]
      }
    ]
  }
}

**Comment by medcl** [comment]
完整复现脚本发一下吧

**Comment by richardlyc** [comment]
phrase suggest 无法查到结果 请问下是什么问题
post   bcc_brandtitle/brandtitle {
    "text" : "液晶电视机"
}

POST bcc_brandtitle/_search
{
 "query" : {
 "match": {
 "text":"液晶电视"
 }
 },
 "suggest" : {
 "my-suggestion" : {
 "text" : "液晶电机",
 "phrase" : {
 "field" : "text"
 }
 }
 }
}

{
 "took": 4,
 "timed_out": false,
 "_shards": {
 "total": 5,
 "successful": 5,
 "skipped": 0,
 "failed": 0
 },
 "hits": {
 "total": 1,
 "max_score": 3.3833895,
 "hits": [
 {
 "_index": "bcc_brandtitle",
 "_type": "brandtitle",
 "_id": "AWEYODMXb9Ir6s9qVXjE",
 "_score": 3.3833895,
 "_source": {
 "text": "液晶电视机"
 }
 }
 ]
 },
 "suggest": {
 "my-suggestion": [
 {
 "text": "液晶电机",
 "offset": 0,
 "length": 4,
 "options": []
 }
 ]

**Comment by uxnow** [comment]
遇到同样的问题，请问有解决方案了吗

**Comment by uxnow** [comment]
@medcl
