### ISSUE TITLE
支持es 2.4.0的ik插件

### ISSUE THREAD

**Issue by xcaptain** [medcl/elasticsearch-analysis-ik#270]
1.9.5对应的es版本是2.3.5，能否支持一下es 2.4.0的呢，谢谢。

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v1.10.0/elasticsearch-analysis-ik-1.10.0.zip

**Comment by duyongxin** [comment]
2.4.4的版本什么时候有？ 求助！

**Comment by medcl** [comment]
@duyongxin https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v2.4.4
