### ISSUE TITLE
当使用关键字进行查询时, 在返回对象中, 返回这个关键字使用 ik 分词后的 token

### ISSUE THREAD

**Issue by zw963** [medcl/elasticsearch-analysis-ik#273]
在做 API 时, 使用 elasticsearch 查询,  我们希望快速返回针对当前关键字的搜
 索结果, 这方面个人认为 mmseg 是优于 ik 的.
 现在有个问题是, 除了结果的同时, 我也期望将搜索关键字拆分后的 tokens 作为
 `推荐' 返回, 如何在这个插件层次达到这个目的?

**Comment by medcl** [comment]
analysis插件没有修改请求返回的，如果要做，只能在query的地方进行附加

**Comment by zw963** [comment]
还望请教.  谢谢.

下面是 Ruby 的伪码, 但是还算比较直观.

```rb
search(
          query: {
            multi_match: {
              query: '关键字',
              fields: [field1, field2],
              # https://www.elastic.co/blog/multi-field-search-just-got-better
              type: 'best_fields',
              analyzer: "mmseg_maxword_with_cut_letter_digi"
            }
          }
        )
```

在这之前, 我已经建立了名称为 `mmseg_maxword_with_cut_letter_digi` 的 analyzer,, 也通过 map 指定 field1, field2 的 `analyzer` 和 `searchAnalyzer` 使用这个分析器.

我对 Elasticsearch 本身了解的很肤浅, 还望请教, 谢谢.

**Comment by zw963** [comment]
因为没有回复, 先通过额外发送一次请求(极其不优雅)的方式把问题解决了.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-analyze.html

仍然盼复. 谢谢.

**Comment by medcl** [comment]
前面其实已经回复了，直接在分词的地方做不了

**Comment by zw963** [comment]
@medcl , 但是我以为你给我提示， 其实在做 query 的时候， 可以做?

例如，我们可以在查询时做排序，做其他字段的条件判断， 我认为也可以返回 tokens ?

**Comment by ScsUndefined** [comment]
这怎么感觉像是要对搜索结果进行高亮？你是在找这个吗？
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html
