### ISSUE TITLE
1.4.1的readmd文件中默认analyzer配置有问题

### ISSUE THREAD

**Issue by javasgl** [medcl/elasticsearch-analysis-ik#274]
同时为何直接配置default.type 为ik_smart却启动不起来？会导致es启动的时候报出 classNotFoundException

![image](https://cloud.githubusercontent.com/assets/5222868/18305112/8de78aa8-7518-11e6-91e2-b32f2f0b930a.png)

**Comment by javasgl** [comment]
default.type只能是ik而不能是 ik_smart?

**Comment by javasgl** [comment]
ElasticsearchIllegalArgumentException[failed to find analyzer type [ik_smart] or tokenizer for [default]]; nested: NoClassSettingsException[Failed to load class setting [type] with value [ik_smart]]; nested: ClassNotFoundException[org.elasticsearch.index.analysis.iksmart.IkSmartAnalyzerProvider

**Comment by medcl** [comment]
es已不支持节点层面配置默认analyzer
