### ISSUE TITLE
v1.9.3用plugin install 安装，config目录没安装进去

### ISSUE THREAD

**Issue by chaegumi** [medcl/elasticsearch-analysis-ik#289]
使用plugin install安装v1.9.3之后，启动elasticsearch会报错。显示是config里边的文件缺失，
我手动把config里边的ik目录放进去后，就好了。

这边说的config目录是在plugins/analysis-ik/config/ik 目录，好像配置文件到这里边找了，1.10.0就不存在这个问题。

**Comment by chaegumi** [comment]
不知道我哪里没做好。

我用“货物进出口”搜索不到结果，用“货物”或者“进出口”单独搜索可以得到结果。

**Comment by medcl** [comment]
mapping发一下吧
chaegumi <notifications@github.com>于2016年10月10日 周一上午11:00写道：

**Comment by chaegumi** [comment]
我自己后边找到问题了，是我写的query值有问题，query值用了 %搜索词%这样不行，把%%去掉就可以了，还做了中文英文的判断，如果是中文不加%，如果是英文加了%。
