### ISSUE TITLE
打算用es2.4.1  请问ik 应该下载哪个版本的啊？

### ISSUE THREAD

**Issue by feiniu5566** [medcl/elasticsearch-analysis-ik#290]
大神您好，我打算用es2.4.1  请问ik 应该下载哪个版本的啊？

**Comment by chaegumi** [comment]
1.10.0就够了

https://github.com/medcl/elasticsearch-analysis-ik/issues/260

**Comment by hiwjcn** [comment]
问题解决了吗？貌似网上的教程都不适用了

**Comment by chaegumi** [comment]
@hiwjcn 

![20161013114304](https://cloud.githubusercontent.com/assets/9654650/19336012/6d2dc302-913a-11e6-8705-9a5a585db00a.jpg)

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.10.1
