### ISSUE TITLE
 "analyzer on field [content] must be set when search_analyzer is set"

### ISSUE THREAD

**Issue by luozehua** [medcl/elasticsearch-analysis-ik#291]
elasticsearch 2.0.2  ik 1.5.0 
 按照README.MD文件中的内容安装，在重启ES的时候，日志中没有看到加载ik插件

创建索引Index
创建mapping
`{
  "fulltext": {
    "_all": {
      "indexAnalyzer": "ik_max_word",
      "searchAnalyzer": "ik_max_word",
      "term_vector": "no",
      "store": "false"
    },
    "properties": {
      "content": {
        "type": "string",
        "store": "no",
        "term_vector": "with_positions_offsets",
        "indexAnalyzer": "ik_max_word",
        "searchAnalyzer": "ik_max_word",
        "include_in_all": "true",
        "boost": 8
      }
    }
  }`

报错 {
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "analyzer on field [content] must be set when search_analyzer is set"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "analyzer on field [content] must be set when search_analyzer is set"
    },
    "status": 400
}

添加analyzer
{
  "fulltext": {
    "_all": {
      "indexAnalyzer": "ik_max_word",
      "searchAnalyzer": "ik_max_word",
      "term_vector": "no",
      "store": "false"
    },
    "properties": {
      "content": {
        "type": "string",
        "store": "no",
        "term_vector": "with_positions_offsets",
        "analyzer": "ik",
        "indexAnalyzer": "ik_max_word",
        "searchAnalyzer": "ik_max_word",
        "include_in_all": "true",
        "boost": 8
      }
    }
  }
}

报错：
{
    "error": {
        "root_cause": [
            {
                "type": "mapper_parsing_exception",
                "reason": "analyzer [ik] not found for field [content]"
            }
        ],
        "type": "mapper_parsing_exception",
        "reason": "analyzer [ik] not found for field [content]"
    },
    "status": 400
}

请问是怎么回事？是我的IK插件没有安装成功还是成功了使用错误呢？求指点！

**Comment by baijs** [comment]
`"reason": "analyzer [ik] not found for field [content]"`
这句话描述的很清楚啦，找不到 `content` 字段

**Comment by zuozhehao** [comment]
同样问题~

**Comment by medcl** [comment]
集群每个节点都需要安装

**Comment by medcl** [comment]
fell free to reopen
