### ISSUE TITLE
Maven slow

### ISSUE THREAD

**Issue by oolzpishere** [medcl/elasticsearch-analysis-ik#294]
第一次用Maven
mvn 下载的速度特别慢，有什么办法解决吗？
使用了这个镜像 http://uk.maven.org/maven2 跟默认的路径都很慢
还经常断开连接

**Comment by medcl** [comment]
打包好的在这里：https://github.com/medcl/elasticsearch-analysis-ik/releases
建议 vpn

**Comment by oolzpishere** [comment]
@medcl 谢谢啦
