### ISSUE TITLE
elasticsearch 5.0不支持Node级别的默认分词器？

### ISSUE THREAD

**Issue by tottishi05** [medcl/elasticsearch-analysis-ik#299]
如果在**elasticsearch.ymal**中设置`index.analysis.analyzer.default: ik`，就会报错：  
`node settings must not contain any index level settings`  
有什么其他办法？

**Comment by medcl** [comment]
es 已经不支持了

**Comment by tottishi05** [comment]
@medcl  
而且好像在创建索引的时候在**indexSettings**里添加的分词器也没用，必须要在**mapping**里为每个字段指定**分词器**？

**Comment by jepeng-miao** [comment]
没有必要在设置里添加了，我试过2.4添加了会报错的

**Comment by tottishi05** [comment]
@jepeng-miao 
那每个索引中的**settings.index.analysis.analyzer**有什么用呢？ 
无论有没有这个设置，在**mapping**里的任何字段都可以随意的设置自己的**analyzer**

**Comment by jepeng-miao** [comment]
@tokikanno 那个yml里面是全局的，配置好的分析器都会引入，索引里面设置的分析器是对于该索引的吧，我是这么理解的

**Comment by tokikanno** [comment]
@jepeng-miao : 應該是 tag @tottishi05 ，幫你 tag 一下

**Comment by jepeng-miao** [comment]
@tokikanno O(∩_∩)O谢谢

**Comment by tottishi05** [comment]
@jepeng-miao 
我试过了，有`elasticsearch.yaml`里面已经无法设置**分词器**了，就像我这个issue里面说的，会报错 
索引设置里面如果设置了**分词器**，**Mapping**里还是需要在**字段**级别重新设置，并且与索引里面的设置完全无关

**Comment by jepeng-miao** [comment]
@tottishi05 明白
