### ISSUE TITLE
请教个es查询问题

### ISSUE THREAD

**Issue by liupan182** [medcl/elasticsearch-analysis-ik#302]
我索引了N条数据，使用中文分词搜索正常，如下图

![image](https://cloud.githubusercontent.com/assets/10054704/19960847/4aef67c6-a1ea-11e6-9254-f166ff5276b0.png)

但是假如我搜索“中”或者“3”类似这种的时候就什么也搜索不出来，需要我怎么设置呢？

**Comment by zuozhehao** [comment]
查询的问题

**Comment by medcl** [comment]
实际场景，这种搜索测试没有异议
