### ISSUE TITLE
es rtf 版本什么时候升级到 5.0 ？windows环境下 要做 自定义分词的热更新

### ISSUE THREAD

**Issue by doubleflying** [medcl/elasticsearch-analysis-ik#303]
es rtf 版本什么时候升级到 5.0 ？我想在 windows环境下 做 自定义分词的热更新

**Comment by medcl** [comment]
1a3cfef951482010c2ea64450a5f387e9a7b8e06

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-rtf/commit/1a3cfef951482010c2ea64450a5f387e9a7b8e06
