### ISSUE TITLE
IK 插件 安装不上

### ISSUE THREAD

**Issue by xiangbin001** [medcl/elasticsearch-analysis-ik#305]
本地环境是2.4.1的，插件包是1.10.1的。windows系统
最后安装的时候是
c:\variable\elasticsearch-2.4.1\bin>plugin install medcl/elasticsearch-analysis-ik/1.10.1
-> Installing medcl/elasticsearch-analysis-ik/1.10.1...
Trying https://download.elastic.co/medcl/elasticsearch-analysis-ik/elasticsearch-analysis-ik-1.10.1.zip ...
Trying https://search.maven.org/remotecontent?filepath=medcl/elasticsearch-analysis-ik/1.10.1/elasticsearch-analysis-ik-1.10.1.zip ...
Trying https://oss.sonatype.org/service/local/repositories/releases/content/medcl/elasticsearch-analysis-ik/1.10.1/elasticsearch-analysis-ik-1.10.1.zip ...
Trying https://github.com/medcl/elasticsearch-analysis-ik/archive/1.10.1.zip ...
Trying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip ...
Downloading .....................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.................................................................................................................................................................
.......................DONE
Verifying https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip checksums if available ...
NOTE: **Unable to verify checksum for downloaded plugin** (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

找不到校验文件？谁能告诉怎么解决

**Comment by medcl** [comment]
不支持插件安装，直接下载解压到 es 的 plugins 目录即可

**Comment by jepeng-miao** [comment]
@medcl 哪个版本可以这样

**Comment by xiangbin001** [comment]
如果直接解压放进去的话es 启动就报错了。。
这是直接解压放进去的目录结构截图
![image](https://cloud.githubusercontent.com/assets/13586376/20250325/8288cd10-aa48-11e6-9003-3bb066b3ab7a.png)
启动ES报错截图
![qq 20161114090141](https://cloud.githubusercontent.com/assets/13586376/20250454/cfbdaa64-aa49-11e6-8c38-96f13e2702ce.png)

我的JDK是1.8的

**Comment by medcl** [comment]
从这里下载 https://github.com/medcl/elasticsearch-analysis-ik/releases
你目录都是源代码，当然不行
