### ISSUE TITLE
分词的效果不好

### ISSUE THREAD

**Issue by 1106285275** [medcl/elasticsearch-analysis-ik#307]
我用es1.5 + ik1.3.0 分词的效果下图1，es1.7.1+ik1.4.1分词的效果如图二。折腾了很多版本的ik分词效果都打不到图一的效果。请教一下，为什么升级以后会遇到这样的问题呢？
![image](https://cloud.githubusercontent.com/assets/21304853/20340310/e5a5da30-ac1b-11e6-9b59-f91c2d7db69e.png)  
![image](https://cloud.githubusercontent.com/assets/21304853/20340345/0e0357fa-ac1c-11e6-912a-ce8500027446.png)

**Comment by medcl** [comment]
你手动设置下 use_smart参数，应该是图二的是 ik_smart,图一是 ik_max_word

**Comment by medcl** [comment]
fell free to reopen
