### ISSUE TITLE
[ 晋玮经商务咨询（上海）有限公司 ] 的ik_max_word分词结果有问题

### ISSUE THREAD

**Issue by startarsyx** [medcl/elasticsearch-analysis-ik#311]
在默认配置下，ik_max_word切出来的结果是： 晋, 玮, 经商, 商务, 咨询, 咨, 询, 上海, 有限公司, 有限, 公司
而ik_smart切出来的结果是： 晋, 玮, 经, 商务, 咨询, 上海, 有限公司
单字“经”在ik_max_word没有，但是在ik_smart有，使得用ik_smart搜不到这条结果

**Comment by medcl** [comment]
保持索引和查询分词类型一致，才能保证结果一致，或者多字段，查询的时候，设置一下权重

**Comment by medcl** [comment]
同 #271
