### ISSUE TITLE
使用ik_smart配置，“雪花”和“雪” 很多搜索不到

### ISSUE THREAD

**Issue by xjpphp** [medcl/elasticsearch-analysis-ik#315]
使用ik_smart配置，“雪花”和“雪” 很多搜索不到，ik_max_word 不存在这个问题

**Comment by medcl** [comment]
查询和索引都同时使用一样的 analyzer，就不会有问题

**Comment by shinux** [comment]
用了同样的 analyzer ，果然粒度就细了很多，但是估计会轻微影响效率，感觉这个 issue 可以关了。
