### ISSUE TITLE
elasticsearch-analysis-ik-5.0.2.zip 没有打包吗？

### ISSUE THREAD

**Issue by oyrm** [medcl/elasticsearch-analysis-ik#317]
elasticsearch-analysis-ik-5.0.2.zip 没有打包吗？
elasticsearch5.0.2使用elasticsearch-analysis-ik-5.0.1.zip运行不了

**Comment by charshine** [comment]
自己打包，

**Comment by simonw0ng** [comment]
使用master build就可以 作者没有拉tag

**Comment by oyrm** [comment]
@charshine @simonw0ng 
谢谢两位，已用master build

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.0.2
