### ISSUE TITLE
在使用Redis来获取日志的时候应该如何设定？

### ISSUE THREAD

**Issue by afei00001** [medcl/elasticsearch-analysis-ik#320]
我现在使用的Redis来作为日志的中转，在Logstash里面配置输出的时候，用的每天生成一个索引。
所以现在不知道如何配置IK了，请知道的人告知一下。

**Comment by medcl** [comment]
es 里面设置一个 template，配置字段的 mapping

**Comment by medcl** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/5.1/indices-templates.html
PUT /_template/template_1
{
  "template": "*",
  "order": 0,
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      }
    },
    "type2": {
      "dynamic_templates": [
        {
          "named_analyzers": {
            "match_mapping_type": "string",
            "match": "*",
            "mapping": {
              "type": "text",
              "analyzer": "ik_max_word"
            }
          }
        },
        {
          "no_doc_values": {
            "match_mapping_type": "*",
            "mapping": {
              "type": "{dynamic_type}",
              "doc_values": false
            }
          }
        }
      ]
    }
  }
}

PUT /index1/type2/12
{
  "name":"测试一下",
  "age":123
}

GET /index1/_mapping
