### ISSUE TITLE
5.1.1 下载编译问题  

### ISSUE THREAD

**Issue by hanyoud** [medcl/elasticsearch-analysis-ik#323]
<parent>
        <groupId>org.sonatype.oss</groupId>
        <artifactId>oss-parent</artifactId>
        <version>7</version>
    </parent>

    <repositories>
        <repository>
            <id>oss.sonatype.org</id>
            <name>OSS Sonatype</name>
            <releases><enabled>true</enabled></releases>
            <snapshots><enabled>true</enabled></snapshots>
            <url>http://oss.sonatype.org/content/repositories/releases/</url>
        </repository>
    </repositories>

oss-parent 提示找不到  <version>7</version> 改成  <version>9</version> 就可以了 。

**Comment by medcl** [comment]
收到，谢谢
另外，直接也可以下载的
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.1.1
