### ISSUE TITLE
请问 analysis 分词后怎么做汇聚

### ISSUE THREAD

**Issue by tianbao54** [medcl/elasticsearch-analysis-ik#324]
你好，我想做一个功能是对用户搜索过的高频词汇做一个分组统计，统计出现最高频的前几名词汇，做一个推荐的功能。
请问用 analysis ik 怎么做呢？

谢谢了。

**Comment by medcl** [comment]
分词之后不适合做聚合，要聚会可以再使用另外一个 keyword 类型的子 fields
