### ISSUE TITLE
怎么设置IK为所有索引或一个索引的默认分词器？

### ISSUE THREAD

**Issue by ucasyp** [medcl/elasticsearch-analysis-ik#325]
2.X里面可以在elasticsearch.xml中指定IK为默认分词：`index.analysis.analyzer.default.type: ik`，5.X不支持这样的配置了，对于索引的字段事先不知道的情况，怎么设置IK为所有索引或一个索引的默认分词器？下面的写法没有效果:

创建索引:
`PUT blog
`
设置mapping:
```
POST blog/article/_mapping
{
  "article": {
    "_all": {
      "analyzer": "ik_max_word",
      "search_analyzer": "ik_max_word",
      "term_vector": "no",
      "store": "false"
    }
  }
}
```

**Comment by medcl** [comment]
可以使用 es 的模板制定

**Comment by medcl** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-templates.html#template-variables

**Comment by medcl** [comment]
PUT /_template/template_1
{
  "template": "*",
  "order": 0,
  "settings": {
    "number_of_shards": 1
  },
  "mappings": {
    "type1": {
      "_source": {
        "enabled": false
      }
    },
    "type2": {
      "dynamic_templates": [
        {
          "named_analyzers": {
            "match_mapping_type": "string",
            "match": "*",
            "mapping": {
              "type": "text",
              "analyzer": "ik_max_word"
            }
          }
        },
        {
          "no_doc_values": {
            "match_mapping_type": "*",
            "mapping": {
              "type": "{dynamic_type}",
              "doc_values": false
            }
          }
        }
      ]
    }
  }
}

PUT /index1/type2/12
{
  "name":"测试一下",
  "age":123
}

GET /index1/_mapping

**Comment by medcl** [comment]
补充一个全局的默认配置


```
DELETE _template/rtf


PUT _template/rtf
{
  "template":   "*", 
  "settings": { "number_of_shards": 1 }, 
  "mappings": {
    "_default_": {
      "_all": { 
        "enabled": true
      },
      "dynamic_templates": [
        {
          "strings": { 
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer":"ik_max_word",
              "ignore_above": 256,
              "fields": {
                "keyword": {
                  "type":  "keyword"
                }
              }
            }
          }
        }
      ]
    }
  }
}
```

**Comment by yongde1990** [comment]
good

**Comment by qqjt** [comment]
elasticsearch 6.0后 _all 已失效。
