### ISSUE TITLE
ik分词会忽略字？

### ISSUE THREAD

**Issue by zhuqunzhou** [medcl/elasticsearch-analysis-ik#340]
·http://xxx:9200/test/_analyze?text=我是猪么你是&tokenizer=ik_smart·

得出来的结果：只有四个词    ·我·  ·猪·  ·你·   ·么·。。 ·是·字不见了？

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/blob/master/config/custom/ext_stopword.dic
这里有停用词配置了
