### ISSUE TITLE
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for existing plugin [ik]. Was the plugin built before 2.0?

### ISSUE THREAD

**Issue by fangqiao** [medcl/elasticsearch-analysis-ik#341]
使用5.1.2,按指令mvn package以后，copy到plugin目录，重启elasticsearch， 出现以上错误。这是为何？

**Comment by hufuman** [comment]
ES的版本和插件的版本不匹配？
比较下你用的ES分支名字和Es的版本号看看

**Comment by fangqiao** [comment]
都是5.1.2哦，git checkout tags/v5.1.2

**Comment by fangqiao** [comment]
还有一句话： Caused by: java.nio.file.NoSuchFileException: /home/fqye/bin/elasticsearch-5.1.2/plugins/ik/plugin-descriptor.properties

哪里找这个文件？

**Comment by fangqiao** [comment]
不好意思，我的错，zip没解压就启动es 了
