### ISSUE TITLE
5.2.2 mvn compile 失败？

### ISSUE THREAD

**Issue by wanglong1615** [medcl/elasticsearch-analysis-ik#343]
按照步骤：
git clone https://github.com/medcl/elasticsearch-analysis-ik
cd elasticsearch-analysis-ik
git checkout tags/{version}
mvn clean
mvn compile

报错：
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/wltea/analyzer/lucene/IKAnalyzer.java:[27,34] 找不到符号
  符号:   类 Analyzer
  位置: 程序包 org.apache.lucene.analysis
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/wltea/analyzer/lucene/IKAnalyzer.java:[28,34] 找不到符号
  符号:   类 Tokenizer
  位置: 程序包 org.apache.lucene.analysis
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/wltea/analyzer/lucene/IKAnalyzer.java:[35,39] 找不到符号
  符号: 类 Analyzer
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/wltea/analyzer/lucene/IKAnalyzer.java:[62,19] 找不到符号
  符号:   类 TokenStreamComponents
  位置: 类 org.wltea.analyzer.lucene.IKAnalyzer
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/elasticsearch/plugin/analysis/ik/AnalysisIkPlugin.java:[32,83] 找不到符号
  符号:   类 Analyzer
  位置: 类 org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/elasticsearch/index/analysis/IkTokenizerFactory.java:[3,34] 找不到符号
  符号:   类 Tokenizer
  位置: 程序包 org.apache.lucene.analysis
[ERROR] /D:/elasticsearch-analysis-ik/src/main/java/org/elasticsearch/index/analysis/IkTokenizerFactory.java:[32,10] 找不到符号
  符号:   类 Tokenizer
  位置: 类 org.elasticsearch.index.analysis.IkTokenizerFactory

**Comment by medcl** [comment]
注意 java 版本
下载在这里直接有：https://github.com/medcl/elasticsearch-analysis-ik/releases

**Comment by wanglong1615** [comment]
太好了，谢谢！
