### ISSUE TITLE
不能使用elasticsearch-plugin命令安装 elasticsearch-analysis-ik

### ISSUE THREAD

**Issue by janbox** [medcl/elasticsearch-analysis-ik#344]
在使用elasticsearch-plugin命令安装分词器时，出现错误。
sudo ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.2.2/elasticsearch-analysis-ik-5.2.2.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.2.2/elasticsearch-analysis-ik-5.2.2.zip
[=================================================] 100%   
ERROR: `elasticsearch` directory is missing in the plugin zip

看上去 elasticsearch-analysis-ik-5.2.2.zip里面没有 elasticsearch目录。

需要把插件的各文件放入到 zip包中的elasticsearch目录中。

**Comment by pengqiuyuan** [comment]
elasticsearch-analysis-ik-5.2.2.zip 解压后的目录名称是 elasticsearch 才行 。

**Comment by civalin** [comment]
The same problem at 5.4.3

```
$ sudo /usr/share/elasticsearch/bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.4.3/elasticsearch-analysis-ik-5.4.3.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.4.3/elasticsearch-analysis-ik-5.4.3.zip
[=================================================] 100%   
ERROR: `elasticsearch` directory is missing in the plugin zip
```

**Comment by likaiguo** [comment]
Site plugins are not supported anymore.

5.x以后不支持这个特性了

https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_plugins.html#_site_plugins_removed

方法一:
copy and unzip target/releases/elasticsearch-analysis-ik-{version}.zip to your-es-root/plugins/ik

方法二:
修改插件这个部分的实现

**Comment by likaiguo** [comment]
@medcl 这个能不能实现一下哇,支持 elasticsearch-plugin install 方式安装.

**Comment by medcl** [comment]
嗯，我这周抽时间fix一下

**Comment by shijunti19** [comment]
lysis-ik-6.3.0.zipcsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-ana 

-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-analysis-ik-6.3.0.zip
[=================================================] 100%?? 
ERROR: `elasticsearch` directory is missing in the plugin zip

Hasn't it been repaired yet

？

**Comment by hortonwei** [comment]
还没修复吗

**Comment by medcl** [comment]
已经 fix 了的。

**Comment by Enivel** [comment]
还是不行
