### ISSUE TITLE
中英文同义词如何设置

### ISSUE THREAD

**Issue by LuZhongliang** [medcl/elasticsearch-analysis-ik#355]
`PUT /qa
{
  "settings": {
    "analysis": {
      "analyzer": {
        "ik-smart-with-synonym": {
          "tokenizer": "ik_smart",
          "filter": [
            "synonym"
          ]
        }
      },
      "filter": {
        "synonym": {
          "type": "synonym",
          "synonyms_path": "analysis/synonym.txt",
          "ignore_case": true
        }
      }
    }
  }
}`

synonym.txt
`twice cooked pork,回锅肉
`

`GET /qa/_analyze
{
  "analyzer": "ik-smart-with-synonym",
  "text": "回锅肉"
}`

`{
  "tokens": [
    {
      "token": "回锅肉",
      "start_offset": 0,
      "end_offset": 3,
      "type": "CN_WORD",
      "position": 0
    },
    {
      "token": "twice",
      "start_offset": 0,
      "end_offset": 3,
      "type": "SYNONYM",
      "position": 0
    },
    {
      "token": "cooked",
      "start_offset": 0,
      "end_offset": 3,
      "type": "SYNONYM",
      "position": 1
    },
    {
      "token": "pork",
      "start_offset": 0,
      "end_offset": 3,
      "type": "SYNONYM",
      "position": 2
    }
  ]
}`

期望的是查"回锅肉" 得到"twice cooked pork" 为同义词, 但实际却将英文按空格分成了多个词!

**Comment by medcl** [comment]
使用 es 的最新的multi-word synonym吧。

**Comment by LuZhongliang** [comment]
目前使用了同义词收缩这个方式解决. 
`twice cooked pork => 回锅肉`
参照 [多词同义词和短语查询](http://elasticsearch.cn/book/elasticsearch_definitive_guide_2.x/multi-word-synonyms.html)
多谢 @medcl , 我再去了解下 multi-word synonym
