### ISSUE TITLE
如何支持ES5.3.1

### ISSUE THREAD

**Issue by wu123456** [medcl/elasticsearch-analysis-ik#362]
我按照readme上，master对应5.x -> master，可是编译打包出来却是5.3.0，
然后就有如下报错
Plugin [analysis-ik] is incompatible with Elasticsearch [5.3.1]. Was designed for version [5.3.0]

我是只能将ES的版本退回5.3.0吗

**Comment by Michael-Jing** [comment]
只要修改一下 pom 文件里的 elasticsearchversion 就行了.

**Comment by wu123456** [comment]
可行，多谢。
