### ISSUE TITLE
使用JAVA API对String进行分词提示找不到IK分词器

### ISSUE THREAD

**Issue by hisou** [medcl/elasticsearch-analysis-ik#363]
ES版本为1.5.2，IK版本1.3.0，解压源码后用maven打包，然后把target/elasticsearch-analysis-ik-1.3.0.jar放到了ES_HOME/config下，再配置elasticsearch.yml如下：
index:
  analysis:                   
    analyzer:      
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true
index.analysis.analyzer.default.type: ik

之后在项目中：
Client  client = new TransportClient(settings)
                .addTransportAddress(new InetSocketTransportAddress("127.0.0.1", 9300))

def keyword = "我是中国人，我爱中国 "
def analyzeResponse =
                client.admin().indices()
                        .prepareAnalyze(keyword)
                        .setAnalyzer('ik')
                        .execute().actionGet()

运行后该部分报错，提示 failed to find analyzer [ik]
后改在浏览器用 http://localhost:9200/_analyze?analyzer=ik&pretty=true&text=我是中国人，我爱中国 
进行测试，同样返回"error" : "ElasticsearchIllegalArgumentException[failed to find analyzer [ik]]",
是不是我没安装好？因为所用es版本较旧，es目录下没有plugins文件夹，所以没有尝试过安装到plugins里。

PS：看到有些帖子说要先建索引，但是看到别人这样用成功过，所以觉得并不是索引问题
而且若使用.setAnalyzer('standard')，则分词成功，tokens为多个单汉字。

**Comment by medcl** [comment]
参照README和注意yml格式
