### ISSUE TITLE
何时同义词可以支持热更新

### ISSUE THREAD

**Issue by platstar** [medcl/elasticsearch-analysis-ik#364]
工作上也是有这类需求，还是有其他的做法可以暂代？

**Comment by medcl** [comment]
同义词不在本插件讨论范围内，有单独的同义词插件，貌似也有热更新的

**Comment by platstar** [comment]
只是单纯提建议,因为分词和同义词需求几乎是分不开的
我也好奇其他人拿elasitcsearch来做中文搜寻应该都会有这情况才是
其他github的同义词套件试过几个但质量都不靠谱
