### ISSUE TITLE
IK- plugin compatiblility issue for elasticsearch 2.4.5

### ISSUE THREAD

**Issue by surwasevb** [medcl/elasticsearch-analysis-ik#371]
I have tried 1.10.1, 1.10.2, 1.10.3, 1.10.4 versions
I didn't find any version compatible with elasticsearch version 2.4.5.
please help

**Comment by medcl** [comment]
use this please:
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.10.5

**Comment by surwasevb** [comment]
Thanks a lot. It's working fine.
