### ISSUE TITLE
关于es读取ik插件得配置文件权限问题

### ISSUE THREAD

**Issue by 401825317** [medcl/elasticsearch-analysis-ik#384]
java.security.AccessControlException: access denied ("java.io.FilePermission" "C
:\Program%20Files\elasticsearch-5.4.0-1TEST\plugins\ik\config\IKAnalyzer.cfg.xml
" "read")

为什么会这样？win7没有问题，windows server 2012 R2就存在这样得问题？？

**Comment by 401825317** [comment]
问题已经解决了，windows server 2012 R2 得文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！文件路径中不能带有空格啊！！！！

**Comment by zweite** [comment]
java: 这锅我来背

**Comment by medcl** [comment]
那我关了啊

**Comment by yuhuanxi** [comment]
别关啊，MAC 上也有这个问题啊

**Comment by zweite** [comment]
@yuhuanxi 你问题都没描述，应该是不一样的问题

**Comment by yuhuanxi** [comment]
您好，是和他一样的问题，一模一样，给您看截图[error](http://o79j0l6a7.bkt.clouddn.com/QQ20170701-224936@2x.png)
，在创建 mapping 的时候出现的

**Comment by yuhuanxi** [comment]
@zweite 我刚刚才想到是路径的问题，原来的路径中含有中文，刚换了个安装路径就好啦。感谢回复！

**Comment by GhostAdults** [comment]
同样的 win10当中也是这样的问题，路径中不能带有空格，否则会出现没有权限无法读取插件的问题
