### ISSUE TITLE
使用ik分词器后，索引速度变慢

### ISSUE THREAD

**Issue by Baz2013** [medcl/elasticsearch-analysis-ik#392]
ik版本： elasticsearch-analysis-ik-1.9.4
es版本：elasticsearch-2.3.4
索引设置：
{"template": "index100004-*",
    "settings": {
        "index.number_of_shards" : 9,
        "number_of_replicas" : 1
    },
    "mappings": {
        "type1": {
            "_source": {
                "enabled": false
            },
            "properties": {
                "Path": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "Type": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "message": {
                "type": "string",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_smart",
                "include_in_all": "true",
                "boost": 8
            }
            }
        }
    }
}

在测试的时候发现，在kafka里lag总量为100,000,000+的时候，使用es默认的分词器，lag总量是下降的，但是一旦换成上边的配置，lag总量就会持续增加。
另外boost参数有什么作用，我把这个参数的值改为24,32的时候都没有明显的效果。

求指导。。。。

**Comment by medcl** [comment]
ik比默认的分词处理要复杂一些，是会慢些，另外，也感谢提醒，我想我可以再做个profile看看具体慢在什么地方，优化一下。
boost现在不建议设置了，直接去掉吧。

**Comment by Baz2013** [comment]
感谢

**Comment by jostyee** [comment]
>boost现在不建议设置了，直接去掉吧。

@medcl 请问这条是从哪个版本开始变动的呢？
