### ISSUE TITLE
目前版本5.4.3貌似不支持 ES5.5

### ISSUE THREAD

**Issue by RobotJiang** [medcl/elasticsearch-analysis-ik#398]
java.lang.IllegalArgumentException: plugin [analysis-ik] is incompatible with version [5.5.0]; was designed for version [5.4.3]

各位有没有其他解决方案？

**Comment by sangjeedondrub** [comment]
Just change the version number from `5.4.3` to '5.5.0` in `pom.xml`file ,like:

```xml
<elasticsearch.version>5.5.0</elasticsearch.version>
```

and then re-package the project

```bash
mvn clean
mvn compile
mvn package
```

**Comment by zhufree** [comment]
发现这个repo除了那几个配置文件别的都一年没动过了。。。

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.5.0
