### ISSUE TITLE
[BUG]就算远程字典没有修改依然会重新加载字典

### ISSUE THREAD

**Issue by gojuukaze** [medcl/elasticsearch-analysis-ik#426]
看了一下代码，代码里判断修改时间用的是
`response.getLastHeader("Last-Modified").getValue().equalsIgnoreCase(last_modified)`
我把equalsIgnoreCase改成equals就没问题了

**Comment by medcl** [comment]
这个不应该吧

**Comment by gojuukaze** [comment]
在本地试了一下，感觉可能和java版本有关。
另外我nginx配了缓存，正常情况下第二次访问时应该返回304，本地测试是这样的，但到服务器上就变成了200。

**Comment by gojuukaze** [comment]
找到原因了，开始运行es时加载了一次，然后monitor运行时开始并没有last_modified，所以会重新加载一次
