### ISSUE TITLE
elasticsearch 2.4.6 无对应的IK。

### ISSUE THREAD

**Issue by njzengxin** [medcl/elasticsearch-analysis-ik#434]
你好：
     elasticsearch 2.4.6 无对应的IK。
     使用了elasticsearch-analysis-ik2.4.5和编译了Master分支都报错。谢谢！

**Comment by griffinqiu** [comment]
+1  谢谢

**Comment by SuperBoxser** [comment]
+1

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v1.10.6
