### ISSUE TITLE
elasticsearch-analysis-ik-5.6.0.zip 无法下载

### ISSUE THREAD

**Issue by xuhengfei** [medcl/elasticsearch-analysis-ik#438]
`
./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.0/elasticsearch-analysis-ik-5.6.0.zip
`

readme 上面说可以这么下载，实际这个地址无法下载，请问是什么状况？

**Comment by medcl** [comment]
可能是网络问题。
手动下载也可以：
https://github.com/medcl/elasticsearch-analysis-ik/releases
