### ISSUE TITLE
用了ik，关键字 移动电源被拆成了移动和电源。求助。。

### ISSUE THREAD

**Issue by xgj1988** [medcl/elasticsearch-analysis-ik#443]
我用了ik_max_word 版本是 5.4.3，我的配置如下
` "jo_search_analyzer":{
                        "type":"custom",
                        "tokenizer":"ik_max_word",
                        "filter":[
                            "synonym"
                        ]
                    },`
我配置了一个同义词  移动电源 => 充电宝 和 充电宝 => 移动电源。。现在比较尴尬的是，这个同义词不起作用，因为移动电源 被拆成了 移动 和电源  充电宝 被拆成了 充电 和 宝。  。这种情况怎么搞呢？

**Comment by airycanon** [comment]
把移动电源和充电宝增加到自定义扩展词典中，请仔细看 [README](https://github.com/medcl/elasticsearch-analysis-ik#dictionary-configuration)
