### ISSUE TITLE
1.4下不能愉快的run起来

### ISSUE THREAD

**Issue by shitiven** [medcl/elasticsearch-analysis-ik#45]
RT.

ES1.4下面不管是plugin -install  还是自己mvn 打的package 都不能愉快的run起来

能不能再搞的1.4的RTF  ^_^

**Comment by kurtzhong** [comment]
同遇到这个问题

**Comment by avastms** [comment]
目测很久以前analyzer插件向es注册自己的机制就发生变化了，但是这个源没做更新，
我已经fork了一份用新的形式向es注册， es 1.5.2目测运行得挺好，
我不是Java程序员，commit log也是乱写的，就先不PR了，
如果有急用的朋友可以去我的源里clone走试试

**Comment by medcl** [comment]
maven里面修改下es对应的版本就可以的,es1.6.0的版本我已经编译好了,可直接下载:https://github.com/medcl/elasticsearch-rtf/tree/1.6.0
