### ISSUE TITLE
5.0之后是不能使用org.elasticsearch.index.analysis.IkAnalyzerProvider？

### ISSUE THREAD

**Issue by yueyihan** [medcl/elasticsearch-analysis-ik#450]
5.0之后是不是不能使用org.elasticsearch.index.analysis.IkAnalyzerProvider 进行定义分词
使用kibana配置：
`PUT /test/_settings?preserve_existing=true
{
"analysis":{
  "analyzer":{
  "ik":{
    "type":"org.elasticsearch.index.analysis.IkAnalyzerProvider",
    "alias":"ik_analyzer"
  },
  "ik_smart":{
    "type":"ik",
    "use_smart":true
  },
  "ik_max_word":{
    "type":"ik",
    "use_smart":false
  }
}
}

}`  还是我配置的有问题报
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Unknown analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "Unknown analyzer type [org.elasticsearch.index.analysis.IkAnalyzerProvider] for [ik]"
  },
  "status": 400
}

**Comment by medcl** [comment]
5.0之后不用定义就能直接用了，请参考 README。

**Comment by yueyihan** [comment]
看readme里面说明是没有了ik analyzer
 主要是原先代码里使用 ik这analyzer，想的不改代码，定义一个ik替代

**Comment by medcl** [comment]
请去掉重复定义
yueyihan <notifications@github.com>于2017年10月17日 周二上午11:20写道：
