### ISSUE TITLE
5.6.4 E 什么时候支持？

### ISSUE THREAD

**Issue by lanmingle** [medcl/elasticsearch-analysis-ik#458]
5.6.4 什么时候支持？目前 docker 提供的最后的版本是 5.6.4 。

**Comment by alexcc4** [comment]
有解决方案了？

**Comment by jerryge** [comment]
+1

**Comment by jerryge** [comment]
@alexcc4 编辑一下 pom.xml,改成5.6.4

**Comment by alexcc4** [comment]
@jerryge git clone 出来改完，自己编译？

**Comment by alexcc4** [comment]
@jerryge 受你启发，把 https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v5.6.3/elasticsearch-analysis-ik-5.6.3.zip 下载解压出来，然后直接复制到 
`plugins` 目录，修改下 `plugin-descriptor.properties` 可以跑通。测试 `README`  的 demo 也 ok

**Comment by lanmingle** [comment]
谢谢！
