### ISSUE TITLE
ik分词器配置在es中报错

### ISSUE THREAD

**Issue by kkrgwbj** [medcl/elasticsearch-analysis-ik#464]
@medcl 你好，es中使用ik分词器创建索引报错。
###
java.security.AccessControlException: access denied ("java.io.FilePermission" "D:\Program%20Files\Java\elasticsearch-6.0.0\plugins\analysis-ik-6.0.0\config\IKAnalyzer.cfg.xml" "read")
###

**Comment by kkrgwbj** [comment]
@medcl 已经找到这个问题了，之前有人提过，是因为路径还有空格问题。[https://github.com/medcl/elasticsearch-analysis-ik/issues/384](url)

**Comment by Mydreamandreality** [comment]
@kkrgwbj 你好,是哪个路径错了呢.我的路径都是正确的呀
