### ISSUE TITLE
本地分词器

### ISSUE THREAD

**Issue by gkenan** [medcl/elasticsearch-analysis-ik#474]
你好，请问有没有elastcisearch ik有没有java可以调用的分词器？现在想要获取分词后的tokens每次都需要额外请求一次es上的ik，感觉不是很方便，如果有本地分词器就可以节省一次请求，前提得保证分词结果和es ik 一样。

**Comment by flueg** [comment]
ES这个分词器本来就是来自一个叫IK的分词，有Java版本
http://code.google.com/p/ik-analyzer/

**Comment by gkenan** [comment]
谢谢，我试试用同样的词库测试一下
