### ISSUE TITLE
使用IK的ik_max_word, 英文分词被分的很细，有没有办法让ik_max_word对英文不做分词

### ISSUE THREAD

**Issue by DodiChen** [medcl/elasticsearch-analysis-ik#478]
使用_analyze?analyzer=ik_max_word&pretty=true&text=Stich Fix进行分词
得到的结果如下：
`{
"tokens": [
{
"token": "stich",
"start_offset": 0,
"end_offset": 5,
"type": "ENGLISH",
"position": 0
}
,
{
"token": "ic",
"start_offset": 2,
"end_offset": 4,
"type": "CN_WORD",
"position": 1
}
,
{
"token": "fix",
"start_offset": 6,
"end_offset": 9,
"type": "ENGLISH",
"position": 2
}
]
_}`_

但我希望只得到 Stich 和 Fix 这两个词。在不使用ik_smart的情况下，是否有实现的方法？

**Comment by hezhiqiang** [comment]
@DodiChen 我也碰到了这个问题，你是如何解决的？

**Comment by chenygs** [comment]
大佬 这个问题是怎么解决的啊
