### ISSUE TITLE
ES6.1.1怎么设置默认为ik?

### ISSUE THREAD

**Issue by liangjian2556** [medcl/elasticsearch-analysis-ik#489]
我用

curl -H "Content-Type: application/json" -Xput  "192.168.1.162:9200/index?pretty=true"  -d  '{
    "settings" : {
        "index" : {
            "analysis.analyzer.default.type": "ik_max_word"
        }
    }
}'
这种方法设置，但是通过curl 'http://192.168.1.162:9200/index/_analyze?pretty=true' -H 'Content-Type: application/json' -d '{ "text":"这里是好记性不如烂笔头感叹号的博客们"}'这样查询还是旧的分词器，这个什么原因啊？

**Comment by medcl** [comment]
参考这里：
```
通过模板设置全局默认分词器

curl -XDELETE http://localhost:9200/_template/rtf


curl -XPUT http://localhost:9200/ _template/rtf
-d'
{
  "template":   "*", 
  "settings": { "number_of_shards": 1 }, 
  "mappings": {
    "_default_": {
      "_all": { 
        "enabled": true
      },
      "dynamic_templates": [
        {
          "strings": { 
            "match_mapping_type": "string",
            "mapping": {
              "type": "text",
              "analyzer":"ik_max_word",
              "ignore_above": 256,
              "fields": {
                "keyword": {
                  "type":  "keyword"
                }
              }
            }
          }
        }
      ]
    }
  }
}
'
```

**Comment by uninxc** [comment]
新创建的索引，依然·无法使用该模板啊  curl -XPUT http://localhost:9200/index8

**Comment by uninxc** [comment]
curl -XGET "http://localhost:9200/index999/_analyze" -H 'Content-Type: application/json' -d'
{

   "text":"中华人民共和国MN"
}'
