### ISSUE TITLE
请打一个：elasticsearch-analysis-ik   for  5.6.6 or  5.6.7版本的包，谢谢！

### ISSUE THREAD

**Issue by zusrsoft** [medcl/elasticsearch-analysis-ik#507]
请打一个：elasticsearch-analysis-ik   for  5.6.6 或5.6.7  版本的包，谢谢！
目前　IK　5.6.5的版本在 elasticsearch　5.6.6 或5.6.7中，无法加载与使用！

**Comment by sdhery** [comment]
不要改IK里面的配置文件就可以支持了吗

**Comment by zusrsoft** [comment]
版本对应上，默认就支持了

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.6.7
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v5.6.6
