### ISSUE TITLE
elasticsearch 已经 6.1.3

### ISSUE THREAD

**Issue by msongs** [medcl/elasticsearch-analysis-ik#508]
ik 无法使用了

**Comment by Jaggle** [comment]
同求6.1.3的，谢谢大佬

**Comment by Jaggle** [comment]
@msongs 我目前找到一个临时的解决办法：打开zip保，修改plugin-descriptor.properties，将版本号修改为6.1.3即可。

**Comment by R1hug0** [comment]
@medcl  M大大,6.2已出

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.1.3
