### ISSUE TITLE
Elasticsearch 6.2.1 安装 ik出错

### ISSUE THREAD

**Issue by negativelo** [medcl/elasticsearch-analysis-ik#514]
![qq 20180209155259](https://user-images.githubusercontent.com/4110994/36017141-5cc0f2a6-0db1-11e8-9cc1-cf4d6d6f9992.png)
请问，这个错误要怎么解决？

**Comment by negativelo** [comment]
已解决 删除 plugin-descriptor.properties 文件中  site、jvm、isolated的相关配置

[Help for plugin authors](https://www.elastic.co/guide/en/elasticsearch/plugins/6.2/plugin-authors.html)

**Comment by medcl** [comment]
谢谢
