### ISSUE TITLE
为什么分词时会把文本中单字全部分出来

### ISSUE THREAD

**Issue by xupengrun** [medcl/elasticsearch-analysis-ik#515]
你好，我使用ik分词时，得到如下结果，关键词会被分出来，但是文本中每个单字也会被分出来，导致搜索时会搜索出包含单字但不相关的内容。请问这是哪里出问题了？
Elasticsearch 2.4.1版本，ik 1.10.1版本
GET http://127.0.0.1:9200/_analyze?analyzer=ik&pretty=true&text=口服液/
{
"tokens": [
{
"token": "口服液",
"start_offset": 0,
"end_offset": 3,
"type": "CN_WORD",
"position": 0
}
,
{
"token": "口服",
"start_offset": 0,
"end_offset": 2,
"type": "CN_WORD",
"position": 1
}
,
{
"token": "口",
"start_offset": 0,
"end_offset": 1,
"type": "CN_WORD",
"position": 2
}
,
{
"token": "服",
"start_offset": 1,
"end_offset": 2,
"type": "CN_WORD",
"position": 3
}
,
{
"token": "液",
"start_offset": 2,
"end_offset": 3,
"type": "CN_WORD",
"position": 4
}
]
}

**Comment by charleslxh** [comment]
搜索时可以使用 `ik_smart` 提高精确度，索引时使用 `ik_max_word`。你也可以使用 `filter` 读分析出来的 `tokens` 进行过滤。分词本身不存在问题

**Comment by xupengrun** [comment]
多谢了，找到原因了，扩展词典的问题
