### ISSUE TITLE
求教IK分词问题 关于英文

### ISSUE THREAD

**Issue by feifeiiiiiiiiiii** [medcl/elasticsearch-analysis-ik#52]
IK支持纯英文分词么？ 还是需要有特别的配置？
目前在使用IK作为es的分词，测试纯英文句子，就全部返回了

**Comment by feifeiiiiiiiiiii** [comment]
我用es的_analyze?analyzer=ik测试句子 she a student in peking 结果如下  是用的es-ik的版本不对么，还是配置错误
```
{
    tokens: [
        {
            token: "she a student in peking",
            start_offset: 0,
            end_offset: 23,
            type: "ENGLISH",
            position: 1
        }
    ]
}
```

**Comment by sinhang** [comment]
> IK支持纯英文分词么？ 还是需要有特别的配置？
> 目前在使用IK作为es的分词，测试纯英文句子，就全部返回了

请问你处理了吗？

**Comment by frsweety** [comment]
> 我用es的_analyze?analyzer=ik测试句子 she a student in peking 结果如下 是用的es-ik的版本不对么，还是配置错误 版本是 elasticsearch-analysis-ik-1.2.8
> 
> ```
> {
>     tokens: [
>         {
>             token: "she a student in peking",
>             start_offset: 0,
>             end_offset: 23,
>             type: "ENGLISH",
>             position: 1
>         }
>     ]
> }
> ```
我7.2没问题
