### ISSUE TITLE
Elasticsearch 分词搜索 - 精确查找

### ISSUE THREAD

**Issue by llearn** [medcl/elasticsearch-analysis-ik#527]
怎么做到分词后更精确的搜索？
比如用户输入： 苹果手机
假如分词器分为： 苹果 手机
我想搜索文档中既包含苹果又包含手机的，而不是把包含苹果和包含手机的都搜索出来。
这个应该怎么做，感谢了。

**Comment by FieldSoft-HelloClyde** [comment]
搜的时候用粗粒度，并且将“苹果手机”加入词典

**Comment by wnjustdoit** [comment]
GET /index/type/_search
{
    "query": {
        "match": {
            "title": {
                "operator": "and",
                "query": "苹果手机 "
            }
        }
    }
}
