### ISSUE TITLE
想搜索出包含特殊符号的内容

### ISSUE THREAD

**Issue by ZhiqiangTao** [medcl/elasticsearch-analysis-ik#528]
比如我想搜索出文本里包含
“” ， , ? ？★☆★$ & ¤ § | °゜ ¨ ± · × ÷ ˇ ˉ ˊ ˋ ˙ Γ Δ Θ Ξ Π Σ Υ Φ Ψ Ω 
等等类似的特殊符号，该如何操作呢？请求帮助

**Comment by panfengfeng** [comment]
同问

**Comment by gpml119** [comment]
同问 连字符 -
