### ISSUE TITLE
加载不到自定义的词典

### ISSUE THREAD

**Issue by lwphk** [medcl/elasticsearch-analysis-ik#529]
![72d54fbe-a2c5-442f-a7da-07acefc97932](https://user-images.githubusercontent.com/16970646/37708973-a69a9bbe-2d43-11e8-884f-18dd51acff3a.png)

启动并没有生效啊? 扩展的dic 没有加载上,启动日志加载了配置文件 什么情况啊?

**Comment by salyfan** [comment]
使用UTF-8 无BOM编码格式

**Comment by lwphk** [comment]
现在换了个版本可以加载了
