### ISSUE TITLE
关于remote_ext_dic实现动态更新词库的功能

### ISSUE THREAD

**Issue by rockybean** [medcl/elasticsearch-analysis-ik#54]
请问  remote_ext_dic 配置是否已经生产环境可以上了？ 没有找到说明文档，我简单看了下源码，发现就是一个head和get的http请求，是不是自己实现掉就可以用了？

**Comment by node** [comment]
1.4开始就可以了， 当然你也可以自己实现，一样的；  重点就是调用 reload dict的方法。
