### ISSUE TITLE
6.3.0什么时候会出来呢？

### ISSUE THREAD

**Issue by jokeyone** [medcl/elasticsearch-analysis-ik#557]

**Comment by dandanlee** [comment]
自己都可以弄。改个版本号即可，不要只是做伸手人吧。

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.3.0

**Comment by jokeyone** [comment]
[elk@centos7 elasticsearch]$ bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-analysis-ik-6.3.0.zip
-> Downloading https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v6.3.0/elasticsearch-analysis-ik-6.3.0.zip
[=================================================] 100%   
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch"
