### ISSUE TITLE
ik 6.3.0 ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

### ISSUE THREAD

**Issue by masteranthoneyd** [medcl/elasticsearch-analysis-ik#558]
使用官方es 6.3.0 版本安装 ik 6.3.0 报错：
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

大神们这个怎么解决。。。

**Comment by medcl** [comment]
再试试

**Comment by masteranthoneyd** [comment]
ok了， awesome
