### ISSUE TITLE
spring boot2.x 集成elasticsearch 无法加载 elasticsearch-analysis-ik分词器

### ISSUE THREAD

**Issue by ft0907** [medcl/elasticsearch-analysis-ik#562]
`@Getter
@Setter
@Document(indexName = "contenttag", type = "tag")
public class ContentTagEs {

	@Id
	private String id;

	@Field(type = FieldType.Text, searchAnalyzer = "ik_max_word", analyzer = "ik_max_word")
	private String title;

}`

spring boot 2.0.2 
spring data elasticsearch 3.0.6

使用docker部署
es服务器  5.5.3
elasticsearch-analysis-ik 5.5.3

使用9200端口测试分词没有问题， 但是使用spring data 集成时 只要使用 searchAnalyzer或 analyzer 注解就无法生成mapping 

控制台错误如下：
failed to load elasticsearch nodes: org.elasticsearch.index.mapper.MapperParsingException: Mapping definition for [title] has unsupported parameters: searchAnalyzer [ik_max_word] not found for field 

尝试使用的配置文件mapping.json 没有问题，然后更换了ansj分词插件也可以正常运行。 对于安装ik插件后 spring data 无法加载到这个插件，作者@Medcl是否有好的解决方法？

**Comment by iambluseli** [comment]
我同样遇到这个问题，请问你有什么好的解决办法了吗？
