### ISSUE TITLE
你好，关于安装 IK 遇到的问题，求解答

### ISSUE THREAD

**Issue by PoplarDddCN** [medcl/elasticsearch-analysis-ik#57]
**使用 mvn package 暴错了，能说下原因吗？**

[root@poplar elasticsearch-analysis-ik-master]# **mvn package**
**/usr/java/jdk1.7.0_65**
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.elasticsearch:elasticsearch-analysis-ik:1.2.9 (/tmp/elasticsearch-analysis-ik-master/pom.xml) has 1 error
[ERROR]     Non-parseable POM /root/.m2/repository/org/sonatype/oss/oss-parent/7/oss-parent-7.pom: Expected root element 'project' but found 'html' (position: START_TAG seen <html>... @1:6)  @ /root/.m2/repository/org/sonatype/oss/oss-parent/7/oss-parent-7.pom, line 1, column 6 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

**提示pom解析异常，我是这样安装IK的**

wget https://github.com/medcl/elasticsearch-analysis-ik/archive/master.zip
unzip master.zip
cd elasticsearch-analysis-ik/
mvn package

pom.xml里的内容只修改了jdk版本，我改成了1.7，发现包错，又改回成1.6还是包错啊，求安装方法，谢谢

**我安装的maven版本：**

[root@poplar elasticsearch-analysis-ik-master]# mvn -v
/usr/java/jdk1.7.0_65
**Apache Maven 3.0.4** (rNON-CANONICAL_2013-04-08_07-49_mockbuild; 2013-04-08 15:49:58+0800)
Maven home: /usr/share/maven
Java version: 1.7.0_65, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_65/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "3.9.10-100.fc17.x86_64", arch: "amd64", family: "unix"

**Comment by medcl** [comment]
应该是你的maven环境问题,如果是es1.6.0, 可直接下载  https://github.com/medcl/elasticsearch-rtf/tree/1.6.0

**Comment by iranw** [comment]
这个是因为安装的meaven版本不对 不能安装meaven2
如果安装了 一定要卸载干净并重新安装meaven
apt-get remove meaven2
apt-get remove autoremove
rm -rf ~/.m2
