### ISSUE TITLE
null_pointer_exception

### ISSUE THREAD

**Issue by javahokky** [medcl/elasticsearch-analysis-ik#579]
使用elasticsearch-plugin安装，es和ik版本一致，分别试了5.5.2，5.6.8，都出现这个问题，请问大家有遇到过吗？
![qq 20180728171053](https://user-images.githubusercontent.com/20985919/43355192-d7860bf8-928a-11e8-9d93-fa896c5217eb.png)
![qq 20180728171114](https://user-images.githubusercontent.com/20985919/43355193-de820150-928a-11e8-918a-7333860abeb9.png)

**Comment by chentaikuang** [comment]
加远程词库有这问题，解决了吗？

**Comment by vearne** [comment]
> 加远程词库有这问题，解决了吗？

解决了，最后发现是JAVA的安全机制，禁止了对远程地址的访问

**Comment by vearne** [comment]
大致可以参考这篇文章， https://blog.yourtion.com/java-access-denied-socketpermission-solution.html 修改 /jre/lib/security/java.policy
添加         permission java.net.SocketPermission "*:*", "accept,connect,resolve";
允许访问外部任意端口
