### ISSUE TITLE
关于 ik use_smart 的疑问

### ISSUE THREAD

**Issue by zhutf123** [medcl/elasticsearch-analysis-ik#59]
index:
  analysis:
    analyzer:
      ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true
index.analysis.analyzer.default.type: ik

es 版本: 1.4.0 插件版本 1.2.9

我已经在 elasticsearch.yml 中配置了如上信息, 为什么  分词之后的结果 还是

输入的为 :    北京一日游

{

    "tokens": 

[

{

    "token": "北京",
    "start_offset": 0,
    "end_offset": 2,
    "type": "CN_WORD",
    "position": 1

},
{

    "token": "京",
    "start_offset": 1,
    "end_offset": 2,
    "type": "CN_WORD",
    "position": 2

},
{

    "token": "一日游",
    "start_offset": 2,
    "end_offset": 5,
    "type": "CN_WORD",
    "position": 3

},
{

    "token": "一日",
    "start_offset": 2,
    "end_offset": 4,
    "type": "CN_WORD",
    "position": 4

},
{

    "token": "一",
    "start_offset": 2,
    "end_offset": 3,
    "type": "TYPE_CNUM",
    "position": 5

},
{

    "token": "日",
    "start_offset": 3,
    "end_offset": 4,
    "type": "COUNT",
    "position": 6

},

        {
            "token": "游",
            "start_offset": 4,
            "end_offset": 5,
            "type": "CN_WORD",
            "position": 7
        }
    ]

}

**Comment by medcl** [comment]
具体的analyze请求发一下看看

**Comment by medcl** [comment]
@zhutf123 这个很久了，应该是使用的问题，如果有问题再重新打开吧
