### ISSUE TITLE
升级6.4.0

### ISSUE THREAD

**Issue by dreamingo88** [medcl/elasticsearch-analysis-ik#590]
es 6.4.0发布了，是否有计划升级支持呢？

**Comment by tolbkni** [comment]
看了下，已经发布了 https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.4.0

**Comment by Krocsky** [comment]
解决了
`bin/elasticsearch-plugin install -b ingest-attachment`，install 加参数--batch或者-b
