### ISSUE TITLE
分词错误，自定义词典没有起作用，为何啊？

### ISSUE THREAD

**Issue by NikolaDai** [medcl/elasticsearch-analysis-ik#594]
http://localhost:9200/_analyze/  POST
{"analyzer":"ik_smart","text":"集团军某旅"}
结果如下：
{
"tokens": [
{
"token": "集团",
"start_offset": 0,
"end_offset": 2,
"type": "CN_WORD",
"position": 0
}
,
{
"token": "军某旅",
"start_offset": 2,
"end_offset": 5,
"type": "CN_WORD",
"position": 1
}
]
}
关键是我把集团军和某旅都为自定义词库，还是不行，请曾老师指点！万分感谢！！

**Comment by primewang** [comment]
自定义词典中有部分分词没生效，有遇到过没？
