### ISSUE TITLE
ubuntu 6.4.1 plugin-descriptor.properties

### ISSUE THREAD

**Issue by jttttttttttttt** [medcl/elasticsearch-analysis-ik#595]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Could not load plugin descriptor for plugin directory [elasticsearch-analysis-ik-6.4.1]
Caused by: java.nio.file.NoSuchFileException: /usr/share/elasticsearch/plugins/elasticsearch-analysis-ik-6.4.1/plugin-descriptor.properties

**Comment by gzb001** [comment]
me too,but my Version is 7.1.0

**Comment by elv1sZqy** [comment]
me too,but my Version is 6.8.6

**Comment by medcl** [comment]
插件是怎么安装的?
