### ISSUE TITLE
版本不匹配

### ISSUE THREAD

**Issue by liangjzhang** [medcl/elasticsearch-analysis-ik#597]
elasticsearch 6.4.2，但IK插件最新版依旧是6.4.1，大概什么时候会有更新

**Comment by Chenhonli** [comment]
elastic search 6.4.2 能用6.4.1中文分词吗？

**Comment by liangjzhang** [comment]
> elastic search 6.4.2 能用6.4.1中文分词吗？

不能

**Comment by medcl** [comment]
已更新
