### ISSUE TITLE
请问使用IK定义index的时候，filter里面的type是什么,还请大神给指点。

### ISSUE THREAD

**Issue by yutaolife** [medcl/elasticsearch-analysis-ik#605]
大神您好，我现在遇到了一个问题，我们使用 ik , pinyin和同义词。在做搜索，但是我们在定义index的时候，需要满足一些条件：
1， 当输入中文或者字母混合的时候， 我们想启动，**ik_smart**，**pinyin**，**同义词**
2，当输入中文或者字母混合的时候， 我们想启动，**ik_max_word**，**pinyin**，**同义词**
3，当输入字母的时候的时候， 我们想启动， pinyin, 同义词, 英文

所以，我们在定义index的时候，如下：
`
PUT /test
{
  "settings": {
    "number_of_replicas": 0,
    "number_of_shards": 1,
    "index": {
      "analysis": {
        "analyzer": {
          "ik_pinyin_analyzer_smart": {
            "type": "custom",
            "tokenizer": "ik_smart",
            "filter": [
              "index_pinyin",
              "smart_filter",
              "my_synonym_filter"
            ]
          },
          "ik_pinyin_analyzer_max_word": {
            "type": "custom",
            "tokenizer": "ik_max_word",
            "filter": [
              "index_pinyin",
              "max_filter",
              "my_synonym_filter"
            ]
          },
          "pinyin_analyzer": {
            "tokenizer": "my_pinyin"
            
          }
        },
        "tokenizer": {
          "my_pinyin": {
            "type": "pinyin",
            "keep_separate_first_letter": false,
            "keep_full_pinyin": true,
            "keep_original": true,
            "limit_first_letter_length": 16,
            "lowercase": true,
            "remove_duplicated_term": true
          }
        },
        "filter": {
          "index_pinyin": {
            "keep_original": true,
            "keep_joined_full_pinyin": true,
            "type": "pinyin",
            "term_vector": "with_positions_offsets"
          },
          "my_synonym_filter": {
            "type": "synonym",
            "synonyms_path": "analysis-ik/config/synonyms.txt"
          },
          "smart_filter":{
            "type":"text", **????**
            "analyzer":"ik_pinyin_analyzer_smart"
          },
          "max_filter":{
            "type":"text", **????**
            "analyzer":"ik_pinyin_analyzer_max_word"
          }
        }
      }
    }

  }
}
`

但是我们发现一个问题：
index filter里面的type， 我们要写什么值呢？
现在elasticsearch返回给我们的错误是 filter type不存在，我们写text也不对，可是官方也没有别的，不像是pinyin 
找了一圈也没有找到。

还请大神给指点。

**Comment by yutaolife** [comment]
问题的 问法不对，而且思路也不对 

所以 关闭

**Comment by sinhang** [comment]
> 问题的 问法不对，而且思路也不对
> 
> 所以 关闭

请问你后面是怎么处理的呢？
