### ISSUE TITLE
Can I use ik dictionary to set which words to be splited?

### ISSUE THREAD

**Issue by developerlicw** [medcl/elasticsearch-analysis-ik#611]
Hello, I am using elasticsearch5 + ik_smart analyzer.
In ik plugin, I set my own dictionary for words which are not expected to be splitted, say brands, company names etc.
And now, I wonder whether I can use dictionary to set words which are expected to be splitted.

For example:
"复印纸" is a keyword that not splitted with ik_smart default settings.
But I hope it can be splitted to "复印" and "纸" because sometimes user may not always search for the whole word, so I hope my search engine can hit for both "copy" and "paper".

When I was using solr, it can realize this by setting "复印" to dictionary, so that "复印纸" will be splitted. But as I tried with ik analyzer, it doesn't seem to work.

Could you please tell me whether ik has this feature? If yes, how can I do that?
Thanks and best wishes, looking for your response.

**Comment by panfengfeng** [comment]
you can add "复印" and "纸" into the dictionary (extra_main.dic), and then add the extra_main.dic into the IKAnalyzer.cfg.xml

**Comment by developerlicw** [comment]
Hi panfengfeng,

Thanks for the reply.
But since we considered adding too many words to dict may cause other problems, we are now trying to figure another way to do it. Thanks anyway :)
