### ISSUE TITLE
请问自定义扩展词典能否指定多个词典文件

### ISSUE THREAD

**Issue by guhanjie** [medcl/elasticsearch-analysis-ik#62]
请问自定义扩展词典能否指定多个词典文件？如：
<entry key="ext_dict">custom/mydict.dic</entry> 
         
        <entry key="ext_stopwords">custom/ext_stopword.dic, ...
</entry>

**Comment by medcl** [comment]
; 分割

**Comment by guhanjie** [comment]
感谢Medcl，源码写得很清楚了，自己太懒没来得及看，所有的扩展字典配置都可以用;分割。
请参见org.wltea.analyzer.cfg.Configuration类。大致如下：
public  List<String> getExtDictionarys(){
		List<String> extDictFiles = new ArrayList<String>(2);
		String extDictCfg = props.getProperty(EXT_DICT);
		if(extDictCfg != null){

			String[] filePaths = extDictCfg.split(";");
			if(filePaths != null){
				for(String filePath : filePaths){
					if(filePath != null && !"".equals(filePath.trim())){
                        File file=new File("ik",filePath.trim());
						extDictFiles.add(file.toString());

					}
				}
			}
		}		
		return extDictFiles;		
	}
