### ISSUE TITLE
es6.5+ik6.5 分词失败 

### ISSUE THREAD

**Issue by jccgjccg** [medcl/elasticsearch-analysis-ik#622]
http://localhost:9200/_analyze/?analyzer=ik_smart&text=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD%E5%9B%BD%E6%AD%8C

{"error":{"root_cause":[{"type":"parse_exception","reason":"request body or source parameter is required"}],"type":"parse_exception","reason":"request body or source parameter is required"},"status":400}

**Comment by wushuaiping** [comment]
同样的问题

**Comment by wushuaiping** [comment]
request:  http://118.24.114.73:9200/_analyze?analyzer=ik_smart&pretty=true&text=%E6%88%91%E6%98%AF%E7%A8%8B%E5%BA%8F%E5%91%98

result:
{
error: - {
root_cause: - [
- {
type: "parse_exception",
reason: "request body or source parameter is required"
}
],
type: "parse_exception",
reason: "request body or source parameter is required"
},
status: 400
}

**Comment by kaiiak** [comment]
```shell
curl -X POST \
  http://127.0.0.1:9200/_analyze \
  -H 'content-type: application/json' \
  -d '{
  "analyzer" : "ik_smart",
  "text" : "中华人民共和国国歌"
}
'
```
@jccgjccg @wushuaiping

**Comment by medcl** [comment]
恩，analyze语法更新了

**Comment by jccgjccg** [comment]
> 
> 
> ```shell
> curl -X POST \
>   http://127.0.0.1:9200/_analyze \
>   -H 'content-type: application/json' \
>   -d '{
>   "analyzer" : "ik_smart",
>   "text" : "中华人民共和国国歌"
> }
> '
> ```
> 
> @jccgjccg @wushuaiping

3Q
