### ISSUE TITLE
中文人名匹配问题

### ISSUE THREAD

**Issue by delaz** [medcl/elasticsearch-analysis-ik#63]
我的index有个人名字段, 想精确匹配名字, 但是用ik分词匹配不到 比如陈赫, 对name字段用term 陈是可以搜到, 用term陈赫就搜不到了

**Comment by rockybean** [comment]
分词问题，你可以试试看 陈赫 用ik的分词结果，估计没有 陈赫这个term

**Comment by medcl** [comment]
分词不能完全解决问题的，用普通的querystring查询，operator使用AND

**Comment by legatoo** [comment]
不要 analyse， 直接 term
