### ISSUE TITLE
JDK11 运行报错，Option UseConcMarkSweepGC was deprecated in version 9.0

### ISSUE THREAD

**Issue by mofee** [medcl/elasticsearch-analysis-ik#645]
ES6.5 已经可以支持 JDK11，但是IK好像不支持，报：
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 a...release
是否有打算支持JDK11，如果有是否有时间表？

**Comment by blueboz** [comment]
--XX:+UseG1GC
