### ISSUE TITLE
ik与elastic synonym共用问题

### ISSUE THREAD

**Issue by ishare** [medcl/elasticsearch-analysis-ik#65]
问题1：发现按照说明配置的ik无法与synonym共用，配置如下，是什么原因呢？
ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
filter: [synonym]

问题2：在elasticsearch.yml里配置的`index.analysis.analyzer.default.type: ik` 不会使用配置的：
index:
analysis:
analyzer:
ik:
type: org.elasticsearch.index.analysis.IkAnalyzerProvider
alias: [ik_analyzer]
tokenizer: ik
filter: [synonym]

**Comment by ishare** [comment]
另外，ik有提供直接加载 拼音转换 配置或接口么？

**Comment by changx** [comment]
你需要定义自己的 analyzer, 用 ik 做 tokenizer，加上 synonym filter

**Comment by medcl** [comment]
参见 #93
