### ISSUE TITLE
ik什么时候开始支持es6.6版本呢？

### ISSUE THREAD

**Issue by miaoyukai** [medcl/elasticsearch-analysis-ik#651]
装了包，但是报错
 Plugin [analysis-ik] was built for Elasticsearch version 6.5.0 but version 6.6.0 is running
啥时候开始支持嘞。坐等

**Comment by shamrockzhao** [comment]
是的。啥时候能支持6.6。跪求。

**Comment by medcl** [comment]
早就放上去了啊，https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.6.0

**Comment by miaoyukai** [comment]
> 早就放上去了啊，[https：//github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.6.0](https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.6.0)

用了链接里面的

**Comment by miaoyukai** [comment]
> 早就放上去了啊，https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.6.0

用了但是报错，好像支持的是6.5
was built for Elasticsearch version 6.5.0 but version 6.6.1 is running

**Comment by miaoyukai** [comment]
> 早就放上去了啊，https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.6.0

下载的包名称是6.6但是mvn构建好之后就变成了6.5
![v md2 x x5my4ow9ia_lx0](https://user-images.githubusercontent.com/38027640/54010390-92d19d00-41a9-11e9-9abd-c83af54e0eed.png)
![image](https://user-images.githubusercontent.com/38027640/54010414-a7ae3080-41a9-11e9-938f-05210a187a03.png)

**Comment by medcl** [comment]
自己构建要自己改版本，要么直接下载打包好的。

**Comment by miaoyukai** [comment]
> 自己构建要自己改版本，要么直接下载打包好的。

哦哦收到，用的你们打好的包
