### ISSUE TITLE
es 6.4.2使用ik_max_word和word_delimiter报错

### ISSUE THREAD

**Issue by LaEmma** [medcl/elasticsearch-analysis-ik#652]
es 6.4.2使用ik_max_word和word_delimiter报错
    下面是索引部分内容
    "tokenizer" : "ik_max_word",
    "filter" : ["word_delimiter", "stop_filter", "synonym"]

    "word_delimiter": {
            "type": "word_delimiter",
            "split_on_numerics": true
      }

报错信息为
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=11,endOffset=16,lastStartOffset=16 for field 'search_attr'"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=11,endOffset=16,lastStartOffset=16 for field 'search_attr'"
  },
  "status": 400
}

tokenizer 用ik_smart就没问题

**Comment by medcl** [comment]
新的 Lucene 对于位置的校验变得严格，max_word分词模式会产生位置的重叠

**Comment by scfw** [comment]
这个问题能解决吗？还是说从max_word的原理上就无法解决？

**Comment by medcl** [comment]
原理上无法解决，除非忽略位置的处理，但是高亮就会出问题

**Comment by scfw** [comment]
看来也只能试试别的插件了

**Comment by DavinBin** [comment]
这个问题你解决了吗？
