### ISSUE TITLE
Plugin [analysis-ik] was built for Elasticsearch version 6.6.0 but version 6.6.1 is running

### ISSUE THREAD

**Issue by soooooolazy** [medcl/elasticsearch-analysis-ik#655]
When will we can use ik 6.6.1?

**Comment by RichieCN** [comment]
{
  "name" : "node-1",
  "cluster_name" : "my-es",
  "cluster_uuid" : "1alnmFL5SU-J4ocXncHwCA",
  "version" : {
    "number" : "6.6.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "a9861f4",
    "build_date" : "2019-01-24T11:27:09.439740Z",
    "build_snapshot" : false,
    "lucene_version" : "7.6.0",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
I have the same problem as you, and my solution is：
You need to upgrade your lucene version to 7.6.0 to solve this problem

**Comment by code-hi** [comment]
我也是同样问题，换成了6.6.0版本

**Comment by xs1031893936** [comment]
可以尝试修改 ik目录中的plugin-descriptor.properties文件

**Comment by liyifan687** [comment]
homebrew铁憨憨，二楼说的lucene_version本来不就是7.6.0？

**Comment by liyifan687** [comment]
> 可以尝试修改ik目录中的plugin-descriptor.properties文件
> 修改其中的版本为6.6.1，有两处需要修改。
> 
> 能够运行，但我不确定这样做是否会有隐患

又不是不能用.jpg

**Comment by medcl** [comment]
是可以的。
