### ISSUE TITLE
6.6.0版本通过mvn打包生成的target/releases/压缩包是6.5.0版本的

### ISSUE THREAD

**Issue by code-hi** [medcl/elasticsearch-analysis-ik#656]
6.6.0版本通过mvn打包生成了target/releases/elasticsearch-analysis-ik-6.5.0.zip的压缩包，经过好多次测试都是一样。通过查看pom.xml里面elasticsearch.version显示为6.5.0，手动修改为6.6.0之后打包出来的就是正确的。不知道是一个bug还是我这边操作不当造成的。还请麻烦看一下

**Comment by iridescentcandy** [comment]
我手动修改了但是mvn打包失败

**Comment by medcl** [comment]
不用修改，直接打包的时候，传参数就可以了：
```
clean package -Delasticsearch.version=6.6.0
```

**Comment by iridescentcandy** [comment]
> 
> 
> 不用修改，直接打包的时候，传参数就可以了：
> 
> ```
> clean package -Delasticsearch.version=6.6.0

我换了旧版本，依然感谢你
