### ISSUE TITLE
ik插件的动态加载词典，无需重启ES的功能支持情况

### ISSUE THREAD

**Issue by zhangwei17** [medcl/elasticsearch-analysis-ik#66]
当前我用的有两个版本的ES，1.3.4和1.5.1，对应用的ik插件是1.2.6和1.2.9.
最近发现ik插件的一个配置有问题，需要进行修复。在新版本里，直接更新配置文件后就生效,但是旧版本里弄了一台机器试了下，并不生效。
所以想知道，是所有版本的ik插件都支持自动热加载插件配置与词典吗？还是特定版本的支持？还是和使用的ES版本有关？如果和ES或者ik的版本有关，是从哪个版本开始支持的呢？

**Comment by lephix** [comment]
同问， 也请问，我直接更新服务器上的词库，需要重启ES服务器吗？

**Comment by medcl** [comment]
直接更新服务器上面的词库,需要重启服务器

**Comment by okuc** [comment]
同问，用户自定义词典添加词后，是否能自动加载？那个版本开始支持？

**Comment by victorylu123** [comment]
词库更新热加载功能现在版本支持了吗？

**Comment by medcl** [comment]
来自社区的贡献，最新的版本已经有支持
