### ISSUE TITLE
关于startOffset must be non-negative的报错

### ISSUE THREAD

**Issue by scfw** [medcl/elasticsearch-analysis-ik#662]
在我自己的环境下测试，pengcong90的提交导致了startOffset must be non-negative的报错，不知道是个案还是确实有bug

**Comment by BigBrother5** [comment]
同遇到这个问题！

**Comment by BigBrother5** [comment]
在索引“得饶人处且饶人”时候会遇到

**Comment by foqq** [comment]
text: "黎明前的黑暗"
analyzer: "ik_max_word",
search_analyzer: "ik_max_word"
exception:
"startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=2,endOffset=3,lastStartOffset=3 for field 'description'"

**Comment by Cosin** [comment]
@foqq @BigBrother5 两位真是巧了，我也碰到了这问题，并且文本都是一样的：

1. 得饶人处且饶人
2. 黎明前的黑暗
3. 宝剑锋从磨砺出

经测试，只在6.7.0、6.7.1上存在此bug，且只存在于ik_max_word模式，ik_smart也没有，之前和之后的版本都没有

@medcl 我听朋友说您之前已经解决了此bug，能否再看看？

**Comment by levylll** [comment]
同遇到，版本是6.7.1 希望 @medcl  早日修复一下，多谢了！

**Comment by levylll** [comment]
看到medcl 在别的贴说似乎是无法解决的。。。sad
https://github.com/medcl/elasticsearch-analysis-ik/issues/652#issuecomment-477600224
或许得版本回退一下啊。。。。

**Comment by scfw** [comment]
目前我是这么解决的：把pengcong90提交的代码注释掉，重新打包，一切都安静了。

**Comment by scfw** [comment]
从原理上是无法解决，但是有些报错可能是pengcong90提交的那部分代码引起的。具体原因自己测试一下就明确了

**Comment by medcl** [comment]
谁来帮忙提交个 PR，谢谢，我忙晕了要。

**Comment by dotNetDR** [comment]
刚在阿里云开了台测试的elasticsearch 6.7.0正好踩中此坑~~~

```
PUT test?include_type_name=false
{
  "mappings": {
    "dynamic": "strict",
    "properties": {
      "content": {
        "type": "text",
        "term_vector": "with_positions_offsets",
        "analyzer": "ik_max_word"
      }
    }
  },
  "settings": {
    "index": {
      "number_of_shards": "1",
      "number_of_replicas": "1"
    }
  }
}

PUT test/_doc/1
{
  "content": "机关算尽太聪明"
}

----
{
  "error": {
    "root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=2,endOffset=3,lastStartOffset=4 for field 'content'"
      }
    ],
    "type": "illegal_argument_exception",
    "reason": "startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=2,endOffset=3,lastStartOffset=4 for field 'content'"
  },
  "status": 400
}
```

**Comment by douniwan5788** [comment]
最新的7.0.0 也有这个问题
黎明前的黑暗
java.lang.IllegalArgumentException: startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOff
set=2,endOffset=3,lastStartOffset=3

**Comment by scfw** [comment]
看一下7.0之后的提交，已经把注释提交上去了，只是还没有发布release

**Comment by vistart** [comment]
@scfw 7.0.1 已经发布了，是否解决了此问题呢？

**Comment by medcl** [comment]
麻烦最新版本帮忙测一下

**Comment by douniwan5788** [comment]
> 麻烦最新版本帮忙测一下

好像是可以了，不过又要reindex了……

**Comment by czhcc** [comment]
我用的是6.8.0，有解决的办法吗？

**Comment by IDrinkMoreWater** [comment]
我也碰到类似问题，好烦恼，用的6.8.2

**Comment by sinboun** [comment]
6.8.1也有同样的问题，麻烦有解决办法吗

**Comment by dotNetDR** [comment]
看了代码，修复是从[7.0.0](https://github.com/medcl/elasticsearch-analysis-ik/blob/v7.0.0/src/main/java/org/wltea/analyzer/core/AnalyzeContext.java#L271)开始的
bug代码是从[6.7.0](https://github.com/medcl/elasticsearch-analysis-ik/blob/v6.7.0/src/main/java/org/wltea/analyzer/core/AnalyzeContext.java#L271)引进的，影响一直持续到[6.8.4](https://github.com/medcl/elasticsearch-analysis-ik/blob/v6.8.4/src/main/java/org/wltea/analyzer/core/AnalyzeContext.java#L271)

**Comment by bmnnmb** [comment]
startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=16,endOffset=17,lastStartOffset=17 for field 'remark'
版本 ES 跟 ik 都是6.8.11，关键词是“黎明前的黑暗”，还是出现了同样的错误，尴尬了，尝试回退到6.6.1试试

**Comment by aveyuan** [comment]
目前版本7.7 依然有这个问题...

**Comment by dotNetDR** [comment]
自己把
`/src/main/java/org/wltea/analyzer/core/AnalyzeContext.java`
271行注释掉（参考：[7.0.0](https://github.com/medcl/elasticsearch-analysis-ik/blob/v7.0.0/src/main/java/org/wltea/analyzer/core/AnalyzeContext.java#L271)）
```
                                        int innerIndex = index + 1;
					for (; innerIndex < index + l.getLength(); innerIndex++) {
						Lexeme innerL = path.peekFirst();
						if (innerL != null && innerIndex == innerL.getBegin()) {
							this.outputSingleCJK(innerIndex - 1);
						}
					}
```
然后重新编译一个ik出来，再安装进去就能解决了。

编译的前记得把`/src/main/resources/plugin-descriptor.properties`
```
elasticsearch.version=<你的es版本>
```
如：
```
elasticsearch.version=6.8.6
```

**Comment by yanghanxy** [comment]
@medcl 您好，
我这边用 6.X branch 的代码也遇到了这个问题，
看了下 6.X branch 的 commit 记录，是[最后一个 commit](https://github.com/medcl/elasticsearch-analysis-ik/commit/125ac3c5e5e66bdb31a75cd43719925c35193917) 引入的这个问题，也一直没有修复。
是不是可以 revert [这个 commit](https://github.com/medcl/elasticsearch-analysis-ik/commit/125ac3c5e5e66bdb31a75cd43719925c35193917)，以免影响更多使用 6.X branch 的人。谢谢！

**Comment by yanghanxy** [comment]
想了一种修复方法， @medcl 帮忙评估一下，谢谢：
https://github.com/medcl/elasticsearch-analysis-ik/pull/835

**Comment by pfsan** [comment]
请问6.7.2的版本页出现了此问题该怎么解决呢？

**Comment by medcl** [comment]
已 revert
