### ISSUE TITLE
如何控制切词粒度

### ISSUE THREAD

**Issue by wuxudong** [medcl/elasticsearch-analysis-ik#67]
比如用缺省字典搜索 海天酱油， 切词的结果是：海天 酱油 酱 油  ，这样会使得带 油 这个字的都出现在搜索结果中，怎样控制只匹配 海天 酱油 ，而忽略所有单个字的切词结果？谢谢

**Comment by avastms** [comment]
默认是最细粒度匹配，你把smart选项打开就行了

**Comment by thm1118** [comment]
当 在索引 setting里配置：
 "settings": {
      "number_of_shards": "1",
      "number_of_replicas": "1",
      "analysis": {
        "filter": {
          "my_synonym_filter": {
            "type": "synonym",
            "synonyms_path": "ik/custom/synonyms.dic"
          }
        },
        "analyzer": {
          "default_index": {
            "tokenizer": "ik"
          },
          "default_search": {
            "tokenizer": "ik",
            "filter": [
              "my_synonym_filter",
              "lowercase",
              "stop"
            ]
          }
        }
      }
这样是没有问题。
但是如果这样开启smart：
"analyzer": {
          "default_index": {
            "tokenizer": "ik_smart"
          },
          "default_search": {
            "tokenizer": "ik_smart",
es就会报 没有ik_smart 这样的分词器。  es自身yml配置文件按照指南里面配置了。 查询的时候使用_analyze?analyzer=ik_smart 也能生效，应该说明能够识别到ik_smart，但是创建索引的时候为什么不能识别ik_smart , 望大神指教

**Comment by avastms** [comment]
@thm1118 在ES里面analyzer和tokenizer是两个东西，你看你参数analyzer=ik_smart，说明有ik_smart 这个analyzer， 但在配置文件里你是指定tokenizer， 
但是并没有ik_smart这个tokenizer，所以你挂了。
着急用的话可以先用我fork的源，我做了点修改，ik, ik_smart， ik_max_word 我都在java代码里向ES分别注册了analyzer和tokenizer。

**Comment by thm1118** [comment]
感谢大神火速解惑。
这个 “我fork的源”不明白啊，elasticsearch-analysis-ik 就是您的啊

**Comment by thm1118** [comment]
我来补个avastms 大神的fork地址：https://github.com/avastms/elasticsearch-analysis-ik.git
大神赶紧发起pull，我先拉下来build

**Comment by changx** [comment]
@avastms   

在配置文件里把 tokenizer type 指定为 ik 就可以了，不用单独注册 tokenizer

```
tokenizer:
   ik_tok:
      type: ik
      use_smart: true
```

**Comment by medcl** [comment]
1.5之后不用单独配置也能用了

**Comment by wudanfeng81** [comment]
21年了，不知道楼主有没有解决这个问题，我也遇到了相同的问题
