### ISSUE TITLE
Multiple nodes with ik plugin

### ISSUE THREAD

**Issue by hackerwin7** [medcl/elasticsearch-analysis-ik#670]
Single node with two elastic instances:

first node use `config` dir, second use `config-1` dir

After following the installation guide, I find only first node have plugin config dir in `{elastic}/config/analysis-ik/`, the second node have no such dir in `{elastic}/config-1/analysis-ik/`,

this lead to second node logs err:
```
java.io.FileNotFoundException: elasticsearch-7.0.0/config-1/analysis-ik/IKAnalyzer.cfg.xml (No such file or directory)
```

**Comment by medcl** [comment]
`config` and `config-1` should be same.
