### ISSUE TITLE
自定义词典扩展使用问题 基于es6.7.0对应版本调整

### ISSUE THREAD

**Issue by jihaiyu** [medcl/elasticsearch-analysis-ik#674]
![image](https://user-images.githubusercontent.com/18650742/56890498-2ccc0c80-6aac-11e9-9e2a-e39a76ded7f8.png)

这里面可以设置多个IkTokenizerFactory加载进去么，用key作为区分字典的参数去获取远程字典，
创建Dictionary时候不使用单利的方式，然后根据laws_regulations::ik_smart 这个值的前半部分作为一个实例的key，每次保障这个key的字典是单利的，线程池部分也和key保持一致，分别去加载自己的自定义远程字典，用于热更新字典库，以上部分都已经改造完成，但是最后发现无法按照自己想要的结果，每次给对应的分词库加分词后，大家都能看到对方的分词，没有实现隔离的效果，希望大佬能给予新的思路~~

![image](https://user-images.githubusercontent.com/18650742/56890834-2f7b3180-6aad-11e9-8d10-97aea0e55007.png)

![image](https://user-images.githubusercontent.com/18650742/56890928-69e4ce80-6aad-11e9-8f25-8c9e6ddfebab.png)

![image](https://user-images.githubusercontent.com/18650742/56890977-8a148d80-6aad-11e9-8883-5978e09dd8b7.png)
![image](https://user-images.githubusercontent.com/18650742/56890992-94cf2280-6aad-11e9-80d7-78c5fd6c8c9e.png)

![image](https://user-images.githubusercontent.com/18650742/56891027-b16b5a80-6aad-11e9-84ff-65c14b9d561e.png)

![image](https://user-images.githubusercontent.com/18650742/56891012-a6b0c580-6aad-11e9-9841-08237c42aade.png)

**Comment by jihaiyu** [comment]
大佬们求围观，求支持~~

**Comment by jihaiyu** [comment]
@medcl 大神、大神快快来~~

**Comment by jihaiyu** [comment]
@medcl 大神大神，快快来哦。

**Comment by medcl** [comment]
词典加载的时候可以都加载进来，读取的时候再根据用户来进行选择

**Comment by auzn1025** [comment]
hi，medcl，这个问题现在能够实现索引级别加载词库不？

**Comment by auzn1025** [comment]
> ![image](https://user-images.githubusercontent.com/18650742/56890498-2ccc0c80-6aac-11e9-9e2a-e39a76ded7f8.png)
> 
> 这里面可以设置多个IkTokenizerFactory加载进去么，用key作为区分字典的参数去获取远程字典，
> 创建Dictionary时候不使用单利的方式，然后根据laws_regulations::ik_smart 这个值的前半部分作为一个实例的key，每次保障这个key的字典是单利的，线程池部分也和key保持一致，分别去加载自己的自定义远程字典，用于热更新字典库，以上部分都已经改造完成，但是最后发现无法按照自己想要的结果，每次给对应的分词库加分词后，大家都能看到对方的分词，没有实现隔离的效果，希望大佬能给予新的思路~~
> 
> ![image](https://user-images.githubusercontent.com/18650742/56890834-2f7b3180-6aad-11e9-8d10-97aea0e55007.png)
> 
> ![image](https://user-images.githubusercontent.com/18650742/56890928-69e4ce80-6aad-11e9-8f25-8c9e6ddfebab.png)
> 
> ![image](https://user-images.githubusercontent.com/18650742/56890977-8a148d80-6aad-11e9-8883-5978e09dd8b7.png)
> ![image](https://user-images.githubusercontent.com/18650742/56890992-94cf2280-6aad-11e9-80d7-78c5fd6c8c9e.png)
> 
> ![image](https://user-images.githubusercontent.com/18650742/56891027-b16b5a80-6aad-11e9-84ff-65c14b9d561e.png)
> 
> ![image](https://user-images.githubusercontent.com/18650742/56891012-a6b0c580-6aad-11e9-9841-08237c42aade.png)

hi, 这个问题你最终有通过修改源码解决了不？

**Comment by jihaiyu** [comment]
实现方案和最开始的想法有些差别，最终效果是实现了。

**Comment by jihaiyu** [comment]
close
