### ISSUE TITLE
请发布一个 针对es 1.4 使用的 1.2.9 版本

### ISSUE THREAD

**Issue by yangjun** [medcl/elasticsearch-analysis-ik#69]
请发布一个 针对es 1.4 使用的 1.2.9 版本

**Comment by sunyonggang** [comment]
支持一下，我试着自己编译，出来的是1.3.0，repo只有master分支是不是说之前的1.2.9的版本代码已经没有了

**Comment by medcl** [comment]
针对1.6.0的版本   https://github.com/medcl/elasticsearch-rtf/tree/1.6.0

**Comment by medcl** [comment]
自己编译的时候，寻找你版本最近的版本，修改下pom.xml文件es的版本打包即可。

**Comment by sunyonggang** [comment]
才发现这个issue，确实就像上面说的这样，自己找到指定版本即可
:runner:
