### ISSUE TITLE
使用elasticsearch-analysis-ik进行中文分词的时候出现乱码

### ISSUE THREAD

**Issue by kuhnyang** [medcl/elasticsearch-analysis-ik#70]
您好，我在使用elasticsearch-analysis-ik插件进行中文分词的时候字段保存成了乱码的形式，比如张三存成了å¼ ä¸‰，请问这是怎么回事

**Comment by medcl** [comment]
这个应该和ik插件没有关系，检测一下你的数据输入

**Comment by nsspw** [comment]
请问mysql river到ES时出现乱码，怎么解决？通过API建的索引没问题

**Comment by medcl** [comment]
得看看river对中文的支持了

**Comment by medcl** [comment]
river里面处理utf8吧，这个和分词器无关哦
