### ISSUE TITLE
null pointer exception

### ISSUE THREAD

**Issue by linhaobuaa** [medcl/elasticsearch-analysis-ik#71]
[2015-06-10 10:20:47,209][DEBUG][action.search.type       ] [ubuntu6] [guba][6], node[JydePkllR2WQdbgrRJDrCQ], [R], s[STARTED]: ❯
5540 org.elasticsearch.transport.RemoteTransportException: [ubuntu9][inet[/219.224.135.94:9301]][indices:data/read/search[phase/query❯
5541 Caused by: org.elasticsearch.search.SearchParseException: [guba][6]: from[-1],size[-1]: Parse Failure [Failed to parse source [{❯
5542 ▸---at org.elasticsearch.search.SearchService.parseSource(SearchService.java:681)
5543 ▸---at org.elasticsearch.search.SearchService.createContext(SearchService.java:537)
5544 ▸---at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:509)
5545 ▸---at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:264)
5546 ▸---at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTra❯
5547 ▸---at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTra❯
5548 ▸---at org.elasticsearch.transport.netty.MessageChannelHandler$RequestHandler.run(MessageChannelHandler.java:275)
5549 ▸---at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
5550 ▸---at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
5551 ▸---at java.lang.Thread.run(Thread.java:745)
5552 Caused by: java.lang.NullPointerException
5553 ▸---at org.wltea.analyzer.dic.Dictionary.isStopWord(Dictionary.java:212)
5554 ▸---at org.wltea.analyzer.core.AnalyzeContext.getNextLexeme(AnalyzeContext.java:316)
5555 ▸---at org.wltea.analyzer.core.IKSegmenter.next(IKSegmenter.java:118)
5556 ▸---at org.wltea.analyzer.lucene.IKTokenizer.incrementToken(IKTokenizer.java:88)
5557 ▸---at org.apache.lucene.analysis.CachingTokenFilter.fillCache(CachingTokenFilter.java:90)
5558 ▸---at org.apache.lucene.analysis.CachingTokenFilter.incrementToken(CachingTokenFilter.java:55)
5559 ▸---at org.apache.lucene.util.QueryBuilder.createFieldQuery(QueryBuilder.java:217)
5560 ▸---at org.apache.lucene.util.QueryBuilder.createBooleanQuery(QueryBuilder.java:87)
5561 ▸---at org.elasticsearch.index.search.MatchQuery.parse(MatchQuery.java:210)
5562 ▸---at org.elasticsearch.index.query.MatchQueryParser.parse(MatchQueryParser.java:165)
5563 ▸---at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
5564 ▸---at org.elasticsearch.index.query.BoolQueryParser.parse(BoolQueryParser.java:93)
5565 ▸---at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:277)
5566 ▸---at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:382)
5567 ▸---at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:281)
5568 ▸---at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:276)

**Comment by medcl** [comment]
es什么版本,和插件版本是否对应匹配

**Comment by iamliqiang** [comment]
File "/usr/local/lib/python2.7/dist-packages/mongo_connector/util.py", line 32, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mongo_connector/doc_managers/elastic_doc_manager.py", line 190, in bulk_upsert
    for ok, resp in responses:
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 156, in streaming_bulk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
BulkIndexError: ('32 document(s) failed to index.', [{u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a602bb5781ff71c59a1fc', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6259b5781ff71c59a201', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a63d1b5781ff71c59a206', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a64f5b5781ff71c59a209', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6690b5781ff71c59a213', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a67a7b5781ff71c59a216', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6835b5781ff71c59a218', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6955b5781ff71c59a221', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6a1bb5781ff71c59a225', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6c6bb5781ff71c59a234', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'553a6dc9b5781ff71c59a238', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'5541058b7ce2b722668f781b', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'5542d1e1c0a93c44171d7c8d', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'5546dd0cc0a93c44171d7c9c', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55924f98a0ddb3ea787c228b', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'559d256a2270937b292bd446', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55a3cd096cf28f073cc51d0e', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55b82466f64664154da161f5', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55b824ebf64664154da161f7', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55ba4d5f9ce908d465281be6', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55bb04cc9ce908d465281bed', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55beb75eb57e51ef39f0a5a7', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55bf037bf1d76dda754024f6', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55bf0556f1d76dda754024f9', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55bf966bae6be2d039bdfdf4', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55c1e610131f283b7810d1b7', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55c5ca55dba02da851efdbed', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55c717fff9ef5605796acfa4', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55ccabaaf9ef5605796acfbc', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55dfe1615dfa2d5e1d05a511', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'55e251fe5dfa2d5e1d05a533', u'error': u'NullPointerException[null]', u'_index': u'ot'}}, {u'index': {u'status': 500, u'_type': u'opost', u'_id': u'5610eeb1401def6516ee83f2', u'error': u'NullPointerException[null]', u'_index': u'ot'}}])
2015-10-06 12:45:27,241 [ERROR] mongo_connector.oplog_manager:551 - OplogThread: Failed during dump collection cannot recover! Collection(Database(MongoClient([u'vpc-node2:27017', u'vpc-node1:27017']), u'local'), u'oplog.rs')
2015-10-06 12:45:27,975 [ERROR] __main__:302 - MongoConnector: OplogThread <OplogThread(Thread-2, started 139868611557120)> unexpectedly stopped! Shutting down
"mongo-connector.log" 16L, 6090C

**Comment by iamliqiang** [comment]
我也遇到这样的问题， es 1.7.2   ik 最新版  git clone下来的

**Comment by iamliqiang** [comment]
用的jieba 分词，没有出现异常

**Comment by medcl** [comment]
配置文件都放了么

**Comment by daviddlw** [comment]
配置文件没放吧

**Comment by iamliqiang** [comment]
放了配置文件啊

2015-10-16 11:31 GMT+08:00 David <notifications@github.com>:

> 配置文件没放吧
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medcl/elasticsearch-analysis-ik/issues/71#issuecomment-148589476>
> .
>



-- 
Best regards/li.qiang

e-mail  : iamliqiang@gmail.com
mobile : 15811244506
msn    :  iamliqiang@hotmail.com

**Comment by iamliqiang** [comment]
这种错误是配置文件没放引起的么，配置文件我放在 /etc/elsticsearch/

2015-10-16 16:52 GMT+08:00 Li Qiang <iamliqiang@gmail.com>:

> 放了配置文件啊
>
> 2015-10-16 11:31 GMT+08:00 David <notifications@github.com>:
>
>> 配置文件没放吧
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/medcl/elasticsearch-analysis-ik/issues/71#issuecomment-148589476>
>> .
>>
>
>
>
> --
> Best regards/li.qiang
>
> e-mail  : iamliqiang@gmail.com
> mobile : 15811244506
> msn    :  iamliqiang@hotmail.com
>
>


-- 
Best regards/li.qiang

e-mail  : iamliqiang@gmail.com
mobile : 15811244506
msn    :  iamliqiang@hotmail.com

**Comment by iamliqiang** [comment]
ik 的配置文件放置在  /usr/share/elasticsearch/config/ik

2015-10-16 16:53 GMT+08:00 Li Qiang <iamliqiang@gmail.com>:

> 这种错误是配置文件没放引起的么，配置文件我放在 /etc/elsticsearch/
>
> 2015-10-16 16:52 GMT+08:00 Li Qiang <iamliqiang@gmail.com>:
>
>> 放了配置文件啊
>>
>> 2015-10-16 11:31 GMT+08:00 David <notifications@github.com>:
>>
>>> 配置文件没放吧
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/medcl/elasticsearch-analysis-ik/issues/71#issuecomment-148589476>
>>> .
>>>
>>
>>
>>
>> --
>> Best regards/li.qiang
>>
>> e-mail  : iamliqiang@gmail.com
>> mobile : 15811244506
>> msn    :  iamliqiang@hotmail.com
>>
>>
>
>
> --
> Best regards/li.qiang
>
> e-mail  : iamliqiang@gmail.com
> mobile : 15811244506
> msn    :  iamliqiang@hotmail.com
>
>


-- 
Best regards/li.qiang

e-mail  : iamliqiang@gmail.com
mobile : 15811244506
msn    :  iamliqiang@hotmail.com

**Comment by medcl** [comment]
@iamliqiang 请问解决了么？

**Comment by iamliqiang** [comment]
没有解决，目前用的是 jieba ，暂时没有用 ik

2015-12-24 19:58 GMT+08:00 Medcl <notifications@github.com>:

> @iamliqiang <https://github.com/iamliqiang> 请问解决了么？
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medcl/elasticsearch-analysis-ik/issues/71#issuecomment-167099509>
> .
>



-- 
Best regards/li.qiang

e-mail  : iamliqiang@gmail.com
mobile : 15811244506
msn    :  iamliqiang@hotmail.com

**Comment by iamliqiang** [comment]
我的电话是 15811244506 ，您电话多少，在北京么

2015-12-28 13:33 GMT+08:00 Li Qiang <iamliqiang@gmail.com>:

> 没有解决，目前用的是 jieba ，暂时没有用 ik
>
> 2015-12-24 19:58 GMT+08:00 Medcl <notifications@github.com>:
>
>> @iamliqiang <https://github.com/iamliqiang> 请问解决了么？
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/medcl/elasticsearch-analysis-ik/issues/71#issuecomment-167099509>
>> .
>>
>
>
>
> --
> Best regards/li.qiang
>
> e-mail  : iamliqiang@gmail.com
> mobile : 15811244506
> msn    :  iamliqiang@hotmail.com
>
>


-- 
Best regards/li.qiang

e-mail  : iamliqiang@gmail.com
mobile : 15811244506
msn    :  iamliqiang@hotmail.com

**Comment by medcl** [comment]
不在北京，看样子应该是你配置文件的问题，怎么会有个哥配置路径的？/etc/elsticsearch/和  /usr/share/elasticsearch/config

**Comment by xxllp** [comment]
这个配置到底是放在哪里哈
