### ISSUE TITLE
按照文档配置，没有接收到远程词典url发送的请求

### ISSUE THREAD

**Issue by zw201913** [medcl/elasticsearch-analysis-ik#729]
![image](https://user-images.githubusercontent.com/16849315/66697856-f1e12c80-ed0b-11e9-9050-9183fb412c07.png)
![image](https://user-images.githubusercontent.com/16849315/66697869-058c9300-ed0c-11e9-8fa0-e330e84ab400.png)
![image](https://user-images.githubusercontent.com/16849315/66697878-12a98200-ed0c-11e9-8bf0-bd62feab2263.png)

**Comment by lazywe** [comment]
删除注释

**Comment by zw201913** [comment]
谢谢，我竟然没看到，太感谢了
