### ISSUE TITLE
在Docker容器里跑时，ik_smart分词器找不到

### ISSUE THREAD

**Issue by baixiaoming555** [medcl/elasticsearch-analysis-ik#73]
http://localhost:9200/us/_analyze?analyzer=ik_smart&pretty=true&text=%E4%B8%AD%E5%8D%8E%E4%BA%BA%E6%B0%91%E5%85%B1%E5%92%8C%E5%9B%BD
出现以下结果
{
  "error" : "RemoteTransportException[[Doctor Faustus][inet[/172.17.0.7:9300]][indices:admin/analyze[s]]]; nested: ElasticsearchIllegalArgumentException[failed to find analyzer [ik_smart]]; ",
  "status" : 400
}
但是analyzer=ik的话是正常的。而且在本机单节点时没有任何问题。

**Comment by medcl** [comment]
容器里面配置有不一样么？

**Comment by baixiaoming555** [comment]
直接把本机单节点的elasticsearch.yml拷贝进去的啊，感觉好奇怪

**Comment by medcl** [comment]
any updates of this issue？

**Comment by zfha** [comment]
@medcl 我出现同样的问题，请问最后如何解决的，版本6.4.0
