### ISSUE TITLE
7.1.0分词器的 elasticsearch.version 还是7.0.0

### ISSUE THREAD

**Issue by ranying01** [medcl/elasticsearch-analysis-ik#731]
IK分词器里面的 elasticsearch.version 版本不对，导致插件安装失败
<properties>
        <elasticsearch.version>7.0.0</elasticsearch.version>
        <maven.compiler.target>1.8</maven.compiler.target>

**Comment by medcl** [comment]
插件下载对应的版本，源码编译要自己改版本号
