### ISSUE TITLE
es6.8.5  ik没有对应版本啊

### ISSUE THREAD

**Issue by naneb1993** [medcl/elasticsearch-analysis-ik#739]

**Comment by gitzhanglj** [comment]
我也遇到这个问题了，我这样解决的：在分支里面选择6.x，下载上传到linux，编译后在target/release下面有建好的包，拷到plugins里面，修改plugin-descriptor.properties文件中elasticsearch.version=你的ES版本号，就好了，希望对你有帮助

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v6.8.5
