### ISSUE TITLE
7.5.0版本啥时候发布

### ISSUE THREAD

**Issue by liuqingzheng** [medcl/elasticsearch-analysis-ik#743]
7.5.0版本啥时候发布

**Comment by Famers** [comment]
我之前都是自己把zip包下下来 然后把包名改成对应版本号 或者直接解压复制到plugin目录下也可以用

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.5.0/elasticsearch-analysis-ik-7.5.0.zip
