### ISSUE TITLE
请问elasticsearch.yml的作用，打包时应该放在哪？

### ISSUE THREAD

**Issue by zacker330** [medcl/elasticsearch-analysis-ik#75]
https://github.com/medcl/elasticsearch-analysis-ik/blob/master/config/elasticsearch.yml

这个文件到底有什么用？

**Comment by medcl** [comment]
配置参考,没有什么用

**Comment by zacker330** [comment]
谢谢啦。
问一个别的问题。
https://github.com/medcl/elasticsearch-analysis-ik/blob/master/src%2Fmain%2Fjava%2Forg%2Felasticsearch%2Findex%2Fanalysis%2FIkTokenizerFactory.java#L21

  public IkTokenizerFactory(Index index, @IndexSettings Settings indexSettings, Environment env, @Assisted String name, @Assisted Settings settings) {

那个settings参数是从哪来的？我在哪里配置它的？

**Comment by zacker330** [comment]
我知道在哪里了。在elasticsearch.yml中配置，然后使用env来读取。
