### ISSUE TITLE
7.x版本分词英文有问题

### ISSUE THREAD

**Issue by mateJay** [medcl/elasticsearch-analysis-ik#755]
POST /_analyze
{
  "analyzer": "ik_max_word",
  "text": ["are you ok"]
}

结果是：
{
  "tokens" : [
    {
      "token" : "you",
      "start_offset" : 4,
      "end_offset" : 7,
      "type" : "ENGLISH",
      "position" : 0
    },
    {
      "token" : "ok",
      "start_offset" : 8,
      "end_offset" : 10,
      "type" : "ENGLISH",
      "position" : 1
    }
  ]
}

**Comment by medcl** [comment]
are 是停用词，被过滤了。

**Comment by mateJay** [comment]
有什么办法不被过滤吗？可以在哪设置吗？

**Comment by xiaoluobotouzi** [comment]
> 有什么办法不被过滤吗？可以在哪设置吗？

找到停止词库，去掉 are
