### ISSUE TITLE
请问，关于热词更新，具体应该如何做

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-ik#76]
关于热词更新这部分：

	<entry key="remote_ext_dict">location</entry>
 	
	<entry key="remote_ext_stopwords">location</entry>
这里都是url，可是返回值的格式不是很明确，可以细致的说一下吗？具体应该返回怎样的内容？
另外就是更新是以什么样的机制更新，是把返回的内容更新到什么位置吗？
还有，我看到项目中使用了sougou的字典，但是没有引用，这个直接在配置文件里添加就可以了是吗？
现在这部分的资料极少，又极其难找，请问有什么论坛或者可以讨论的地方吗？
谢谢作者及团队。

另外：
在使用ik之前，用query_string搜索的时候，比如 title字段里面的内容是：美国政府今日关门。搜索关键字“美”就可以搜索出此内容；但是使用ik分词后，只能搜索“美国”才能搜索出此条内容，再搜索“美”无法搜索出结果，请问这种情况如何处理？

---资深Elasticsearch研究员

**Comment by Ben07** [comment]
该http请求返回的内容格式是一行一个分词，换行符用`\n`即可。(首页不是写着吗?)

**Comment by starckgates** [comment]
@Ben07 1.返回一行一个分词是string格式吧，比如“领导\n主任\n”这样？
真希望作者们能提供个帮助文档什么的就好了。。。

**Comment by Ben07** [comment]
@starckgates 对的,我是创建了一个*.dic的文件,然后一行一个词,用的时候读取这个文件.
我对term这个词还不是很了解,刚接触搜索这领域,用的也是elasticsearch

**Comment by starckgates** [comment]
@Ben07 哦，Elasticsearch里包含很多搜索方式，这个在api文档里是有介绍的，其中就包含term和query_string.其中term属于精确查询，如果不用分词的话必须是精确的，比如要搜“中华人民”，那么必须term：“中华人民”才可以搜出来；query_string就类似于sql里的like，属于模糊查询，不用分词的情况下搜索部分就可以，但是准确性低，就是这样。所以在用分词的时候，用term搜索比如“人民”就很精确的搜出“中华人民”，我是这样理解的。当然用法还有很多。因为初期没有用分词，所以一直用query_string ,但是信息量大的时候，会发现搜出来的根本不是想要的，所以现在需要用分词精确查询了。如果再想细致就需要用到聚合和过滤。。。哎，现在文档少的可怜。都是试，我接触Elasticsearch整2个月。从6.1开始知道这玩意的。

For Search

**Comment by Ben07** [comment]
@starckgates 多谢解释,我用的应该是query_string,使用了ikanalysis自带个搜狗词库,在use_smart模式下结果还是能接受的,有些词不想被拆分的话只能自己手动添加词了.我接触了可能一两个礼拜吧,最开始用的smart_cn,发现不是很好用.聚合和过滤我还没用到,不过估计以后会用到.先有个印象.
