### ISSUE TITLE
package v7.6.1 built into v7.4.0 jar

### ISSUE THREAD

**Issue by jrayu** [medcl/elasticsearch-analysis-ik#761]
![image](https://user-images.githubusercontent.com/37897165/77159246-f17d6680-6adf-11ea-83d3-e572447ae58e.png)

复制过去了才发现并不能跑.
于是我将pom里的7.4.0改成了7.6.1，能用了，但不确定有什么隐患。
![image](https://user-images.githubusercontent.com/37897165/77159132-bda24100-6adf-11ea-8998-f5e11375de59.png)

**Comment by medcl** [comment]
没有什么问题
