### ISSUE TITLE
搜索案例一

### ISSUE THREAD

**Issue by feng003** [medcl/elasticsearch-analysis-ik#765]
新人请教一下 关于搜索优化的

    POST product/_search
    {
          "from": 0,
          "size": 100,
      "query": {
        "bool": {
          "must": [
            {
              "match": {
                "title": "父与子"
              }
            }
          ]
        }
      }
    }

搜索了如下的结果
"max_score" : 19.332825,

    1  "title" : "父与子",     "_score" : 19.332825,
    2  "title" : "父与子，温情与爱",  "_score" : 18.432213,
    3  "title" : "父与子全集",  "_score" : 18.000814,
    4  "title" : "文子与浩森一起走",  "_score" : 11.440653,
    5  "title" : "艺术设计与美学 刘子川 ", "_score" : 10.115841,
    6  "title" : "现代物流学理论与实践 陈子侠"  "_score" : 9.804673,
    。。。还有N条只匹配一个字的 搜索

想请教一下 如何把后边4 到 N条过滤掉  现在考虑的是根据 _score来过滤。

方案一：简单的以为 _score减半之后的数据就可以过滤掉了

方案二：在分析索引或者搜索索引的时候限制关键词的长度，后来发现简单限制长度 会导致分词失败

    "analysis":{
          "analyzer":{
            "by_max_word":{
              "type":"custom",
              "tokenizer":"ik_max_word",
              "filter":["by_length"]
            }
          },
          "filter": {
            "by_length":{
              "type":"length",
              "min":2
            }
          }
    }

    GET /product/_analyze
    {
      "text": "父与子",
      "analyzer": "by_max_word"
    }
    //结果是
    {
      "tokens" : [ ]
    }

**Comment by yoke88** [comment]
按_score 排序，取前面的不就好了

**Comment by feng003** [comment]
> 按_score 排序，取前面的不就好了

是取了前面的，可以怎么判断呢？有没有规则

**Comment by billryan** [comment]
match_phrase 结合 minimal_should_match 就可以干掉了

**Comment by feng003** [comment]
> match_phrase 结合 minimal_should_match 就可以干掉了

minimum_should_match  谢谢了 学习了
