### ISSUE TITLE
关于create a mapping

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-ik#77]
看到您的示例，在create a mapping，属性里用到了indexanalyzer和searchanalyzer，这两个不是应该写成index_analyzer和search_analyzer这样吗？看到示例里是indexanalyzer和searchanalyzer，这样可以吗？

另外，我看到除了给字段定义了属性，同时也给类型定义了属性；字段定义属性我了解，请问给类型定义属性的意义是什么？这里不太理解。

感谢作者提供的ik，这真是极好的。

For Search！

**Comment by medcl** [comment]
@starckgates 是的，已fix，另外2.0以后，没有index_analyzer,只有analyzer和search_analyzer
