### ISSUE TITLE
请问一下查询路名查不到该怎么解决？

### ISSUE THREAD

**Issue by dongdong7** [medcl/elasticsearch-analysis-ik#772]
`{
  "tokens" : [ {
    "token" : "兴业路",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "CN_WORD",
    "position" : 0
  } ]
}`
以上是分析片断

`"address": "上海市黄浦区兴业路123弄5号楼",`

以上是数据片断

查询语句如下：

`
{
   "query":{
      "bool":{
         "must":[
            {
               "match":{
                  "address":"兴业路"
               }
            }
         ],
         "must_not":[],
         "should":[]
      }
   },
   "from":0,
   "size":10,
   "sort":[

   ],
   "aggs":{

   }
}

`
查不到数据，关键词换成 『兴业』就有数据。请大神们帮忙看看。

**Comment by momowsd** [comment]
什么版本的ik？  7.3.2的ik_smart切词就是“兴业” + “路”
{
  "tokens" : [
    {
      "token" : "兴业",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "CN_WORD",
      "position" : 0
    },
    {
      "token" : "路",
      "start_offset" : 2,
      "end_offset" : 3,
      "type" : "CN_CHAR",
      "position" : 1
    }
  ]
}

**Comment by dongdong7** [comment]
我发现重建mapping，再重导数据后可以起效。

**Comment by dongdong7** [comment]
更新字典且生效后，再调用update-by-query就可以用了。:- |

**Comment by momowsd** [comment]
嗯，自定义词典更新的话，索引需要重做
