### ISSUE TITLE
POST /_analyze 可以分词 在_index中不能分词

### ISSUE THREAD

**Issue by JayisGH** [medcl/elasticsearch-analysis-ik#773]
"properties": {
            "name": {
                "type": "text"
            },
            "age": {
                "type": "integer"
            },
            "mail": {
                "type": "keyword"
            },
            "hobby": {
                "type": "text",
                "analyzer": "ik_max_word"
            }
        }

POST _index/_search
{
    "query": {
        "match": {
            "hobby": "足球 "
        }
    },
    "highlight": {
        "fields": {
            "hobby": {}
        }
    }
}
==================================
    "_source": {
          "name": "袁隆平",
          "age": "17",
          "mail": "123@163.com",
          "hobby": " 足球、篮球"
        },
        "highlight": {
          "hobby": [
            "<em>足</em><em>球</em>、篮<em>球</em>"
          ]
        }
      }

什么原因 help!!!!!!

**Comment by medcl** [comment]
什么版本？
有没有完整可以复现的脚本？
```
PUT test-ik
{
  "mappings": {
    "properties": {
      "name": {
        "type": "text"
      },
      "age": {
        "type": "integer"
      },
      "mail": {
        "type": "keyword"
      },
      "hobby": {
        "type": "text",
        "analyzer": "ik_max_word"
      }
    }
  }
}

POST test-ik/_doc/1
{
      "name": "袁隆平",
      "age": "17",
      "mail": "123@163.com",
      "hobby": " 足球、篮球"
    }

POST test-ik/_search
{
  "query": {
    "match": {
      "hobby": "足球 "
    }
  },
  "highlight": {
    "fields": {
      "hobby": {}
    }
  }
}
```
我这里测试没有发现你的问题：
```
{
  "took" : 199,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.2876821,
    "hits" : [
      {
        "_index" : "test-ik",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 0.2876821,
        "_source" : {
          "name" : "袁隆平",
          "age" : "17",
          "mail" : "123@163.com",
          "hobby" : " 足球、篮球"
        },
        "highlight" : {
          "hobby" : [
            "<em>足球</em>、篮球"
          ]
        }
      }
    ]
  }
}

```

欢迎补充重新打开。

**Comment by JayisGH** [comment]
版本7.1.1
`POST /it_learner/_doc/work1
{
    "settings": {
        "index": {
            "number_of_shards": "1",
            "number_of_replicas": "0"
        }
    },
    "mappings": {
        "properties": {
            "name": {
                "type": "text"
            },
            "age": {
                "type": "integer"
            },
            "mail": {
                "type": "keyword"
            },
            "hobby": {
                "type": "text",
                "analyzer": "ik_max_word"
            }
        }
    }
}`

`/POST it_learner/_bulk
{"index": {"_index": "it_learner", "_id": 1}}
{"name": "袁隆平", "age": "17", "mail": "123@163.com", "hobby": "足球、篮球"}`


最后 
highlight中不能分开
