### ISSUE TITLE
请问下，在elasticsearch中如何使用java api操作ik？有没有相关文档？

### ISSUE THREAD

**Issue by shuai7boy** [medcl/elasticsearch-analysis-ik#791]
请问下，在elasticsearch中如何使用java操作ik？有没有相关文档？

**Comment by medcl** [comment]
只有在定义 Mapping 的地方会用到 IK，所有查看对应的 MappingAPI 就可以了。
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-analyze.html
https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-put-mapping.html

JAVA API 不能直接调用 IK 里面的方法。

**Comment by shuai7boy** [comment]
收到，感谢！
