### ISSUE TITLE
作者你好，热更新词库能否自己修改源码为增量更新，以检测文件的形式？

### ISSUE THREAD

**Issue by qwe857359351a** [medcl/elasticsearch-analysis-ik#802]
词库量接近10W，后续还会慢慢增加，每次热更新都会全量处理一遍，加载比较慢。
目前想到的方案是：
需要修改源码，词库以本地文件或者定期下载文件的形式，将词库文件放到IK的目前中，启动时加载，词库读取完成后，内存中记录文件最后的修改时间和最后读取的行数，当检测到文件发生变化时，从最后的一行开始读取，只加载新添加的词语。
不知这样的方案是能否可行？谢谢

**Comment by medcl** [comment]
可以的

**Comment by qwe857359351a** [comment]
> 可以的

好的，非常感谢您的回复

**Comment by qwe857359351a** [comment]
> 可以的

好的，非常感谢您的回复

**Comment by ColorfulDick** [comment]
老哥，如果要实现增量更新，是不是得配置2个url，一个负责全局更新，一个负责增量更新？否则怎么知道ik分词器要拉取全量(es服务刚启动需要初始化时)的还是增量的？
