### ISSUE TITLE
无法将包含“-”的词正确分词，如“歼-10“

### ISSUE THREAD

**Issue by luyehui** [medcl/elasticsearch-analysis-ik#804]
已在远程词库中添加了 “歼-10”，但是无法得到正确的分词。
POST /_analyze
{
  "text": "歼-10",
  "tokenizer": "ik_max_word"
}

{
    "tokens": [
        {
            "token": "歼",
            "start_offset": 0,
            "end_offset": 1,
            "type": "CN_CHAR",
            "position": 0
        },
        {
            "token": "10",
            "start_offset": 2,
            "end_offset": 4,
            "type": "ARABIC",
            "position": 1
        },
        {
            "token": "1",
            "start_offset": 2,
            "end_offset": 3,
            "type": "CN_WORD",
            "position": 2
        }
    ]
}

**Comment by zhangAlwin** [comment]
这个问题最后怎么解决了

**Comment by luyehui** [comment]
> 这个问题最后怎么解决了

改源码
