### ISSUE TITLE
7.6.1数字+中文的无法查询到结果

### ISSUE THREAD

**Issue by han1101xu** [medcl/elasticsearch-analysis-ik#811]
例如：查找 2020年
分词：
`GET /_analyze
{
  "text":"2020年",
  "analyzer":"ik_smart"
}`
分词结果：
`{
  "tokens" : [
    {
      "token" : "2020年",
      "start_offset" : 0,
      "end_offset" : 5,
      "type" : "TYPE_CQUAN",
      "position" : 0
    }
  ]
}`

查询：
` GET test3/_search
{
  "query": {
     "match":
          {
            "productName":"2020年"
          }
  }
}`
查询结果：
`{
  "took" : 1,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 0,
      "relation" : "eq"
    },
    "max_score" : null,
    "hits" : [ ]
  }
}`

``

**Comment by han1101xu** [comment]
是因为 ik_smart和ik_max_word 对2020年的分词结果不一致导致的。
我设置的"analyzer": "ik_max_word"， "search_analyzer": "ik_smart"

**Comment by yanqic** [comment]
> 是因为 ik_smart和ik_max_word 对2020年的分词结果不一致导致的。
> 我设置的"analyzer": "ik_max_word"， "search_analyzer": "ik_smart"

我试了 两个分词是一样的  7.8版本
