### ISSUE TITLE
如何才能将英文的停用词识别为一个词?

### ISSUE THREAD

**Issue by ucando** [medcl/elasticsearch-analysis-ik#813]
由于应用特殊, 英文单词中的as需要被正常搜索, 但是分词器已经默认将它过滤掉了, 是否有办法将它作为一个词来处理? 尝试在自定义词库里加上as这个词, 但没效果

**Comment by tifazxy** [comment]
停用词词典stopword.dic中去除掉as这个词，重启ES集群就可以被分词了
