### ISSUE TITLE
关于热词更新 return bad code 405

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-ik#83]
------------------------------------------------------
错误提示    Elasticsearch版本 1.6.0  ik 对应版本
===================================
[2015-08-06 14:31:11,567][INFO ][ik-analyzer              ] remote_ext_dict http://localhost:8000/api/Dict/getCustomDict/ return bad code 405
------------------------------------------------------
curl里第一次执行返回值：
===================================
C:\Windows\system32>curl -i http://localhost:8000/api/Dict/getCustomDict/
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 12
Content-Type: text/html
Last-Modified: Thu, 06 Aug 2015 03:29:17 GMT
ETag: "2e7541aa8c6e5a2681adf19c007bc3d9"
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 06 Aug 2015 06:22:37 GMT

medcl
浣?
-----------------------------------------------------------
curl里第二次执行返回值
=====================================
C:\Windows\system32>curl -i http://localhost:8000/api/Dict/getCustomDict/
HTTP/1.1 200 OK
Cache-Control: public
Content-Length: 71
Content-Type: text/html
Last-Modified: Thu, 06 Aug 2015 06:25:45 GMT
ETag: "91fb16762ac5ce1dee59a127f23daaf8"
Server: Microsoft-IIS/8.0
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Date: Thu, 06 Aug 2015 06:26:06 GMT

medcl
浣?
medcl
浣?
鍗撳垱
鍗撳垱璧勮
鏀剁洏
鏀剁洏浠?
纾烽吀
------------------------------------------------------------
请问是哪里有问题的呢？
Please told me where is the problem?Thank YOU！
另外，为什么中文显示的是乱码，读取的文件是utf-8格式。

**Comment by starckgates** [comment]
其中乱码的问题我找到答案了，把utf-8改成utf-8 Signature就好了，可为啥不是utf-8呢？

**Comment by starckgates** [comment]
我来补充一下，截了一些图
![1](https://cloud.githubusercontent.com/assets/12822162/9105844/ec5469bc-3c4d-11e5-9513-740b40b06f9e.png)
![2](https://cloud.githubusercontent.com/assets/12822162/9105850/f3b58e70-3c4d-11e5-9bf0-d5f5cdb1dd5c.png)

**Comment by medcl** [comment]
.net里面输出的时候指定的编码对了应该就行的

**Comment by starckgates** [comment]
@medcl 现在的问题是在浏览器里查看没问题，第一次返回200，没变化的情况下返回304。
但是在ES控制台中返回405，这个是不是有什么问题存在？另外热词更新从url里取出值后，保存在什么文件中吗？还是直接就给ik用了？像是远程字典？
这个热词，在启动Elasticsearch的时候会加载出来

---------------------
[2015-08-06 15:36:22,378][INFO ][ik-analyzer              ] [Dict Loading]http://localhost:8000/api/Dict/getCustomDict/
[2015-08-06 15:36:22,746][INFO ][ik-analyzer              ] 锘縨edcl
[2015-08-06 15:36:22,747][INFO ][ik-analyzer              ] 浣?
[2015-08-06 15:36:22,749][INFO ][ik-analyzer              ] 鍗撳垱
[2015-08-06 15:36:22,750][INFO ][ik-analyzer              ] 鍗撳垱璧勮
[2015-08-06 15:36:22,751][INFO ][ik-analyzer              ] 鏀剁洏
[2015-08-06 15:36:22,755][INFO ][ik-analyzer              ] 鏀剁洏浠?
[2015-08-06 15:36:22,758][INFO ][ik-analyzer              ] 纾烽吀
[2015-08-06 15:36:22,759][INFO ][ik-analyzer              ] 鍖栧伐

-------------------------------------
然后再继续就是
[2015-08-06 15:49:32,775][INFO ][ik-analyzer              ] remote_ext_dict http://localhost:8000/api/Dict/getCustomDict/ return bad code 405
[2015-08-06 15:50:32,772][INFO ][ik-analyzer              ] remote_ext_dict http://localhost:8000/api/Dict/getCustomDict/ return bad code 405
[2015-08-06 15:51:32,770][INFO ][ik-analyzer              ] remote_ext_dict http://localhost:8000/api/Dict/getCustomDict/ return bad code 405

无论我如何改变文件内容都是这样。

**Comment by starckgates** [comment]
我把.net代码沾进来大家看看，使用的webapi

----------------------------------------------------------------------------------------

    public class DictController : ApiController
    {
        [HttpGet]
        public HttpResponseMessage getCustomDict()
        {
            HttpResponseMessage response = new HttpResponseMessage();
            string filename = "E:/ForSearch/ForSearch_v1.0/DictWebAPI/Dict/updict.dic";
            FileInfo fileinfo = new FileInfo(filename);
            if (fileinfo == null)
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
            string etag = string.Format("\"{0}\"", GetMD5.GetMD5HashFromFile(filename));
            var tag = Request.Headers.IfNoneMatch.FirstOrDefault();
            if (Request.Headers.IfModifiedSince.HasValue && tag != null && tag.Tag == etag)
            {
                response.StatusCode = HttpStatusCode.NotModified;
            }
            else
            {
                FileStream fs = fileinfo.OpenRead();
                MemoryStream responseStream = new MemoryStream();
                bool fullContent = true;

                if (this.Request.Headers.Range != null)
                {
                    fullContent = false;
                    RangeItemHeaderValue range = this.Request.Headers.Range.Ranges.First();
                    if (range.From != null)
                    {
                        fs.Seek(range.From.Value, SeekOrigin.Begin);
                        if (range.From == 0 && (range.To == null || range.To >= fs.Length))
                        {
                            fs.CopyTo(responseStream);
                            fullContent = true;
                        }
                    }
                    if (range.To != null)
                    {
                        if (range.From != null)
                        {
                            long? rangeLength = range.To - range.From;
                            int length = (int)Math.Min(rangeLength.Value, fs.Length - range.From.Value);
                            byte[] buffer = new byte[length];
                            fs.Read(buffer, 0, length);
                            responseStream.Write(buffer, 0, length);
                        }
                        else
                        {
                            int length = (int)Math.Min(range.To.Value, fs.Length);
                            byte[] buffer = new byte[length];
                            fs.Read(buffer, 0, length);
                            responseStream.Write(buffer, 0, length);
                        }
                    }
                    else
                    {
                        if (range.From != null)
                        {
                            if (range.From < fs.Length)
                            {
                                int length = (int)(fs.Length - range.From.Value);
                                byte[] buffer = new byte[length];
                                fs.Read(buffer, 0, length);
                                responseStream.Write(buffer, 0, length);
                            }
                        }
                    }
                }
                else
                {
                    fs.CopyTo(responseStream);
                }
                fs.Close();
                responseStream.Position = 0;
                response.StatusCode = fullContent ? HttpStatusCode.OK : HttpStatusCode.PartialContent;
                response.Content = new StreamContent(responseStream);
                response.Headers.ETag = new EntityTagHeaderValue(etag);
                response.Headers.CacheControl = new CacheControlHeaderValue();
                response.Headers.CacheControl.Public = true;
                response.Headers.CacheControl.MaxAge = TimeSpan.FromHours(24);
                response.Content.Headers.Expires = DateTimeOffset.Now.AddDays(1);
                response.Content.Headers.LastModified = fileinfo.LastWriteTime;
            }
            return response;
        }
    }


----------------------------------------------------------------------------------------

**Comment by medcl** [comment]
每次远程取,本地没有保存,你大jar包是自己编译的么?你可以编译一下使用最新的代码,之前的版本有问题

**Comment by starckgates** [comment]
@medcl jar是自己编译的，在git下载的zip包，然后用mvn编译生成的，然后用target\releases、elasticsearch-analysis-ik-1.4.0.zip里的5个jar包。
建议大神这个修改版价格版本号，因为我昨天重新下载的，版本跟之前一样也是1.4.0，所以看不出区别。
另外远程取是不是只要启动Elasticsearch的时候看到加载到分词了就算能用了？只是后面热词更新的时候不知道是什么样的，因为我这还是提示 return bad code 405

**Comment by starckgates** [comment]
我刚测试了，现在的问题就是第一次es启动的时候可以加载，分词可用，但是无法热词更新，再添加新分词，不重启es无法实现新的分词使用，应该就是return bad code 405的问题。麻烦大神看看是不是bug之类的

**Comment by starckgates** [comment]
另外还有一点，就是这个热词更新，每次更新后都需要重建索引？否则新的词是差不错来的啊

**Comment by medcl** [comment]
恩,词库调整后只会影响后进来的索引数据,之前的不会变的

**Comment by medcl** [comment]
你写的这个http服务不支持HEAD操作,所以报405了

**Comment by medcl** [comment]
插件源码:org.wltea.analyzer.dic.Monitor
49行:		HttpHead head = new HttpHead(location);
修改为:
		HttpGet head = new HttpGet(location);
我这没有环境,你可以帮忙验证一下么?谢谢.

**Comment by medcl** [comment]
如果不支持HEAD的话,会加大检测是否新词变化的开销,建议还是你实现HEAD的操作,或者你本地修改插件代码也行

**Comment by starckgates** [comment]
@medcl 
我刚刚看了您的源码，确实是这样，我开了一个新题目，关于304的问题的。
我在我的源码里进行了调整，尽量不去修改您那边代码，增加了服务器head请求后是可以的。

**Comment by starckgates** [comment]
成功加载了两次后出现了下面的错误

----------

[2015-08-07 10:55:10,564][ERROR][ik-analyzer              ] remote_ext_dict http://localhost:8000/api/Dict/getCustomDict/ error!
java.lang.NullPointerException
        at org.wltea.analyzer.dic.Monitor.run(Monitor.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by starckgates** [comment]
@medcl  大神，我找到问题了，是您源码里的，可能被别人修改的了问题
 
==========

//返回200 才做操作
			if(response.getStatusLine().getStatusCode()==200 || response.getStatusLine().getStatusCode()==304)
修改为 

//返回200 才做操作
			if(response.getStatusLine().getStatusCode()==200 )

问题就解决了~

**Comment by medcl** [comment]
那你提交个pull request吧，welcome

send via my Phone.

**Comment by starckgates** [comment]
@medcl 
额~(⊙o⊙)… 研究了半天，git这玩意儿只会看看，不知道咋pull .....
等我研究研究啊~O(∩_∩)O~

**Comment by medcl** [comment]
refer to #84
