### ISSUE TITLE
编译文件版本和源码版本不一致

### ISSUE THREAD

**Issue by AlbertZhe** [medcl/elasticsearch-analysis-ik#839]
我切换到 v7.7.1 tag；使用 mvn -U clean package -Dmaven.test.skip 编译，但是在 target\releases 目录下，获取的是 7.4.0 版本的 zip 文件。

**Comment by AlbertZhe** [comment]
我知道修改配置文件可以达到和ES匹配，只是不明白为什么官网下载版本正确，但是自己编译却不匹配呢

**Comment by medcl** [comment]
打包的时候版本号是动态传进去的，代码没有改，没有必要每次改个版本号提交一下。
