### ISSUE TITLE
热词更新的304问题

### ISSUE THREAD

**Issue by starckgates** [medcl/elasticsearch-analysis-ik#84]
那篇写的太多了，于是在这里重新开了一个
大神，我刚看了源码，索然java不是很精通，但还是能看懂。
在热词更新里，ES加载的时候使用的http get请求，所以我写的远程词典可以用
然后在监控流程里使用的是http head请求，因为我的webapi只使用了[HttpGet],所以head请求没有权限，所以返回了405，我改成[AcceptVerbs("GET", "HEAD")] 后，这个问题得到解决。
下面说的是304的问题，我看到源码里原来只是判断200的时候进行获取，这个是对的，为什么还要加上304也获取呢？304本身就是没有变化才返回304，这个是客户端通过cookie与服务器获取的header对比来的，所以，增加304页获取是不正确的，希望大神能考虑一下，
或许是其他大神改的，您没有看到？

**Comment by starckgates** [comment]
1、将http 304作为正常状态处理  这个是不正确的

304不应该和200做相同处理，否则就失去热词更新的意义了。

**Comment by medcl** [comment]
同意，301 304 500 403 404都可以忽略，只过200

send via my Phone.

**Comment by starckgates** [comment]
@medcl 
大神~会pull啦~

**Comment by medcl** [comment]
#86 fixed
