### ISSUE TITLE
请问一下ik分词器6.8.12版本支持es6.8.13么？

### ISSUE THREAD

**Issue by LuckyMango** [medcl/elasticsearch-analysis-ik#840]
我们目前使用的是elasticsearch6.8.13版本，但是在安装ik分词器的时候发现没有6.8.13版本，只有6.8.12版本。请问一下ik6.8.12版本是否支持es6.8.13版本
![image](https://user-images.githubusercontent.com/43702671/100716155-45707700-33f3-11eb-870c-a6a9feb2f7f3.png)

**Comment by medcl** [comment]
已上传 6.8.13
