### ISSUE TITLE
analyzer [ik_smart] has not been configured in mappings

### ISSUE THREAD

**Issue by shaofuzhang** [medcl/elasticsearch-analysis-ik#848]
elasticsearch-7.10.1

安装插件 ./bin/elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.10.1/elasticsearch-analysis-ik-7.10.1.zip

重启了 es 

使用 ./elasticsearch-plugin 可以看到安装成功
![image](https://user-images.githubusercontent.com/13144493/103144572-e0484100-4766-11eb-9e76-aa7ffa5defbd.png)

按照文档创建mapping
curl -XPOST http://localhost:9200/index/_mapping -H 'Content-Type:application/json' -d'
{
        "properties": {
            "content": {
                "type": "text",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_smart"
            }
        }

}'

提示 

{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"analyzer [ik_smart] has not been configured in mappings"}],"type":"illegal_argument_exception","reason":"analyzer [ik_smart] has not been configured in mappings"},"status":400}

**Comment by XieCJ** [comment]
遇到了同样问题，怎么解决的？

**Comment by tonitech** [comment]
遇到了同样问题，怎么解决的？

**Comment by tonitech** [comment]
> 遇到了同样问题，怎么解决的？

我试了下，如果有一个节点没有安装插件会报这个错误的，所有的节点都要安装插件
