### ISSUE TITLE
编译后版本不一致的情况 强调一下 希望大家顶上去，不要沉下去了

### ISSUE THREAD

**Issue by zanglikun** [medcl/elasticsearch-analysis-ik#857]
新尝试此分词器的 老哥，请直接下载 编译好的版本，不要拿Maven版本去编译，不出意外 你编译的版本 会与你下载的源码编译出来的结果 不一致。所以 ，直接下载发布好的编译好的版本！！！
![A)EQ%{3SJ_)K@_M%LECNBY7](https://user-images.githubusercontent.com/61591648/106093827-faad7a00-616b-11eb-9824-ec29c3ec9308.png)

**Comment by frsweety** [comment]
maven是能编译的，编译前先手动把版本改下就行了，具体哪个文件我忘了

**Comment by zanglikun** [comment]
是的，但是 新手尝试的时候，自己尝试拿源码去编译，编译出来版本不一致，所以 我才会留言

**Comment by medcl** [comment]
手动下载源码就要自己改版本。之前的 issue 里面有说明的。
