### ISSUE TITLE
请问下现在是否有适配7.11版本的es的 ik 分词器

### ISSUE THREAD

**Issue by BigDataScholar** [medcl/elasticsearch-analysis-ik#859]
最近在学习ES，安装了目前官网最新的7.11版本的elasticsearch，然后发现分词器最新版本只有7.10.2，发现并不能使用，想问下7.11.x 版本的 ik 分词器什么时候能更新，谢谢

**Comment by cuiliang** [comment]
同求，谢谢~

**Comment by lyf3358** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.11.1/elasticsearch-analysis-ik-7.11.1.zip
这个下载地址有问题

**Comment by BigDataScholar** [comment]
> https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.11.1/elasticsearch-analysis-ik-7.11.1.zip
> 这个下载地址有问题

我刚下载成功了，你看下这个网址：https://github.com/medcl/elasticsearch-analysis-ik/archive/v7.11.1.zip

**Comment by BigDataScholar** [comment]
感谢 Jack 及时更新了最新的 ik 分词器

**Comment by YiuTerran** [comment]
> 感谢 Jack 及时更新了最新的 ik 分词器

最新版没有release，只有source code，要改pom文件自己编译吧？

**Comment by lyf3358** [comment]
> > 感谢 Jack 及时更新了最新的 ik 分词器
> 
> 最新版没有release，只有source code，要改pom文件自己编译吧？

不知道要改pom文件，差点编译吐血，多谢老哥提示

**Comment by cuiliang** [comment]
> > > 感谢 Jack 及时更新了最新的 ik 分词器
> > 
> > 
> > 最新版没有release，只有source code，要改pom文件自己编译吧？
> 
> 不知道要改pom文件，差点编译吐血，多谢老哥提示

大佬可以分享一个编译好的么？不懂Java实在是太难了😢

**Comment by lyf3358** [comment]
> > > > 感谢 Jack 及时更新了最新的 ik 分词器
> > > 
> > > 
> > > 最新版没有release，只有source code，要改pom文件自己编译吧？
> > 
> > 
> > 不知道要改pom文件，差点编译吐血，多谢老哥提示
> 
> 大佬可以分享一个编译好的么？不懂Java实在是太难了😢

用 maven 编译 你去了解下

**Comment by YiuTerran** [comment]
> 大佬可以分享一个编译好的么？不懂Java实在是太难了😢

https://cowtransfer.com/s/79f3ed06d8954f  在首页输入取件码：778988（24小时内有效）

**Comment by cuiliang** [comment]
> > 大佬可以分享一个编译好的么？不懂Java实在是太难了😢
> 
> https://cowtransfer.com/s/79f3ed06d8954f 在首页输入取件码：778988（24小时内有效）

谢谢~

**Comment by cuiliang** [comment]
Java0基础，尝试在windows下编译了一下，做个记录。供有类似需求的朋友参考：

参考资料：https://www.cnblogs.com/csyzlm/p/11660710.html

**安装JDK：**
https://www.oracle.com/java/technologies/javase-jdk15-downloads.html
下载安装Windows x64 Installer

**下载安装Maven：**
https://maven.apache.org/download.cgi
下载zip包
解压缩在某个位置



**设置环境变量**
新建环境变量MAVEN_HOME和M2_HOME，赋值前面解压缩的路径。
编辑环境变量Path，追加;%MAVEN_HOME%\bin\;



**修改配置文件**
修改解压目录下conf/settings.xml文件。
添加国内镜像源，其它保持默认。

<mirror>
    <id>alimaven</id>
    <mirrorOf>central</mirrorOf>
    <name>aliyun maven</name>
    <url>http://maven.aliyun.com/nexus/content/repositories/central/</url>
</mirror>

**编译**
下载ik代码包
修改pom文件中的ES版本（7.11.1）
在目录下开启命令行窗口运行 mvn build 命令。

**打包**
运行 mvn package 命令。
完成后在elasticsearch-analysis-ik-7.11.1\target\releases下会生成一个zip文件，就是它了。

**Comment by BigDataScholar** [comment]
> Java0基础，尝试在windows下编译了一下，做个记录。供有类似需求的朋友参考：
> 
> 参考资料：https://www.cnblogs.com/csyzlm/p/11660710.html
> 
> **安装JDK：**
> https://www.oracle.com/java/technologies/javase-jdk15-downloads.html
> 下载安装Windows x64 Installer
> 
> **下载安装Maven：**
> https://maven.apache.org/download.cgi
> 下载zip包
> 解压缩在某个位置
> 
> **设置环境变量**
> 新建环境变量MAVEN_HOME和M2_HOME，赋值前面解压缩的路径。
> 编辑环境变量Path，追加;%MAVEN_HOME%\bin;
> 
> **修改配置文件**
> 修改解压目录下conf/settings.xml文件。
> 添加国内镜像源，其它保持默认。
> 
> alimaven central aliyun maven http://maven.aliyun.com/nexus/content/repositories/central/
> **编译**
> 下载ik代码包
> 修改pom文件中的ES版本（7.11.1）
> 在目录下开启命令行窗口运行 mvn build 命令。
> 
> **打包**
> 运行 mvn package 命令。
> 完成后在elasticsearch-analysis-ik-7.11.1\target\releases下会生成一个zip文件，就是它了。

感谢cuiliang的分享，可惜我es的版本是7.11.0，最新发布的7.11.1版本依然无法适配

**Comment by cuiliang** [comment]
@BigDataScholar 我试了修改7.11.0，也是编译不成功的。 看起来对我们小白来说，只能升级ES版本了😂

**Comment by BigDataScholar** [comment]
看起来好像是的，最新的ik分词器版本已经到了7.11.1，我也觉得7.11.0不会有更新了

**Comment by medcl** [comment]
maven 里面7.11.0的 es 包没有，直接用最新的版吧。
