### ISSUE TITLE
建议远程词库增加支持gzip压缩响应

### ISSUE THREAD

**Issue by cuiliang** [medcl/elasticsearch-analysis-ik#860]
由于完全不懂java，抱歉无法修改并贡献代码。

7.11.1版本。

当服务器启用响应内容压缩时，content-encoding 的值是gzip，此时词典无法加载成功（请求不出错，但是取不出单词）。
必须关闭服务器的压缩选项，词典才能正常加载。

网上搜到一些gzip支持的讨论，供大佬参考：https://stackoverflow.com/a/2790124/3335415

**Comment by yanqic** [comment]
看了源码， 7.11.1 版本是支持 gzip 的，看看响应头是不是缺少 chunk etag ,last-modify
