### ISSUE TITLE
Mapper for [content] conflicts with existing mapper:\n\tCannot update parameter [analyzer] from [ik_max_word] to [default]

### ISSUE THREAD

**Issue by cooldowntime** [medcl/elasticsearch-analysis-ik#865]
7.11.1版本 
完全按照例子来的，新增映射再添加文档，新增文档的时候报错，测试分词是可用的
{'error': {'root_cause': [{'type': 'illegal_argument_exception', 'reason': 'Mapper for [content] conflicts with existing mapper:\n\tCannot update parameter [analyzer] from [ik_max_word] to [default]'}], 'type': 'illegal_argument_exception', 'reason': 'Mapper for [content] conflicts with existing mapper:\n\tCannot update parameter [analyzer] from [ik_max_word] to [default]'}, 'status': 400}

mapping配置
{
    "mappings": {
        "properties": {
            "content": {
                "type": "text",
                "analyzer": "ik_max_word",
                "search_analyzer": "ik_smart"
            }
        }
    }
}

**Comment by kunkkazyc** [comment]
Same problem happen in my project. how to resolve this issue?

**Comment by anatanick** [comment]
Me too, when I use 7.12.1 in my project, can anyone help me? THx

**Comment by leojames** [comment]
问题解决了么 有答案了么？

**Comment by medcl** [comment]
麻烦提一下完整的复现过程，我刚特意试了一下，没有遇到如上问题哈，注意 es 的 Mapping 里面的 analyzer 不能直接修改，要删掉重新来

**Comment by leojames** [comment]
这个为啥不能在mapping设置analyzer呢？如果不指定这个会自动选择ik 是不是不指定那个search_analyzer 也会默认走ik ？

**Comment by medcl** [comment]
>这个为啥不能在mapping设置analyzer呢？
需要手动设置否则走默认的 analyzer，analyzer 一旦设置不能修改，不明白你说的为什么不能设置是什么意思。

**Comment by wc188996** [comment]
我也碰到了这个问题，请问有解决方案了么？我用的是7.12
PUT http://localhost:9200/doc HTTP/1.1
Content-Type: application/json

{
    "mappings": {
      "properties": {
        "content": {
          "type": "text",
          "analyzer": "ik_max_word",
          "search_analyzer": "ik_smart"
        }
      }
    }
}

put http://localhost:9200/doc/pdf/20210601 HTTP/1.1
Content-Type: application/json

{"content":"同时面向真正生产过程的控制闭环。"} 

异常如下：
"root_cause": [
      {
        "type": "illegal_argument_exception",
        "reason": "Mapper for [content] conflicts with existing mapper:\n\tCannot update parameter [analyzer] from [ik_max_word] to [default]"
      }
    ]

**Comment by wc188996** [comment]
试了半天  按照样例一直报错，改为如下方式可以正常工作：
`PUT http://localhost:9200/doc HTTP/1.1
Content-Type: application/json

{   
    "settings": {
    "analysis": {
      "analyzer": {
        "default": {
          "type": "ik_max_word"
        }
      }
    }
    }
}`
然后在上传文件就可以了
`POST  http://localhost:9200/doc/pdf/20210602 HTTP/1.1
Content-Type: application/json

{"content":"能力，同时面向真正生产过程的控制闭环。"}`

**Comment by hshdy** [comment]
这个有可能是指定了 type 导致的报错。

**Comment by 180501** [comment]
找到解决方案了，使用POST来进行更改文档内容而不用更改全局设置(_settings)：
POST /post/_doc
{
  "mappings": {
    "properties": {
    "title": {
      "type": "text",
      "analyzer": "ik_max_word",  
      "search_analyzer": "ik_smart"
    },
    "content": {
      "type": "text",
      "analyzer": "ik_max_word",
      "search_analyzer": "ik_smart"
    }
  }
  }
}
这样运行后再次查询，选定的映射就具有分词器了
