### ISSUE TITLE
求大佬编译7.12.0版本

### ISSUE THREAD

**Issue by Talbot5** [medcl/elasticsearch-analysis-ik#868]
es更新了7.12.0，小弟不会maven编译

**Comment by Talbot5** [comment]
> es更新了7.12.0，小弟不会maven编译

解决方法，修改plugin-descriptor.properties中的es中
的version版本

**Comment by FikaCode** [comment]
我改了版本号编译了一下， https://github.com/FikaCode/elasticsearch-analysis-ik-compile/releases/tag/7.12.0
