### ISSUE TITLE
1.4.0 能用在 ES 1.7.1 中吗？

### ISSUE THREAD

**Issue by ejzhang** [medcl/elasticsearch-analysis-ik#88]
下载master编译后版本是1.4.0，不知能否用在最新的ElasticSearch 1.7.1中？

**Comment by medcl** [comment]
请自行修改pom文件中es的版本再编译
        <elasticsearch.version>1.7.1</elasticsearch.version>

send via my Phone.

**Comment by ejzhang** [comment]
谢谢！

**Comment by sxpd7788** [comment]
我这里修改es的版本号然后编译配置不过还是不行。 一起启动久保错。

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-rtf/tree/1.7.1?files=1

这里有编译好的，自取

send via my Phone.
