### ISSUE TITLE
热更新 IK 分词数量对ES的影响？

### ISSUE THREAD

**Issue by CodeLieutenant** [medcl/elasticsearch-analysis-ik#89]
热更新IK分词的时候，如果需要更新的分词特别多，例如一万多，那么这样的话，因为tcp传输分片以及重建词典的原因，会不会特别占资源，进而影响ES的正常功能？或者不是一万多，那么是否存在一个您推荐的阈值呢

**Comment by medcl** [comment]
如果这么多,建议修改词典文件再重启服务器,更新词典会影响分词结果,会影响之前数据的查询,尽量少做更新

**Comment by hanjk1234** [comment]
大神，如果热更新了词典文件，是不是需要重新索引之前的数据？
那这样子的话就需要停机，重新索引？

**Comment by medcl** [comment]
需要重新索引！停机是不必的

send via my Phone.

**Comment by hanleijun** [comment]
大神，想问一下，我通过远程词典热更新了之后，发现，查询结果很不稳定，一会按照添加前的来，一会按照添加后的来（全部重建索引之后仍然这样），请问建议怎样处理呢？

**Comment by medcl** [comment]
现在的热更新分词属于实验性质，建议谨慎使用，生成环境请更新词典文件。
