### ISSUE TITLE
elasticsearch 7.13.3,已经转好，结果分词器还没适配，，，，

### ISSUE THREAD

**Issue by MicahKong** [medcl/elasticsearch-analysis-ik#894]
elasticsearch 7.13.3,已经转好，结果分词器还没适配，，，，
java.lang.IllegalArgumentException: Plugin [analysis-ik] was built for Elasticsearch version 7.13.2 but version 7.13.3 is running

**Comment by cnzcs** [comment]
7.13.3 的es 最新版本 装上 7.13.2的ik es 启动会闪退 有没有大佬能解答

**Comment by MicahKong** [comment]
我把es版本降到7.13.2，就可以了，估计开发



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月15日(周四) 晚上7:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [medcl/elasticsearch-analysis-ik] elasticsearch 7.13.3,已经转好，结果分词器还没适配，，，， (#894)




 
7.13.3 的es 最新版本 装上 7.13.2的ik es 启动会闪退 有没有大佬能解答
