### ISSUE TITLE
关于ik 分词器 7.13.2 无法匹配elasticsearch-7.13.3最新版本解决方案-本人亲测可用-cnzcs

### ISSUE THREAD

**Issue by cnzcs** [medcl/elasticsearch-analysis-ik#895]
只需要改一下ik分词器插件的配置就可以了plugin-descriptor.properties 将里面的 elasticsearch.version=7.13.2版本改成 elasticsearch.version=7.13.3version=7.13.3 重启es 就可以了

**Comment by caolong373** [comment]
很棒, 本来准备换下版本

**Comment by wuxiuling01** [comment]
欸，我怎么不行

**Comment by QQ-ing** [comment]
不行的，需要检查一下 plugin-descriptor.properties 这个文件里面有两个地方需要修改，一个是 version=7.13.2 一个是elasticsearch.version=7.13.2  这两个地方都需要改成 7.13.3，我开始漏掉了一个也是不行的，后面两个修改完了就行了。
