### ISSUE TITLE
什么时候出 7.13.4 版本的分词插件

### ISSUE THREAD

**Issue by gooking** [medcl/elasticsearch-analysis-ik#897]
什么时候出 7.13.4 版本的分词插件

现在安装的是 7.13.4 版本，但是现在插件的版本是 7.13.3 ，所以安装插件时候提示：

`Exception in thread "main" java.lang.IllegalArgumentException: Plugin [analysis-ik] was built for Elasticsearch version 7.13.3 but version 7.13.4 is running`

**Comment by isscy** [comment]
急需啊急需啊急需

**Comment by qifengzhang007** [comment]
7.13.3 竟然有严重漏洞，官方紧急推出了7.13.4
哎。心塞。

**Comment by suktec** [comment]
不会编译，等的焦急

**Comment by suktec** [comment]
> 急需啊急需啊急需
我编译了一个，安装吧
./elasticsearch-plugin install https://www.suksoft.com/elasticsearch-analysis-ik-7.13.4.zip

**Comment by suktec** [comment]
> 7.13.3 竟然有严重漏洞，官方紧急推出了7.13.4
> 哎。心塞。

我编译了一个，安装吧
./elasticsearch-plugin install https://www.suksoft.com/elasticsearch-analysis-ik-7.13.4.zip

**Comment by suktec** [comment]
> 不会编译，等的焦急

原来文档里面有说明，还能方便
`git clone https://github.com/medcl/elasticsearch-analysis-ik
cd elasticsearch-analysis-ik
git checkout tags/{version}
mvn clean
mvn compile
mvn package
`

**Comment by mianqiangsheng** [comment]
谢谢有用！

**Comment by medcl** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v7.13.4
