### ISSUE TITLE
ES集群上更改词典需要重启所有ES实例吗

### ISSUE THREAD

**Issue by CodeLieutenant** [medcl/elasticsearch-analysis-ik#90]
如题，假如，我使用的是ES集群（例如10个ES节点），那么，现在我想增加词，那么我是只需要在一个节点上更改词典配置文件并重启就行？还是需要更改所有10个节点，然后都重启？

**Comment by medcl** [comment]
每个都需要修改并重启

**Comment by niuhw** [comment]
分词插件是否必须安装到全部节点上？master或者client节点是否也有必要安装？为什么？

**Comment by CodeLieutenant** [comment]
都得装。。。
