### ISSUE TITLE
关于ik加入同义词的问题

### ISSUE THREAD

**Issue by hanleijun** [medcl/elasticsearch-analysis-ik#91]
想问一下，在analyzer中加入同义词，如果是在定义的filter中，加入类似synonyms: ["word1","word2"]
是可以的，但是希望读取本地的同义词文件：synonyms_path: synonyms.txt，这个txt中的同义词应该用什么形式写呢，我配了好几次，都没法识别，文本中写："word1,word2"  这样可以么。谢谢~

**Comment by medcl** [comment]
请访问论坛获取答案,
http://elasticsearch.cn/?/question/29
