### ISSUE TITLE
关于es调用ik的问题

### ISSUE THREAD

**Issue by whybangbang** [medcl/elasticsearch-analysis-ik#92]
我们在使用ik的过程中发现在建立索引的时候会调用IKAnalyzer，在搜索的时候就没有调用，我们从日志中看到的，而且搜索出来的结果也是这样的,请问为什么会发生这样的事情，我们在mapping中设置了 "indexAnalyzer": "ik",
                "searchAnalyzer": "ik",
es版本1.5.2 ik版本elasticsearch-analysis-ik-master
麻烦帮我解答一下

**Comment by wadekun** [comment]
我刚也遇到这样问题，发现是mapping中没有  searchAnalyzer:ik，的设置

**Comment by medcl** [comment]
这个是以前的参数名,后面版本调整了,最新的是analyzer和search_analyzer 请参照最新的README
