### ISSUE TITLE
编译报错，安装后启动es报错，想学习一下太难了

### ISSUE THREAD

**Issue by yellowgg** [medcl/elasticsearch-analysis-ik#923]
1.我一开始安装了最新版的es 7.16.0，然后安装ik时提示版本不一致，我就下载源码编译，一堆东西缺失，根本编译不起来
2.然后我就降级安装es 7.15.2，下载作者提供的ik v7.15.2的插件，[v7.15.2](https://github.com/medcl/elasticsearch-analysis-ik/releases/tag/v7.15.2)，然后安装完之后启动es还是报错，错误如下
```
java.lang.ClassNotFoundException: org.elasticsearch.plugin.analysis.ik.AnalysisIkPlugin
```
3.我继续下载v7.15.2的源码，打开之后依然还是一堆报错，找到上面的AnalysisIkPlugin类
![image](https://user-images.githubusercontent.com/27286340/145663049-ec8dc7e2-88d6-4fb8-834d-943baf540fb0.png)

**Comment by yellowgg** [comment]
@medcl

**Comment by yellowgg** [comment]
换成了7.14.2还是不行，呜呜呜
![image](https://user-images.githubusercontent.com/27286340/145679693-9f18dd35-8c05-4821-81e7-7b87ac0175d5.png)

**Comment by yellowgg** [comment]
我是sb哈哈
![PWP2NCYHK$1{ 5B~{X3{`V2](https://user-images.githubusercontent.com/27286340/145680390-4a84762d-5110-4053-a78d-44fe51b759f1.png)

**Comment by stupi-d** [comment]
@yellowgg 朋友你是怎么解决的呀，我也遇到这个问题了，如果看到了麻烦回我一下谢谢

**Comment by yellowgg** [comment]
> @yellowgg 朋友你是怎么解决的呀，我也遇到这个问题了，如果看到了麻烦回我一下谢谢

啊这，两年过去了，都忘了当时的情况了，不过从我的回复来看，应该是很简单的东西，可能是哪里没有设置好导致的，你再细心检查一下看看，一般都这样的，碰到的问题最后发现是很简单的原因，而且大部分原因都是因为粗心

**Comment by stupi-d** [comment]
> > @yellowgg 朋友你是怎么解决的呀，我也遇到这个问题了，如果看到了麻烦回我一下谢谢
> 
> 啊这，两年过去了，都忘了当时的情况了，不过从我的回复来看，应该是很简单的东西，可能是哪里没有设置好导致的，你再细心检查一下看看，一般都这样的，碰到的问题最后发现是很简单的原因，而且大部分原因都是因为粗心

朋友太感谢了！！！真的是一个很简单的错误（路径要放对），真的谢谢你，抱着试着问一下的态度，没想到你会这么快就回复我，不是看到你的回复说要仔细检查一下我可能就准备放弃这个地方了，改好之后最后试了一下然后成功了的感觉太棒了（主要是我找了几个小时的原因了T_T），反正就是真的真的感谢你！！！
