### ISSUE TITLE
ES 6.8.21版本

### ISSUE THREAD

**Issue by wwnaitang** [medcl/elasticsearch-analysis-ik#925]
你好，目前为了解决Log4j漏洞，官方建议先升级到6.8.21版本，但是这个版本没有ik分词器

**Comment by yixuan004** [comment]
+1 同求qaq

**Comment by yixuan004** [comment]
> 你好，目前为了解决Log4j漏洞，官方建议先升级到6.8.21版本，但是这个版本没有ik分词器

https://github.com/medcl/elasticsearch-analysis-ik/releases
