### ISSUE TITLE
关于ik加入同义词的问题

### ISSUE THREAD

**Issue by hanleijun** [medcl/elasticsearch-analysis-ik#93]
我是这样配置的 ，还是不起作用，index用的max的，search用的smart的，然后加载的同义词库也是没问题的，请教一下这个配置的有问题么，谢谢  
      ik_max_word:
           type: ik
          use_smart: false
      ik_smart:
          type: custom
          tokenizer: ik
          filter: [sysfilter]
          use_smart: true

**Comment by zh6335901** [comment]
你的同义词是否是中文的呢，我遇到这样的问题：中文同义词没有效果，英文同义词可以工作

**Comment by medcl** [comment]
请问你的词典文件是否是utf8格式呢?

**Comment by zh6335901** [comment]
你好，我确认了下我的词典文件是utf8格式的，但是中文还是无效

**Comment by medcl** [comment]
参照这个贴 应该是可以的,是不是哪里弄的不对,你贴一下过程  http://elasticsearch.cn/?/question/29

**Comment by zh6335901** [comment]
多谢回复，我之前就是参照这个帖子的，后面我调试了下发现配置是正确的，指定对应的analyzer分析中文词同义词是生效的。问题出在了查询上，我查询是用的match:
    {
      "query" : {
        "match" : {
          "name" : {
            "query" : "马铃薯",
            "operator" : "and",
            "analyzer" : "ik_syno"
          }
        }
      }
    }
这样的话，结果只有马铃薯。但是我把match的参数operator改成`or`的时候，同义词就生效了，查询出现马铃薯和土豆两个结果。发现了问题所在的地方，但是不是很理解为什么operator参数为`and`的时候中文同义词无效。
奇怪的是，不管operator参数是什么，因为英文同义词都是可以的。
下面是测试用的同义词词典:
    土豆, 马铃薯
    番茄, 西红柿
    foozball, foosball

我ElasticSearch的版本是1.50

**Comment by zh6335901** [comment]
多谢回复，找到问题所在了，并不是配置的问题。是我自己查询的问题，我查询用的是match，并且把operator设置为`and`，但是ik_syno分析器分析的结果是这个:
```
{
  "tokens" : [ {
    "token" : "土豆",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "SYNONYM",
    "position" : 1
  }, {
    "token" : "马铃薯",
    "start_offset" : 0,
    "end_offset" : 3,
    "type" : "SYNONYM",
    "position" : 1
  }, {
    "token" : "铃",
    "start_offset" : 1,
    "end_offset" : 2,
    "type" : "CN_WORD",
    "position" : 2
  }, {
    "token" : "薯",
    "start_offset" : 2,
    "end_offset" : 3,
    "type" : "CN_WORD",
    "position" : 3
  } ]
}
```

**Comment by node** [comment]
ls 你的同义词词典格式不太对吧？ 试试这样的：

土豆 => 马铃薯 
番茄 => 西红柿

**Comment by squarehuang** [comment]
请问一下我设置tokenizer: ik，再使用synonym token filter可以实现同义词功能，但use_smart参数设置不起作用，是有少了什么设定吗? (ik_syno_smart)
analyzer:
  ik:
          alias: [ik_analyzer]
          type: org.elasticsearch.index.analysis.IkAnalyzerProvider
      ik_max_word:
          type: ik
          use_smart: false
      ik_smart:
          type: ik
          use_smart: true
      ik_syno_smart:
          type: custom
          tokenizer: ik
          filter: [my_synonym_filter]
          use_smart: true
filter:
      my_synonym_filter:
          type: synonym
          synonyms_path: analysis/synonym.txt

**Comment by JohnTian** [comment]
## 同义词配置

### step 1

`elasticserach.yml` 最后一行添加：
`index.analysis.analyzer.default.type: ik`

### step 2

在`elasticsearch-2.3.1/config`目录下面，存放`synonyms.txt`

其中，synonyms.txt 编码格式为'utf-8'，内容为：

    #Example:
    ipod, i-pod, i pod
    foozball , foosball
    universe , cosmos
    西红柿, 番茄
    马铃薯, 土豆
    aa, bb

### step 3

新建立索引类型设置
```
curl -XPUT localhost:9200/test/_mapping?pretty -d '
{
  "settings": {
    "index": {
      "analysis": {
        "analyzer": {
          "jt_cn": {
            "type": "custom",
            "use_smart": "true",
            "tokenizer": "ik_smart",
            "filter": ["jt_tfr","jt_sfr"],
            "char_filter": ["jt_cfr"]
          },
          "ik_smart": {
            "type": "ik",
            "use_smart": "true"
          },
          "ik_max_word": {
            "type": "ik",
            "use_smart": "false"
          }
        },
        "filter": {
          "jt_tfr": {
            "type": "stop",
            "stopwords": [" "]
          },
          "jt_sfr": {
            "type": "synoym",
            "synonyms_path": "synonyms.txt"
          }
        },
        "char_filter": {
            "jt_cfr": {
                "type": "mapping",
                "mappings": [
                    "| => \\|"
                ]
            }
        }
      }
    }
  },
  "mappings": {
    "solution": {
      "properties": {
        "title": {
          "include_in_all": true,
          "analyzer": "jt_cn",
          "term_vector": "with_positions_offsets",
          "boost": 8,
          "store": true,
          "type": "string"
        }
      }
    }
  }
}
'
```


### step 4

    curl -XPUT localhost:9200/test/solution/1 -d '
    {
        "title": "番茄"
    }
    '
    curl -XPUT localhost:9200/test/solution/2 -d '
    {
        "title": "西红柿"
    }
    '


### step 5

    curl -XPOST 'localhost:9200/test/solution/_search?pretty' -d '
    {
      "query": {
        "query_string": {
          "title": {
            "query": "西红柿",
            "analyzer": "jt_cn"
          }
        }
      },
      "highlight": {
        "pre_tags": [
          "<tag1>",
          "<tag2>"
        ],
        "post_tags": [
          "</tag1>",
          "</tag2>"
        ],
        "fields": {
          "title": {}
        }
      }
    }
    '

结果：
```
    {
      "took": 3,
      "timed_out": false,
      "_shards": {
        "total": 5,
        "successful": 5,
        "failed": 0
      },
      "hits": {
        "total": 2,
        "max_score": 0.4500804,
        "hits": [
          {
            "_index": "test",
            "_type": "solution",
            "_id": "1",
            "_score": 0.4500804,
            "_source": {
              "title": "西红柿"
            }
          },
          {
            "_index": "test",
            "_type": "solution",
            "_id": "2",
            "_score": 0.36006433,
            "_source": {
              "title": "番茄"
            }
          }
        ]
      }
    }
```

**Comment by lyk2112** [comment]
你好，我有一个问题。例如我字典有一个词“ideapad311”,max_word分词分出term"ideapad311","ideapad","311",但smart_word分出只有“ideapad311”,当加上空格为"ideapad","311",我怎样才能让ik_smart识别出"ideapad","311"两个term??谢谢

**Comment by 5452** [comment]
不能互为同义词，如果两个词是同义词的话需要添加两遍同义词词典，比如：一行：番茄，西红柿，第二行：西红柿，番茄。这个是试验得出的结论，真的是这样的话，如果我有很多词都表示一个意义，岂不是要添加很多遍？而且添加很多遍也不一定可行？

**Comment by ChopperLee2011** [comment]
贴一段👆的配置在5.x后出现的错误：
```
2018-03-31T04:23:34.195515742Z 
Since elasticsearch 5.x index level settings can NOT be set on the nodes 
configuration like the elasticsearch.yaml, in system properties or command line 
arguments.In order to upgrade all indices the settings must be updated via the 
/${index}/_settings API. Unless all settings are dynamic all indices must be closed 
in order to apply the upgradeIndices created in the future should use index templates 
to set default values. 
2018-03-31T04:23:34.195627187Z 
Please ensure all required values are updated on all indices by executing: 
2018-03-31T04:23:34.195659571Z 
curl -XPUT 'http://localhost:9200/_all/_settings?preserve_existing=true' -d '{
  "index.analysis.analyzer.default.type" : "ik"
}'
*************************************************************************************
```
提示说不要更改yml，需要直接通过http调用API去update setting

**Comment by medcl** [comment]
@ChopperLee2011 把 ik修改成ik_smart或ik_max_word不就行了？

**Comment by ChopperLee2011** [comment]
@medcl 我的版本是6.1，没有更改elasticsesarch.yml，也没有调用/_all/_settings，直接做的step 3，是有效果的。

**Comment by bsc2xp** [comment]
char_filter 里把  \ 映射为 \\| 是为了什么？转义？

**Comment by bsc2xp** [comment]
另外请问各位 ，jt_tfr 里的停用词数组为空，默认会使用 ik 的 tokenizer 的停用词配置么？         
` "jt_tfr": {
            "type": "stop",
            "stopwords": [" "]
          }`
