### ISSUE TITLE
为什么我下载的没有jar包，是一个mavern项目，然后运行es闪退

### ISSUE THREAD

**Issue by Rain-with-me** [medcl/elasticsearch-analysis-ik#940]
为什么我下载的没有jar包，是一个mavern项目，然后运行es闪退，请求指导一下

**Comment by medcl** [comment]
从 release 下载编译好的，你下的是源码

**Comment by Rain-with-me** [comment]
谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月24日(周二) 下午2:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [medcl/elasticsearch-analysis-ik] 为什么我下载的没有jar包，是一个mavern项目，然后运行es闪退 (Issue #940)




 
从 release 下载编译好的，你下的是源码
