### ISSUE TITLE
Why cloud service manufacturers use open source software for free and don't fix open source software's bugs

### ISSUE THREAD

**Issue by marmot-z** [medcl/elasticsearch-analysis-ik#945]
#662 该问题在18年就已修复，但至今（2022.05.13） 阿里云 ElasticSearch 6.7 版本的 ik 插件仍未修复该问题。追问其原因，答曰 ik 插件属于第三方软件，没有办法修复！为什么这些云服务商免费使用着开源软件进行盈利，而对开源软件的问题修复毫不关心，脸都不要了！！！

**Comment by medcl** [comment]
我来更新一下 6.7的分支

**Comment by medcl** [comment]
分支已 revert 上一个 commit
