### ISSUE TITLE
为什么找不到ES7.17.4对应的ik分词器版本？

### ISSUE THREAD

**Issue by varGengYang** [medcl/elasticsearch-analysis-ik#946]
**7.17.4可以对应使用哪个版本的IK分词器呢？**

![image](https://user-images.githubusercontent.com/31209135/170807067-b9074dfd-18f3-4bd2-81dd-21448dc981f9.png)

![image](https://user-images.githubusercontent.com/31209135/170808042-06ab09f0-12a7-451c-894a-1278bb9c33fe.png)

**Comment by ChunzhiAoe** [comment]
我也在寻找。。

**Comment by medcl** [comment]
已经发布
