### ISSUE TITLE
版本对应问题请教

### ISSUE THREAD

**Issue by varGengYang** [medcl/elasticsearch-analysis-ik#947]
图中ik6.x对应es6.x能看懂，红框里的master对应7.x-->master，不太理解，是不是当前master版本可以应用到ES 7.x之后的所有版本呢？ES 7.17.4，能否使用ik 8.x  ？  麻烦帮忙解惑

![image](https://user-images.githubusercontent.com/31209135/170808115-6865d0d3-ae4d-4527-a6c1-4230ef78d28d.png)

**Comment by varGengYang** [comment]
No

**Comment by JaneYork** [comment]
> No

必须ES版本和IK的release版本号一致？
