### ISSUE TITLE
elasticsearch8.3.1 启动ik报错

### ISSUE THREAD

**Issue by adi100** [medcl/elasticsearch-analysis-ik#958]
[2022-07-06T14:41:08,101][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elk1] fatal error in thread [elasticsearch[elk1][masterService#updateTask][T#1]], exiting
java.lang.NoSuchMethodError: 'void org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider.<init>(org.elasticsearch.index.IndexSettings, java.lang.String, org.elasticsearch.common.settings.Settings)'
        at org.elasticsearch.index.analysis.IkAnalyzerProvider.<init>(IkAnalyzerProvider.java:13) ~[?:?]

**Comment by RyanHu** [comment]
换8.2.3要不然就再等等

**Comment by SusanZhang1993** [comment]
es8.3.3 安装8.2.3的分词器 启动也报此错误 ，想问下怎么解决

**Comment by SusanZhang1993** [comment]
> [2022-07-06T14:41:08,101][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [elk1] fatal error in thread [elasticsearch[elk1][masterService#updateTask][T#1]], exiting java.lang.NoSuchMethodError: 'void org.elasticsearch.index.analysis.AbstractIndexAnalyzerProvider.(org.elasticsearch.index.IndexSettings, java.lang.String, org.elasticsearch.common.settings.Settings)' at org.elasticsearch.index.analysis.IkAnalyzerProvider.(IkAnalyzerProvider.java:13) ~[?:?]

请问你怎么解决的
