### ISSUE TITLE
使用ik后如果单词里有“基” 这个字就会报编码错误

### ISSUE THREAD

**Issue by linjianzao** [medcl/elasticsearch-analysis-ik#96]
mapping:

curl -XPOST http://localhost:9200/index1/resource/_mapping -d'
{
    "resource": {
             "_all": {
            "analyzer": "ik"
        },
        "properties": {
            "title": {
                "type" : "string",
                "boost" : 8.0,
                "term_vector" : "with_positions_offsets",
                "analyzer" : "ik",
                "include_in_all" : true
            }
        }
    }
}'

插入数据:

curl -XPUT 'http://localhost:9200/index1/resource/1?pretty=true' -d '{
  "title" : "世界如此之基"
}'

返回错误:
{
  "error" : "MapperParsingException[failed to parse [title]]; nested: JsonParseException[Invalid UTF-8 middle byte 0xc0\n at [Source: [B@6428ddc2; line: 2, column: 16]]; ",
  "status" : 400
}

但是 当我把IK关闭后 ，就不会报错了

**Comment by medcl** [comment]
请问你用的es什么版本呢?我刚用1.7.1的rtf试了一下,没有重现

```

➜  ~  curl -XPUT  localhost:9200/index1
{"acknowledged":true}%                                                          ➜  ~  curl -XPOST http://localhost:9200/index1/resource/_mapping -d'
{
"resource": {
"_all": {
"analyzer": "ik"
},
"properties": {
"title": {
"type" : "string",
"boost" : 8.0,
"term_vector" : "with_positions_offsets",
"analyzer" : "ik",
"include_in_all" : true
}
}
}
}'
{"acknowledged":true}%                                                          ➜  ~  curl -XPUT 'http://localhost:9200/index1/resource/1?pretty=true' -d '{
quote> "title" : "世界如此之基"
quote> }'
{
  "_index" : "index1",
  "_type" : "resource",
  "_id" : "1",
  "_version" : 1,
  "created" : true
}

```

**Comment by linjianzao** [comment]
谢谢你的回复。 
我好像找到问题了， 我用的xshell 然后编码没改。
但是我用elasticsearch-py 操作还是会有报错，应该也是相同问题。
非常感谢，是我自己没注意

**Comment by linjianzao** [comment]
现在如果我输入
 curl -XPUT 'http://localhost:9200/index1/resource/1?pretty=true' -d '{
  "title" : "基友"
}'

会报错：
{
  "error" : "StringIndexOutOfBoundsException[String index out of range: -1]",
  "status" : 500
}

如果输入的是：
curl -XPUT 'http://localhost:9200/index1/resource/1?pretty=true' -d '{
  "title" : "朋友 "
}'
那结果是正常的。
请问这是我分词的原因还是其他的

**Comment by medcl** [comment]
无法重现!
