### ISSUE TITLE
请问7.17.6版本还会更新吗？

### ISSUE THREAD

**Issue by aquliu** [medcl/elasticsearch-analysis-ik#965]
QAQ

**Comment by hutaoseven** [comment]
参考这个 [https://github.com/medcl/elasticsearch-analysis-ik/issues/960](https://github.com/medcl/elasticsearch-analysis-ik/issues/960) 自己编译

**Comment by Wesley-GONG** [comment]
不会弄，哪位好心人有编译好的7.17.6，丢一个吧？

**Comment by Wesley-GONG** [comment]
@aquliu 没弄过Java的东西，研究了一下午，编译出来了，请下载

https://github.com/Wesley-GONG/elasticsearch-analysis-ik/releases/tag/elasticsearch-analysis-ik
