### ISSUE TITLE
8.4.0 下载

### ISSUE THREAD

**Issue by niu-dali** [medcl/elasticsearch-analysis-ik#966]
[elasticsearch-analysis-ik-8.4.0.zip](https://github.com/medcl/elasticsearch-analysis-ik/files/9441312/elasticsearch-analysis-ik-8.4.0.zip)

**Comment by RainingNight** [comment]
有没有8.4.1

**Comment by samxu007** [comment]
能否帮忙编译下8.4.1

**Comment by wozl** [comment]
> 有没有8.4.1

参考[参考](https://github.com/medcl/elasticsearch-analysis-ik/issues/960)

**Comment by RainingNight** [comment]
> 

能否帮忙编译下8.4.1

**Comment by RainingNight** [comment]
> > 有没有8.4.1
> 
> 参考[参考](https://github.com/medcl/elasticsearch-analysis-ik/issues/960)

能否帮忙编译下8.4.1

**Comment by niu-dali** [comment]
更新这么快的吗？

**Comment by wozl** [comment]
> 更新这么快的吗？
这个很正常啊，一周一个版本

**Comment by wozl** [comment]
> > > 有没有8.4.1
> > 
> > 
> > 参考[参考](https://github.com/medcl/elasticsearch-analysis-ik/issues/960)
> 
> 能否帮忙编译下8.4.1
参考后你就会编译了，很简单的，多琢磨琢磨，有助于你的技术增长的。

**Comment by RainingNight** [comment]
> 更新这么快的吗？

坐等大佬

**Comment by wozl** [comment]
> > 更新这么快的吗？
> 
> 坐等大佬
那您继续等吧，哎，怎么都是伸手要的呢，花时间研究下都舍不得么

**Comment by RainingNight** [comment]
> > > 更新这么快的吗？
> > 
> > 
> > 坐等大佬
> > 那您继续等吧，哎，怎么都是伸手要的呢，花时间研究下都舍不得么

问题是不会Java啊

**Comment by wozl** [comment]
> > > > 更新这么快的吗？
> > > 
> > > 
> > > 坐等大佬
> > > 那您继续等吧，哎，怎么都是伸手要的呢，花时间研究下都舍不得么
> 
> 问题是不会Java啊

那就降版本吧，那个参考地址里面有人建了个自动编译的工作流，您看下他那边有没有更新最新的吧

**Comment by niu-dali** [comment]
> > 更新这么快的吗？
> 
> 坐等大佬

https://github.com/medcl/elasticsearch-analysis-ik/issues/968
