### ISSUE TITLE
扩展词库只有部分生效

### ISSUE THREAD

**Issue by themez** [medcl/elasticsearch-analysis-ik#98]
你好，我在扩展词库`mydict.dic`中添加了几个条目(如下)，重启es后发现只有`谷大白话`这个生效了(和添加之前相比几个不相关的结果被过滤了)，其他几个条目依然会搜索出很多不相关内容，ik的配置文件都是从 elasticsearch-rtf项目中下载的，请问我该怎么修改配置，或是查找可能的原因？
```
medcl
INFINITBYTE
阮一峰
谷大白话
曼联
```

**Comment by medcl** [comment]
修改词库之后,之前的数据需要重建

**Comment by themez** [comment]
@medcl 我看到文档中有热更新分词，用热更新的方法也需要重建数据吗

**Comment by okuc** [comment]
@themez 好像热更新分词也需要对之前的数据重建，这也是一直让我头疼的地方，当数据量很大时重建数据，并不是一件易事。

**Comment by medcl** [comment]
如果业务中需要经常更新热词,可能用这种方案不合适

**Comment by medcl** [comment]
@themez 重建数据解决问题了么?

**Comment by themez** [comment]
@medcl 暂时也没有更好的方案, 这个先close吧.
