### ISSUE TITLE
When Will 7.17.7 be supported

### ISSUE THREAD

**Issue by 15083030770** [medcl/elasticsearch-analysis-ik#981]

**Comment by WillMeng** [comment]
Please support 7.17.7, thanks.

**Comment by jingjian-1420** [comment]
Please support 7.17.7, thanks.

**Comment by HDHXTM** [comment]
we can use  7.17.6:

unzip elasticsearch-analysis-ik-7.17.6.zip
vi  plugin-descriptor.properties
modify elasticsearch.version=7.17.6   to   elasticsearch.version=7.17.7
restart es
ok,ik is working

**Comment by ElisaMin** [comment]
I build one for 7.17.10 https://github.com/ElisaMin/elasticsearch-analysis-ik/releases/tag/7.17.10

**Comment by keweiLv** [comment]
nice,7.17.10

**Comment by shandy-0** [comment]
so funny
