### ISSUE TITLE
请问 es1.7.2 ik支持了吗?

### ISSUE THREAD

**Issue by Lywangwenbin** [medcl/elasticsearch-analysis-ik#99]
用现在master分支的源码 修改pom es的版本为1.7.2 打包后，启动es，词库不能完全加载，使用ik分词会报错
es-version: 1.7.2
mvn package 打包得到jar包，放到es plugins目录，并将config中ik目录放到es的config目录中，最后在elasticsearch.yml结尾中配置(照着仓库 readme复制的)：
index:
analysis:
analyzer:
ik:
alias: [ik_analyzer]
type: org.elasticsearch.index.analysis.IkAnalyzerProvider
ik_max_word:
type: ik
use_smart: false
ik_smart:
type: ik
use_smart: true
然后启动elastic search 正常，词库 在执行[Dict Loading]ik/custom/ext_stopword.dic到这里停在那了，然后请求http://localhost:9200/_analyze?analyzer=ik&pretty=true&text=我是中国人 就会报错
{
"error" : "ElasticsearchIllegalArgumentException[failed to find analyzer [ik]]",
"status" : 400
}

**Comment by manbusky** [comment]
我用的ES版本1.7.2与你遇到同样的问题；

看到最近的"pom.xml"文件的commit注释是："update elasticsearch to 1.6.2"，于是我就切换到 ES 1.6.2 版本就没问题了，测试成功；

**Comment by Lywangwenbin** [comment]
@manbusky  这么说ik最新支持到1.6.2啊

**Comment by manbusky** [comment]
@Lywangwenbin 
我看到那个commit log，做的版本切换；

作者邮件回复说可以支持到1.7.1，我没有尝试；

**Comment by medcl** [comment]
没问题,支持的
