### ISSUE TITLE
不支持7.17.8版本

### ISSUE THREAD

**Issue by ichenkaihua** [medcl/elasticsearch-analysis-ik#996]

**Comment by hqhangyu** [comment]
我也需要这个版本的ik，有计划发布吗

**Comment by mateJay** [comment]
下载相近的版本，解压后修改plugin-descriptor.properties文件里面的elasticsearch.version就可以

**Comment by djdgtg** [comment]
> 下载相近的版本，解压后修改plugin-descriptor.properties文件里面的elasticsearch.version就可以

牛逼

**Comment by Zhangruixin2333** [comment]
> 强的一

**Comment by ChenBigBig** [comment]
Good!

**Comment by shandy-0** [comment]
我试过了，这样不行

**Comment by iamgd67** [comment]
> 我试过了，这样不行

可以的，重新打成zip后，如果要用`./bin/elasticsearch-plugin install`来安装，要用  `file:///path/file` 这样的路径，不然会识别成plugin id，报`ERROR: Unknown plugin elasticsearch-analysis-ik-7.17.8.zip`

**Comment by iamgd67** [comment]
不过我用7.17.7的ik和 7.17.8的es，报了 
`startOffset must be non-negative, and endOffset must be >= startOffset, and offsets must not go backwards startOffset=94,endOffset=98,lastStartOffset=128 for field 'log'`
