### ISSUE TITLE
Does  not support version 7.17.8?

### ISSUE THREAD

**Issue by hqhangyu** [medcl/elasticsearch-analysis-ik#997]
i chose this version of es for my system，but i can't find  the version of ik supported it,can you  tell me the plan  about it.what time ready  release it ?

**Comment by renzcu** [comment]
https://github.com/medcl/elasticsearch-analysis-ik/issues/981#issuecomment-1316437263

**Comment by hqhangyu** [comment]
> [#981 (comment)](https://github.com/medcl/elasticsearch-analysis-ik/issues/981#issuecomment-1316437263)

太美
